package wifihaven.api.tools

import wifihaven.api.PressOutreachConfig
import wifihaven.api.notify.{EmailOutcome, EmailSender}
import wifihaven.api.press.PressOutreach
import zio.*

import java.nio.file.{Files, Path, Paths}

/**
 * #2233 — generator for the reviewable press-outreach DRY-RUN artifact.
 *
 * Run it with:
 * {{{
 * mill api.test.runMain wifihaven.api.tools.PressDryRunArtifact
 * }}}
 *
 * It drives `PressOutreach.run` with `confirmed = false` over the BUNDLED manifest and the BUNDLED
 * release, and writes what each recipient would actually receive to
 * `evidence/2233-press-dry-run.md` — the rendered HTML body, not a paraphrase of it.
 *
 * ==Why the HTML and not the text==
 *
 * #2677 shipped literal `**` asterisks to a journalist because the only thing anyone ever looked at
 * was the plain-text side of a message whose HTML part was the one that got sent. The composer
 * emits ONE body and it is HTML, so the artifact records the HTML verbatim. A reviewer opening it
 * can see markdown that failed to render, because unrendered markdown is visible as markdown.
 *
 * ==Why this cannot send==
 *
 * Two independent reasons, either sufficient. `confirmed = false` means `run` short-circuits every
 * contact to `DryRun` before reaching the transport at all; and the [[EmailSender]] passed in
 * throws if it is ever invoked, so a future change that broke the first reason would fail loudly
 * here rather than quietly mailing 21 journalists from a developer's laptop.
 *
 * It lives in test sources, not `api/src`: it is a review tool, not a shipped code path.
 */
object PressDryRunArtifact extends ZIOAppDefault {

  /** The transport that proves the point: invoking it at all is the bug. */
  private val neverSends: EmailSender = new EmailSender {
    // `sendAs` (what the outreach loop calls) delegates to `send` by default in the trait, so
    // overriding this one method covers both entry points.
    def send(to: String, subject: String, htmlBody: String): UIO[EmailOutcome] =
      ZIO.die(new IllegalStateException(s"dry-run artifact attempted a real send to $to"))
  }

  private val cfg = PressOutreachConfig(
    enabled = true,
    fromAddress = "WifiHaven Press <press@wifihaven.net>",
    replyTo = "press@wifihaven.net",
    perSendDelayMillis = 0,
  )

  /**
   * Placeholder fills, clearly marked as such. The real values are the operator's to supply at send
   * time; using obvious sentinels here means a reader can never mistake the artifact for the sent
   * article, and the unresolved-token guard is exercised with them present.
   */
  private val fill = Map(
    "date"          -> "August 17, 2026",
    "founderName"   -> "[FOUNDER NAME — operator supplies at send]",
    "betaSignupUrl" -> "https://app.wifihaven.net/beta",
    "pressKitUrl"   -> "[PRESS KIT URL — operator supplies at send]",
  )

  private val repoRoot: Path = {
    var cur: Path = Paths.get(sys.props.getOrElse("user.dir", ".")).toAbsolutePath
    while cur != null && !Files.isDirectory(cur.resolve("api/src")) do cur = cur.getParent
    if cur == null then sys.error("could not locate repo root (api/src) from user.dir")
    cur
  }

  private val OutPath = "evidence/2233-press-dry-run.md"

  def run =
    for {
      contacts <- PressOutreach.loadContacts()
      template <- PressOutreach.loadReleaseTemplate()
      report   <- PressOutreach.run(
        contacts = contacts,
        rawReleaseTemplate = template,
        fill = fill,
        cfg = cfg,
        sender = neverSends,
        confirmed = false,
      )
      out    = render(report)
      target = repoRoot.resolve(OutPath)
      _ <- ZIO.attempt(Files.createDirectories(target.getParent))
      _ <- ZIO.attempt(Files.writeString(target, out))
      _ <- Console.printLine(
        s"wrote $OutPath (${report.totalContacts} recipients, mode=${report.mode})",
      )
    } yield ()

  private def render(r: PressOutreach.Report): String = {
    val header =
      s"""# #2233 press outreach — staged DRY-RUN batch
         |
         |Generated by `mill api.test.runMain wifihaven.api.tools.PressDryRunArtifact`.
         |
         |**No email was sent to produce this file.** The run is `confirmed = false`, and the
         |`EmailSender` it was given fails the process if invoked. Every recipient below resolves to
         |`dry_run`.
         |
         || field | value |
         ||---|---|
         || mode | `${r.mode}` |
         || recipients | ${r.totalContacts} |
         || emailable (a resolvable address today) | ${r.emailable} |
         || form-only (manual submission via `contactUrl`) | ${r.formOnly} |
         || unresolved release tokens | ${
          if r.unresolvedPlaceholders.isEmpty then "none"
          else r.unresolvedPlaceholders.mkString("`", "`, `", "`")
        } |
         |
         |`emailable` is ${r.emailable} because no target has a verified published address in-repo —
         |the operator supplies addresses at send time via `emailOverrides`. That is the fabrication
         |rule, not a bug.
         |
         |Each section below is the exact HTML body the recipient's mail client would render. It is
         |shown as raw HTML deliberately: unrendered markdown is visible as markdown here, which is
         |the check #2677 existed for.
         |
         |## Per-recipient outcomes
         |
         || contact | outlet | outcome | to |
         ||---|---|---|---|
         |""".stripMargin

    val table = r.results
      .map(x => s"| `${x.contactId}` | ${x.outlet} | `${x.outcome}` | ${x.to.getOrElse("—")} |")
      .mkString("\n")

    val bodies = r.emails
      .map { e =>
        s"""
           |---
           |
           |## ${e.outlet} — ${e.person} (`${e.contactId}`)
           |
           |- **From:** `${e.from}`
           |- **Reply-To:** `${e.replyTo}`
           |- **To:** ${e.to
            .map(t => s"`$t`")
            .getOrElse("_(form-only — no address; submit manually)_")}
           |- **Subject:** ${e.subject}
           |
           |```html
           |${e.htmlBody}
           |```
           |""".stripMargin
      }
      .mkString("\n")

    header + table + "\n" + bodies
  }
}
