-- V82__household_settings_id_identity.sql
-- #2386: make household_settings.id auto-generate so every household can own
-- its OWN settings row (multi-tenant isolation, epic #2085/#622) —
-- schema-only foundation for the cross-tenant-leak fix.
--
-- Background: `household_settings.id` was `INT PRIMARY KEY CHECK (id = 1)`
-- (V16) — a hand-pinned singleton back when settings were install-global.
-- V65 added `household_id` + `uq_household_settings_household =
-- UNIQUE(household_id)`, and V75 dropped the `id = 1` CHECK, so the table can
-- now legally hold one row per household. But `id` still has NO default/
-- sequence, so nothing can INSERT a second row without hand-picking an id —
-- which is why no provisioning path ever seeded a per-household settings row,
-- and `getForHousehold` silently fell back to household #1's row (the #2386
-- leak). Attaching an identity to `id` is the one schema change the fix needs;
-- the seed-on-create + boot backfill + fail-loud read land in the follow-up
-- source PR (#2386).
--
-- GENERATED BY DEFAULT (not ALWAYS): the existing `ensureDefault` INSERT still
-- supplies `id = 1` explicitly (`ON CONFLICT (id) DO NOTHING`), and BY DEFAULT
-- lets an explicit value win over the sequence, so that seed keeps working
-- unchanged. New per-household inserts omit `id` and let the sequence fill it.
--
-- The sequence is advanced past the current max id so a generated value can
-- never collide with the existing id=1 (or any hand-inserted row): `setval`
-- to MAX(id) sets the NEXT generated value to MAX(id)+1.
--
-- SCHEMA-ONLY PR (per docs/process/migrations.md#migrations-back-compat): SQL +
-- docs only, no source/tests. image-(N-1) — which only ever inserts id=1 — is
-- unaffected: BY DEFAULT identity permits the explicit id, and the sequence
-- starts at 2. The unconditional (#2098) feature suite applying this over the
-- seeded schema (embedded Postgres) is the clean-apply / back-compat gate.
--
-- `household_settings` is a small singleton-today metadata table, NOT one of
-- the unbounded-growth event tables. Attaching an identity creates a sequence
-- and sets the column default (catalog metadata) — no table rewrite, no scan —
-- so this is safe on the Flyway startup critical path even at prod data volume
-- (docs/process/migrations.md#migrations-prod-data-volume).

ALTER TABLE household_settings
  ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Set the identity sequence's next value to MAX(id)+1 so a generated id can
-- never collide with an already-present row (today just id=1).
SELECT setval(
  pg_get_serial_sequence('household_settings', 'id'),
  (SELECT COALESCE(MAX(id), 1) FROM household_settings)
);
