package familydns.api.feature

import familydns.api.db.*
import familydns.api.routes.*
import familydns.shared.*
import zio.*
import zio.http.*
import zio.json.ast.Json
import zio.json.*
import zio.test.*

import java.sql.SQLException
import java.time.Instant
import java.util.UUID

/**
 * Covers #310: API must return 503 (not bare 500) when the DB throws, so the OpenWRT agent can
 * distinguish transient failures from genuine errors. See docs/resilience.md §3 and
 * api/src/routes/ErrorMapper.scala.
 */
object DbFailureSpec extends ZIOSpecDefault {

  private val secretMsg =
    "ERROR: relation \"secret_users_table\" does not exist at line 42"

  /**
   * RouterAuth stub: always fails with the given throwable. Simulates a DB outage at the auth step.
   */
  private def failingAuth(t: Throwable): RouterAuth =
    new RouterAuth {
      def authenticate(req: Request): IO[Response, Router] =
        ZIO.fail(t).mapError(ErrorMapper.dbErrorToResponse)
    }

  /** RouterAuth stub: succeeds with a synthetic Router; never touches the DB. */
  private def okAuth(routerId: UUID): RouterAuth =
    new RouterAuth {
      def authenticate(req: Request): IO[Response, Router] =
        ZIO.succeed(
          Router(
            id = routerId,
            name = "test",
            enrollmentTokenHash = Some("hash"),
            tokenHash = Some("hash"),
            lastSeenAt = None,
            lastEtag = None,
            createdAt = "2026-05-13T00:00:00Z",
          ),
        )
    }

  /**
   * Stub repos: every method throws SQLException. Defeats the type system but matches the failure
   * mode under test — calling code wraps these via `.mapError(ErrorMapper.dbErrorToResponse)`.
   */
  private def throwing[A]: Task[A] = ZIO.fail(new SQLException(secretMsg))

  private def brokenRouterRepo: RouterRepo = new RouterRepo {
    def listAll                                 = throwing
    def findById(id: UUID)                      = throwing
    def findByEnrollmentTokenHash(h: String)    = throwing
    def findByTokenHash(h: String)              = throwing
    def create(n: String, h: String)            = throwing
    def completeEnrollment(id: UUID, h: String) = throwing
    def touch(id: UUID, etag: Option[String])   = throwing
    def delete(id: UUID)                        = throwing
  }

  private def brokenTrafficRepo: TrafficReportRepo = new TrafficReportRepo {
    def insertBatch(rs: List[TrafficReportInsert])                   = throwing
    def listForDevice(mac: String, d: java.time.LocalDate)           = throwing
    def listForRouter(r: UUID, l: Int)                               = throwing
    def listSessionRows(f: SessionFilter)                            = throwing
    def listPresenceRows(macs: List[String], d: java.time.LocalDate) = throwing
  }

  private def brokenTimeUsageRepo: TimeUsageRepo = new TimeUsageRepo {
    def incrementSecondsAndBytes(
        mac: String,
        domain: String,
        date: java.time.LocalDate,
        s: Long,
        bi: Long,
        bo: Long,
    ) = throwing
    def getSecondsUsed(mac: String, domain: String, date: java.time.LocalDate)     = throwing
    def getSecondsAndBytes(mac: String, domain: String, date: java.time.LocalDate) = throwing
    def listForDevice(mac: String, date: java.time.LocalDate)                      = throwing
    def listForDeviceMacs(macs: List[String], date: java.time.LocalDate)           = throwing
    def snapshotAll(date: java.time.LocalDate)                                     = throwing
  }

  private def brokenDeviceRepo: DeviceRepo = new DeviceRepo {
    def listAll                                                                   = throwing
    def findByMac(mac: String)                                                    = throwing
    def upsert(mac: String, name: String, pid: Long, ip: String)                  = throwing
    def updateLastSeen(mac: String, ip: String)                                   = throwing
    def touchLastSeen(mac: String, ip: Option[String], at: Instant)               = throwing
    def upsertUnknown(mac: String, name: String, ip: Option[String], at: Instant) = throwing
    def renameIfAutoGenerated(mac: String, newName: String)                       = throwing
    def updateProfile(mac: String, pid: Long)                                     = throwing
    def delete(mac: String)                                                       = throwing
  }

  private def brokenConnectionEventRepo: ConnectionEventRepo = new ConnectionEventRepo {
    def insertBatch(es: List[ConnectionEventInsert]) = throwing
    def recent(l: Int)                               = throwing
    def listForMac(mac: String, l: Int)              = throwing
    def listForRouter(r: UUID, l: Int)               = throwing
    def query(f: LogFilter)                          = throwing
    def stats                                        = throwing
    def topBlocked(h: Int, l: Int)                   = throwing
    def lastSeenByMacSince(since: Instant)           = throwing
  }

  private def jsonField(body: String, key: String): Option[String] =
    body.fromJson[Json].toOption.flatMap(_.asObject).flatMap(_.get(key)).flatMap(_.asString)

  def spec = suite("DB failure → 503 (#310)")(
    test("ErrorMapper returns 503 + JSON + Retry-After + class-only body") {
      val resp = ErrorMapper.dbErrorToResponse(new SQLException(secretMsg))
      for {
        body <- resp.body.asString
      } yield assertTrue(resp.status == Status.ServiceUnavailable) &&
        assertTrue(jsonField(body, "status").contains("error")) &&
        assertTrue(jsonField(body, "db").contains("SQLException")) &&
        assertTrue(
          resp.headers
            .get("Retry-After")
            .contains("30"),
        )
    },
    test("ErrorMapper does not leak SQL details (no table name, no line number)") {
      val resp = ErrorMapper.dbErrorToResponse(new SQLException(secretMsg))
      for {
        body <- resp.body.asString
      } yield assertTrue(!body.contains("secret_users_table")) &&
        assertTrue(!body.contains("line 42")) &&
        assertTrue(!body.contains("relation"))
    },
    test("router endpoint returns 503 + Retry-After when auth step's DB lookup throws") {
      val auth   = failingAuth(new SQLException(secretMsg))
      val routes = RouterIngestRoutes.routes(
        auth,
        brokenRouterRepo,
        brokenTrafficRepo,
        brokenTimeUsageRepo,
        brokenDeviceRepo,
        brokenConnectionEventRepo,
      )
      val req    = Request
        .post(URL.decode("/api/router/usage").toOption.get, Body.fromString("{}"))
        .addHeader(Header.Authorization.Bearer("any"))
      for {
        resp <- routes.runZIO(req)
        body <- resp.body.asString
      } yield assertTrue(resp.status == Status.ServiceUnavailable) &&
        assertTrue(jsonField(body, "status").contains("error")) &&
        assertTrue(jsonField(body, "db").contains("SQLException")) &&
        assertTrue(resp.headers.get("Retry-After").contains("30")) &&
        assertTrue(!body.contains("secret_users_table"))
    },
    test("router endpoint returns 400 (not 503) on malformed body even when repos would throw") {
      // Auth succeeds; body is junk → must short-circuit to 400 before any DB call.
      val auth   = okAuth(UUID.randomUUID())
      val routes = RouterIngestRoutes.routes(
        auth,
        brokenRouterRepo,
        brokenTrafficRepo,
        brokenTimeUsageRepo,
        brokenDeviceRepo,
        brokenConnectionEventRepo,
      )
      val req    = Request
        .post(URL.decode("/api/router/usage").toOption.get, Body.fromString("not json"))
        .addHeader(Header.Authorization.Bearer("any"))
      for {
        resp <- routes.runZIO(req)
      } yield assertTrue(resp.status == Status.BadRequest)
    },
    test("router endpoint returns 401 (not 503) when bearer token missing") {
      // RouterAuthLive checks the bearer header before touching the repo, so missing-auth must 401
      // regardless of repo health.
      val auth   = new RouterAuthLive(brokenRouterRepo)
      val routes = RouterIngestRoutes.routes(
        auth,
        brokenRouterRepo,
        brokenTrafficRepo,
        brokenTimeUsageRepo,
        brokenDeviceRepo,
        brokenConnectionEventRepo,
      )
      val req    = Request.post(URL.decode("/api/router/usage").toOption.get, Body.fromString("{}"))
      for {
        resp <- routes.runZIO(req)
      } yield assertTrue(resp.status == Status.Unauthorized)
    },
  )
}
