package familydns.api.db

import cats.syntax.all.*
import doobie.*
import doobie.implicits.*
import doobie.postgres.implicits.*
import familydns.shared.*
import familydns.shared.Schedule
import zio.*
import zio.interop.catz.*
import java.time.{Instant, LocalDate}
import java.util.UUID

given Meta[List[String]] = Meta[Array[String]].imap(_.toList)(_.toArray)

case class DbUser(
    id: Long,
    username: String,
    passwordHash: String,
    role: String,
    createdAt: Instant,
)
case class LogFilter(
    mac: Option[String] = None,
    blocked: Option[Boolean] = None,
    domain: Option[String] = None,
    location: Option[String] = None,
    hours: Int = 24,
    limit: Int = 200,
    offset: Int = 0,
)

case class SessionFilter(
    macs: Option[List[String]] = None, // None = no MAC restriction; Some(Nil) = match nothing
    host: Option[String] = None,
    since: Option[Instant] = None,
    until: Option[Instant] = None,
)

trait UserRepo {
  def findByUsername(u: String): Task[Option[DbUser]]
  def findById(id: Long): Task[Option[DbUser]]
  def create(u: String, h: String, r: String): Task[Long]
  def updatePassword(id: Long, h: String): Task[Unit]
  def listAll: Task[List[DbUser]]
  def delete(id: Long): Task[Unit]
}

trait UserProfileRepo {
  def listProfilesForUser(userId: Long): Task[List[Long]]
  def listProfilesForUsername(username: String): Task[List[Long]]
  def listAllMappings: Task[List[(Long, Long)]] // (userId, profileId)
  def setProfilesForUser(userId: Long, profileIds: List[Long]): Task[Unit]
  def addLink(userId: Long, profileId: Long): Task[Unit]
  def removeLink(userId: Long, profileId: Long): Task[Unit]
  def hasAccess(userId: Long, profileId: Long): Task[Boolean]
}

trait ProfileRepo {
  def listAll: Task[List[Profile]]
  def findById(id: Long): Task[Option[Profile]]
  def create(name: String, cats: List[String]): Task[Long]
  def update(p: Profile): Task[Unit]
  def delete(id: Long): Task[Unit]
  def setPaused(id: Long, paused: Boolean): Task[Unit]
}

trait ScheduleRepo {
  def listAll: Task[List[Schedule]]
  def listForProfile(pid: Long): Task[List[Schedule]]
  def replaceForProfile(pid: Long, scheds: List[ScheduleRequest]): Task[Unit]
}

trait TimeLimitRepo {
  def findForProfile(pid: Long): Task[Option[TimeLimit]]
  def upsert(pid: Long, mins: Int): Task[Unit]
  def delete(pid: Long): Task[Unit]
  def listAll: Task[List[TimeLimit]]
}

trait SiteTimeLimitRepo {
  def listForProfile(pid: Long): Task[List[SiteTimeLimit]]
  def listAll: Task[List[SiteTimeLimit]]
  def replaceForProfile(pid: Long, limits: List[SiteTimeLimitRequest]): Task[Unit]
}

trait DeviceRepo {
  def listAll: Task[List[Device]]
  def findByMac(mac: String): Task[Option[Device]]
  def upsert(mac: String, name: String, pid: Long, ip: String): Task[Long]
  def updateLastSeen(mac: String, ip: String): Task[Unit]

  /**
   * Update last_seen_ip/at only if the device row exists. Used by router ingest where we don't want
   * to create rows here (events does that).
   */
  def touchLastSeen(mac: String, ip: Option[String], at: Instant): Task[Int]

  /**
   * Insert a row for a previously unknown device with NULL profile_id, or refresh last_seen_ip/at
   * on an existing row. Used by /api/router/events.
   */
  def upsertUnknown(mac: String, name: String, ip: Option[String], at: Instant): Task[Long]

  /**
   * Rename a device only if its current name is an auto-generated placeholder ("unknown" or
   * "device-XXXXXX"). Used by router ingest to upgrade names once a later DHCP lease carries a real
   * hostname (#249). Returns the number of rows updated (0 if the name was admin-curated).
   */
  def renameIfAutoGenerated(mac: String, newName: String): Task[Int]
  def updateProfile(mac: String, pid: Long): Task[Unit]
  def delete(mac: String): Task[Unit]
}

trait BlocklistRepo {
  def insertBatch(domains: List[(String, String)]): Task[Int]
  def clearCategory(cat: String): Task[Unit]
  def listCategories: Task[List[String]]
  def countByCategory: Task[List[(String, Int)]]
  def loadCategory(cat: String): Task[Set[String]]
  def loadAll: Task[Map[String, Set[String]]]
}

trait TimeUsageRepo {

  /**
   * Increment seconds + byte counters for (mac, domain, date). Repeats are *additive* — the caller
   * is responsible for idempotency at the request level (traffic_reports unique key).
   */
  def incrementSecondsAndBytes(
      mac: String,
      domain: String,
      date: LocalDate,
      seconds: Long,
      bytesIn: Long,
      bytesOut: Long,
  ): Task[Unit]

  /** Read seconds_used for a (mac, domain, date) row. Returns 0 if no row. */
  def getSecondsUsed(mac: String, domain: String, date: LocalDate): Task[Long]

  /** Read (seconds_used, bytes_in, bytes_out) for a (mac, domain, date) row. */
  def getSecondsAndBytes(
      mac: String,
      domain: String,
      date: LocalDate,
  ): Task[(Long, Long, Long)]
  def listForDevice(mac: String, date: LocalDate): Task[List[TimeUsage]]
  def listForDeviceMacs(macs: List[String], date: LocalDate): Task[List[TimeUsage]]
  def snapshotAll(date: LocalDate): Task[Map[(String, String), Int]]
}

trait TimeExtensionRepo {
  def getTotalExtension(mac: String, date: LocalDate): Task[Int]
  def grant(mac: String, date: LocalDate, mins: Int, by: String, note: Option[String]): Task[Long]
  def listForDevice(mac: String, date: LocalDate): Task[List[TimeExtension]]
  def snapshotAll(date: LocalDate): Task[Map[String, Int]]
  // Profile-level extension methods (V5+)
  def grantForProfile(
      profileId: Long,
      date: LocalDate,
      mins: Int,
      by: String,
      note: Option[String],
  ): Task[Long]
  def getProfileTotalExtension(profileId: Long, date: LocalDate): Task[Int]
  def listForProfile(profileId: Long, date: LocalDate): Task[List[TimeExtension]]
  def snapshotAllByProfile(date: LocalDate): Task[Map[Long, Int]]
}

case class TrafficReportInsert(
    routerId: UUID,
    mac: String,
    ip: Option[String],
    hostname: String,
    date: LocalDate,
    periodStart: Instant,
    periodEnd: Instant,
    activeSeconds: Int,
    bytesIn: Long,
    bytesOut: Long,
)

case class BlockEventInsert(
    mac: Option[String],
    hostname: String,
    reason: String,
)

case class ConnectionEventInsert(
    routerId: UUID,
    mac: Option[String],
    hostname: String,
    destIp: Option[String],
    allowed: Boolean,
    reason: String,
    ts: Instant,
)

trait RouterRepo {
  def listAll: Task[List[Router]]
  def findById(id: UUID): Task[Option[Router]]
  def findByEnrollmentTokenHash(h: String): Task[Option[Router]]
  def findByTokenHash(h: String): Task[Option[Router]]
  def create(name: String, enrollmentTokenHash: String): Task[UUID]
  def completeEnrollment(id: UUID, tokenHash: String): Task[Unit]
  def touch(id: UUID, etag: Option[String]): Task[Unit]
  def delete(id: UUID): Task[Unit]
}

trait TrafficReportRepo {
  def insertBatch(reports: List[TrafficReportInsert]): Task[Int]
  def listForDevice(mac: String, date: LocalDate): Task[List[TrafficReport]]
  def listForRouter(routerId: UUID, limit: Int): Task[List[TrafficReport]]

  /**
   * Rows fit for session stitching: returned ordered by (router_id, mac, hostname, date,
   * period_start) so the caller can fold contiguous runs directly. Filters are AND-composed. `macs
   * \= Some(Nil)` returns an empty list (no devices match).
   */
  def listSessionRows(f: SessionFilter): Task[List[familydns.api.sessions.SessionRow]]
}

trait BlockEventRepo {
  def insertBatch(events: List[BlockEventInsert]): Task[Int]
  def recent(limit: Int): Task[List[BlockEvent]]
  def listForMac(mac: String, limit: Int): Task[List[BlockEvent]]
}

trait ConnectionEventRepo {
  def insertBatch(events: List[ConnectionEventInsert]): Task[Int]
  def recent(limit: Int): Task[List[ConnectionEvent]]
  def listForMac(mac: String, limit: Int): Task[List[ConnectionEvent]]
  def listForRouter(routerId: UUID, limit: Int): Task[List[ConnectionEvent]]
  def query(f: LogFilter): Task[List[QueryLog]]
  def stats: Task[DashboardStats]
  def topBlocked(hours: Int, limit: Int): Task[List[DomainCount]]
}

class UserRepoLive(xa: Transactor[Task]) extends UserRepo {
  def findByUsername(u: String)               =
    sql"SELECT id,username,password_hash,role,created_at FROM users WHERE username=$u"
      .query[(Long, String, String, String, Instant)]
      .map(DbUser.apply)
      .option
      .transact(xa)
  def findById(id: Long)                      =
    sql"SELECT id,username,password_hash,role,created_at FROM users WHERE id=$id"
      .query[(Long, String, String, String, Instant)]
      .map(DbUser.apply)
      .option
      .transact(xa)
  def create(u: String, h: String, r: String) =
    sql"INSERT INTO users(username,password_hash,role) VALUES($u,$h,$r) RETURNING id"
      .query[Long]
      .unique
      .transact(xa)
  def updatePassword(id: Long, h: String)     =
    sql"UPDATE users SET password_hash=$h WHERE id=$id".update.run.transact(xa).unit
  def listAll = sql"SELECT id,username,password_hash,role,created_at FROM users ORDER BY id"
    .query[(Long, String, String, String, Instant)]
    .map(DbUser.apply)
    .to[List]
    .transact(xa)
  def delete(id: Long) = sql"DELETE FROM users WHERE id=$id".update.run.transact(xa).unit
}

class UserProfileRepoLive(xa: Transactor[Task]) extends UserProfileRepo {
  def listProfilesForUser(userId: Long)                  =
    sql"SELECT profile_id FROM user_profiles WHERE user_id=$userId ORDER BY profile_id"
      .query[Long]
      .to[List]
      .transact(xa)
  def listProfilesForUsername(u: String)                 =
    sql"SELECT up.profile_id FROM user_profiles up JOIN users us ON us.id=up.user_id WHERE us.username=$u ORDER BY up.profile_id"
      .query[Long]
      .to[List]
      .transact(xa)
  def listAllMappings                                    =
    sql"SELECT user_id, profile_id FROM user_profiles"
      .query[(Long, Long)]
      .to[List]
      .transact(xa)
  def setProfilesForUser(userId: Long, pids: List[Long]) = {
    val del = sql"DELETE FROM user_profiles WHERE user_id=$userId".update.run
    val ins = pids.distinct.map(pid =>
      sql"INSERT INTO user_profiles(user_id,profile_id) VALUES($userId,$pid) ON CONFLICT DO NOTHING".update.run,
    )
    (del *> ins.foldLeft(FC.unit)(_ *> _.void)).transact(xa)
  }
  def addLink(userId: Long, pid: Long)                   =
    sql"INSERT INTO user_profiles(user_id,profile_id) VALUES($userId,$pid) ON CONFLICT DO NOTHING".update.run
      .transact(xa)
      .unit
  def removeLink(userId: Long, pid: Long)                =
    sql"DELETE FROM user_profiles WHERE user_id=$userId AND profile_id=$pid".update.run
      .transact(xa)
      .unit
  def hasAccess(userId: Long, pid: Long)                 =
    sql"SELECT 1 FROM user_profiles WHERE user_id=$userId AND profile_id=$pid"
      .query[Int]
      .option
      .transact(xa)
      .map(_.isDefined)
}

class ProfileRepoLive(xa: Transactor[Task]) extends ProfileRepo {
  private type R = (Long, String, List[String], List[String], List[String], Boolean)
  private def toP(r: R)                        = Profile(r._1, r._2, r._3, r._4, r._5, r._6)
  def listAll                                  =
    sql"SELECT id,name,blocked_categories,extra_blocked,extra_allowed,paused FROM profiles ORDER BY id"
      .query[R]
      .map(toP)
      .to[List]
      .transact(xa)
  def findById(id: Long)                       =
    sql"SELECT id,name,blocked_categories,extra_blocked,extra_allowed,paused FROM profiles WHERE id=$id"
      .query[R]
      .map(toP)
      .option
      .transact(xa)
  def create(name: String, cats: List[String]) =
    sql"INSERT INTO profiles(name,blocked_categories) VALUES($name,${cats.toArray}) RETURNING id"
      .query[Long]
      .unique
      .transact(xa)
  def update(p: Profile)                       =
    sql"UPDATE profiles SET name=${p.name},blocked_categories=${p.blockedCategories.toArray},extra_blocked=${p.extraBlocked.toArray},extra_allowed=${p.extraAllowed.toArray},paused=${p.paused} WHERE id=${p.id}".update.run
      .transact(xa)
      .unit
  def delete(id: Long) = sql"DELETE FROM profiles WHERE id=$id".update.run.transact(xa).unit
  def setPaused(id: Long, p: Boolean) =
    sql"UPDATE profiles SET paused=$p WHERE id=$id".update.run.transact(xa).unit
}

class ScheduleRepoLive(xa: Transactor[Task]) extends ScheduleRepo {
  private type R = (Long, Long, String, List[String], String, String)
  private def toS(r: R)         = Schedule(r._1, r._2, r._3, r._4, r._5, r._6)
  def listAll                   =
    sql"SELECT id,profile_id,name,days,block_from,block_until FROM schedules ORDER BY id"
      .query[R]
      .map(toS)
      .to[List]
      .transact(xa)
  def listForProfile(pid: Long) =
    sql"SELECT id,profile_id,name,days,block_from,block_until FROM schedules WHERE profile_id=$pid ORDER BY id"
      .query[R]
      .map(toS)
      .to[List]
      .transact(xa)
  def replaceForProfile(pid: Long, ss: List[ScheduleRequest]) = {
    val del = sql"DELETE FROM schedules WHERE profile_id=$pid".update.run
    val ins = ss.map(s =>
      sql"INSERT INTO schedules(profile_id,name,days,block_from,block_until) VALUES($pid,${s.name},${s.days.toArray},${s.blockFrom},${s.blockUntil})".update.run,
    )
    (del *> ins.foldLeft(FC.unit)(_ *> _.void)).transact(xa)
  }
}

class TimeLimitRepoLive(xa: Transactor[Task]) extends TimeLimitRepo {
  def findForProfile(pid: Long)    =
    sql"SELECT id,profile_id,daily_minutes FROM time_limits WHERE profile_id=$pid"
      .query[(Long, Long, Int)]
      .map(TimeLimit.apply)
      .option
      .transact(xa)
  def upsert(pid: Long, mins: Int) =
    sql"INSERT INTO time_limits(profile_id,daily_minutes) VALUES($pid,$mins) ON CONFLICT(profile_id) DO UPDATE SET daily_minutes=EXCLUDED.daily_minutes".update.run
      .transact(xa)
      .unit
  def delete(pid: Long)            =
    sql"DELETE FROM time_limits WHERE profile_id=$pid".update.run.transact(xa).unit
  def listAll                      = sql"SELECT id,profile_id,daily_minutes FROM time_limits"
    .query[(Long, Long, Int)]
    .map(TimeLimit.apply)
    .to[List]
    .transact(xa)
}

class SiteTimeLimitRepoLive(xa: Transactor[Task]) extends SiteTimeLimitRepo {
  private type R = (Long, Long, String, Int, String, Boolean)
  private def toS(r: R)         = SiteTimeLimit(r._1, r._2, r._3, r._4, r._5, r._6)
  def listForProfile(pid: Long) =
    sql"SELECT id,profile_id,domain_pattern,daily_minutes,label,exempt_from_daily FROM site_time_limits WHERE profile_id=$pid ORDER BY id"
      .query[R]
      .map(toS)
      .to[List]
      .transact(xa)
  def listAll                   =
    sql"SELECT id,profile_id,domain_pattern,daily_minutes,label,exempt_from_daily FROM site_time_limits ORDER BY id"
      .query[R]
      .map(toS)
      .to[List]
      .transact(xa)
  def replaceForProfile(pid: Long, ls: List[SiteTimeLimitRequest]) = {
    val del = sql"DELETE FROM site_time_limits WHERE profile_id=$pid".update.run
    val ins = ls.map(l =>
      sql"INSERT INTO site_time_limits(profile_id,domain_pattern,daily_minutes,label,exempt_from_daily) VALUES($pid,${l.domainPattern},${l.dailyMinutes},${l.label},${l.exemptFromDaily})".update.run,
    )
    (del *> ins.foldLeft(FC.unit)(_ *> _.void)).transact(xa)
  }
}

class DeviceRepoLive(xa: Transactor[Task]) extends DeviceRepo {
  def listAll                                                                   =
    sql"SELECT d.id,d.mac,d.name,d.profile_id,p.name,d.last_seen_ip,d.last_seen_at::TEXT FROM devices d LEFT JOIN profiles p ON p.id=d.profile_id ORDER BY d.name"
      .query[
        (
            Long,
            String,
            String,
            Option[Long],
            Option[String],
            Option[String],
            Option[String],
        ),
      ]
      .map(r => Device(r._1, r._2, r._3, r._4, r._5, r._6, r._7))
      .to[List]
      .transact(xa)
  def findByMac(mac: String)                                                    =
    sql"SELECT d.id,d.mac,d.name,d.profile_id,p.name,d.last_seen_ip,d.last_seen_at::TEXT FROM devices d LEFT JOIN profiles p ON p.id=d.profile_id WHERE d.mac=$mac"
      .query[
        (
            Long,
            String,
            String,
            Option[Long],
            Option[String],
            Option[String],
            Option[String],
        ),
      ]
      .map(r => Device(r._1, r._2, r._3, r._4, r._5, r._6, r._7))
      .option
      .transact(xa)
  def upsert(mac: String, name: String, pid: Long, ip: String)                  =
    sql"INSERT INTO devices(mac,name,profile_id,last_seen_ip,last_seen_at) VALUES($mac,$name,$pid,NULLIF($ip,''),NOW()) ON CONFLICT(mac) DO UPDATE SET name=EXCLUDED.name,profile_id=EXCLUDED.profile_id RETURNING id"
      .query[Long]
      .unique
      .transact(xa)
  def updateLastSeen(mac: String, ip: String)                                   =
    sql"UPDATE devices SET last_seen_ip=$ip,last_seen_at=NOW() WHERE mac=$mac".update.run
      .transact(xa)
      .unit
  def touchLastSeen(mac: String, ip: Option[String], at: Instant)               =
    sql"UPDATE devices SET last_seen_ip=COALESCE($ip,last_seen_ip),last_seen_at=$at WHERE mac=$mac".update.run
      .transact(xa)
  def upsertUnknown(mac: String, name: String, ip: Option[String], at: Instant) =
    sql"""INSERT INTO devices(mac,name,profile_id,last_seen_ip,last_seen_at)
          VALUES($mac,$name,NULL,$ip,$at)
          ON CONFLICT(mac) DO UPDATE
          SET last_seen_ip=COALESCE(EXCLUDED.last_seen_ip,devices.last_seen_ip),
              last_seen_at=EXCLUDED.last_seen_at
          RETURNING id"""
      .query[Long]
      .unique
      .transact(xa)
  def renameIfAutoGenerated(mac: String, newName: String)                       = {
    val autoNamePattern = "^device-[0-9a-fA-F]+$"
    sql"""UPDATE devices SET name=$newName
          WHERE mac=$mac AND (name='unknown' OR name ~ $autoNamePattern)""".update.run
      .transact(xa)
  }
  def updateProfile(mac: String, pid: Long)                                     =
    sql"UPDATE devices SET profile_id=$pid WHERE mac=$mac".update.run.transact(xa).unit
  def delete(mac: String) = sql"DELETE FROM devices WHERE mac=$mac".update.run.transact(xa).unit
}

class BlocklistRepoLive(xa: Transactor[Task]) extends BlocklistRepo {
  def insertBatch(ds: List[(String, String)]) = Update[(String, String)](
    "INSERT INTO blocklist_domains(domain,category) VALUES(?,?) ON CONFLICT DO NOTHING",
  ).updateMany(ds).transact(xa)
  def clearCategory(cat: String)              =
    sql"DELETE FROM blocklist_domains WHERE category=$cat".update.run.transact(xa).unit
  def listCategories  = sql"SELECT DISTINCT category FROM blocklist_domains ORDER BY category"
    .query[String]
    .to[List]
    .transact(xa)
  def countByCategory =
    sql"SELECT category,COUNT(*)::INT FROM blocklist_domains GROUP BY category ORDER BY category"
      .query[(String, Int)]
      .to[List]
      .transact(xa)
  def loadCategory(cat: String) = sql"SELECT domain FROM blocklist_domains WHERE category=$cat"
    .query[String]
    .to[List]
    .transact(xa)
    .map(_.toSet)
  def loadAll                   = sql"SELECT category,domain FROM blocklist_domains"
    .query[(String, String)]
    .to[List]
    .transact(xa)
    .map(_.groupBy(_._1).map((k, vs) => k -> vs.map(_._2).toSet))
}

class TimeUsageRepoLive(xa: Transactor[Task]) extends TimeUsageRepo {
  def incrementSecondsAndBytes(
      mac: String,
      dom: String,
      d: LocalDate,
      seconds: Long,
      bytesIn: Long,
      bytesOut: Long,
  ): Task[Unit] =
    sql"""INSERT INTO time_usage(device_mac,domain,date,seconds_used,bytes_in,bytes_out,last_seen_at)
          VALUES($mac,$dom,$d,$seconds,$bytesIn,$bytesOut,NOW())
          ON CONFLICT(device_mac,domain,date) DO UPDATE
          SET seconds_used=time_usage.seconds_used+EXCLUDED.seconds_used,
              bytes_in=time_usage.bytes_in+EXCLUDED.bytes_in,
              bytes_out=time_usage.bytes_out+EXCLUDED.bytes_out,
              last_seen_at=NOW()""".update.run
      .transact(xa)
      .unit
  def getSecondsUsed(mac: String, dom: String, d: LocalDate): Task[Long]                   =
    sql"SELECT COALESCE(seconds_used,0) FROM time_usage WHERE device_mac=$mac AND domain=$dom AND date=$d"
      .query[Long]
      .option
      .transact(xa)
      .map(_.getOrElse(0L))
  def getSecondsAndBytes(mac: String, dom: String, d: LocalDate): Task[(Long, Long, Long)] =
    sql"SELECT COALESCE(seconds_used,0),COALESCE(bytes_in,0),COALESCE(bytes_out,0) FROM time_usage WHERE device_mac=$mac AND domain=$dom AND date=$d"
      .query[(Long, Long, Long)]
      .option
      .transact(xa)
      .map(_.getOrElse((0L, 0L, 0L)))
  def listForDevice(mac: String, d: LocalDate)                                             =
    sql"SELECT id,device_mac,domain,date::TEXT,(COALESCE(seconds_used,0)/60)::INT,last_seen_at::TEXT FROM time_usage WHERE device_mac=$mac AND date=$d ORDER BY seconds_used DESC"
      .query[(Long, String, String, String, Int, String)]
      .map(TimeUsage.apply)
      .to[List]
      .transact(xa)
  def listForDeviceMacs(macs: List[String], d: LocalDate)                                  =
    if macs.isEmpty then ZIO.succeed(Nil)
    else {
      val arr = macs.toArray
      sql"SELECT id,device_mac,domain,date::TEXT,(COALESCE(seconds_used,0)/60)::INT,last_seen_at::TEXT FROM time_usage WHERE device_mac = ANY($arr) AND date=$d ORDER BY device_mac,seconds_used DESC"
        .query[(Long, String, String, String, Int, String)]
        .map(TimeUsage.apply)
        .to[List]
        .transact(xa)
    }
  def snapshotAll(d: LocalDate)                                                            =
    sql"SELECT device_mac,domain,(COALESCE(seconds_used,0)/60)::INT FROM time_usage WHERE date=$d"
      .query[(String, String, Int)]
      .to[List]
      .transact(xa)
      .map(_.map((m, dom, mins) => (m, dom) -> mins).toMap)
}

class TimeExtensionRepoLive(xa: Transactor[Task]) extends TimeExtensionRepo {
  def getTotalExtension(mac: String, d: LocalDate)                                          =
    sql"SELECT COALESCE(SUM(extra_minutes),0)::INT FROM time_extensions WHERE device_mac=$mac AND date=$d"
      .query[Int]
      .unique
      .transact(xa)
  def grant(mac: String, d: LocalDate, mins: Int, by: String, note: Option[String])         =
    sql"INSERT INTO time_extensions(device_mac,date,extra_minutes,granted_by,note) VALUES($mac,$d,$mins,$by,$note) RETURNING id"
      .query[Long]
      .unique
      .transact(xa)
  def listForDevice(mac: String, d: LocalDate)                                              =
    sql"SELECT id,profile_id,device_mac,date::TEXT,extra_minutes,granted_by,note,created_at::TEXT FROM time_extensions WHERE device_mac=$mac AND date=$d ORDER BY created_at"
      .query[(Long, Option[Long], Option[String], String, Int, String, Option[String], String)]
      .map(TimeExtension.apply)
      .to[List]
      .transact(xa)
  def snapshotAll(d: LocalDate)                                                             =
    sql"SELECT device_mac,SUM(extra_minutes)::INT FROM time_extensions WHERE date=$d AND device_mac IS NOT NULL GROUP BY device_mac"
      .query[(String, Int)]
      .to[List]
      .transact(xa)
      .map(_.toMap)
  def grantForProfile(pid: Long, d: LocalDate, mins: Int, by: String, note: Option[String]) =
    sql"INSERT INTO time_extensions(profile_id,date,extra_minutes,granted_by,note) VALUES($pid,$d,$mins,$by,$note) RETURNING id"
      .query[Long]
      .unique
      .transact(xa)
  def getProfileTotalExtension(pid: Long, d: LocalDate)                                     =
    sql"SELECT COALESCE(SUM(extra_minutes),0)::INT FROM time_extensions WHERE profile_id=$pid AND date=$d"
      .query[Int]
      .unique
      .transact(xa)
  def listForProfile(pid: Long, d: LocalDate)                                               =
    sql"SELECT id,profile_id,device_mac,date::TEXT,extra_minutes,granted_by,note,created_at::TEXT FROM time_extensions WHERE profile_id=$pid AND date=$d ORDER BY created_at"
      .query[(Long, Option[Long], Option[String], String, Int, String, Option[String], String)]
      .map(TimeExtension.apply)
      .to[List]
      .transact(xa)
  def snapshotAllByProfile(d: LocalDate)                                                    =
    sql"SELECT profile_id,SUM(extra_minutes)::INT FROM time_extensions WHERE date=$d AND profile_id IS NOT NULL GROUP BY profile_id"
      .query[(Long, Int)]
      .to[List]
      .transact(xa)
      .map(_.toMap)
}

class RouterRepoLive(xa: Transactor[Task]) extends RouterRepo {
  private type R =
    (UUID, String, Option[String], Option[String], Option[Instant], Option[String], Instant)
  private def toR(r: R)                                 =
    Router(
      r._1,
      r._2,
      r._3,
      r._4,
      r._5.map(_.toString),
      r._6,
      r._7.toString,
    )
  def listAll                                           =
    sql"SELECT id,name,enrollment_token_hash,token_hash,last_seen_at,last_etag,created_at FROM routers ORDER BY created_at"
      .query[R]
      .map(toR)
      .to[List]
      .transact(xa)
  def findById(id: UUID)                                =
    sql"SELECT id,name,enrollment_token_hash,token_hash,last_seen_at,last_etag,created_at FROM routers WHERE id=$id"
      .query[R]
      .map(toR)
      .option
      .transact(xa)
  def findByEnrollmentTokenHash(h: String)              =
    sql"SELECT id,name,enrollment_token_hash,token_hash,last_seen_at,last_etag,created_at FROM routers WHERE enrollment_token_hash=$h"
      .query[R]
      .map(toR)
      .option
      .transact(xa)
  def findByTokenHash(h: String)                        =
    sql"SELECT id,name,enrollment_token_hash,token_hash,last_seen_at,last_etag,created_at FROM routers WHERE token_hash=$h"
      .query[R]
      .map(toR)
      .option
      .transact(xa)
  def create(name: String, enrollmentTokenHash: String) =
    sql"INSERT INTO routers(name,enrollment_token_hash) VALUES($name,$enrollmentTokenHash) RETURNING id"
      .query[UUID]
      .unique
      .transact(xa)
  def completeEnrollment(id: UUID, tokenHash: String)   =
    sql"UPDATE routers SET token_hash=$tokenHash, enrollment_token_hash=NULL, last_seen_at=NOW() WHERE id=$id".update.run
      .transact(xa)
      .unit
  def touch(id: UUID, etag: Option[String])             =
    sql"UPDATE routers SET last_seen_at=NOW(), last_etag=COALESCE($etag,last_etag) WHERE id=$id".update.run
      .transact(xa)
      .unit
  def delete(id: UUID)                                  =
    sql"DELETE FROM routers WHERE id=$id".update.run.transact(xa).unit
}

class TrafficReportRepoLive(xa: Transactor[Task]) extends TrafficReportRepo {
  private type R =
    (Long, UUID, String, Option[String], String, String, String, String, Int, Long, Long)
  private def toT(r: R)                               =
    TrafficReport(r._1, r._2, r._3, r._4, r._5, r._6, r._7, r._8, r._9, r._10, r._11)
  def insertBatch(reports: List[TrafficReportInsert]) =
    Update[TrafficReportInsert](
      "INSERT INTO traffic_reports(router_id,mac,ip,hostname,date,period_start,period_end,active_seconds,bytes_in,bytes_out) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(router_id,period_start,mac,hostname) DO NOTHING",
    ).updateMany(reports).transact(xa)
  def listForDevice(mac: String, date: LocalDate)     =
    sql"SELECT id,router_id,mac,ip,hostname,date::TEXT,period_start::TEXT,period_end::TEXT,active_seconds,bytes_in,bytes_out FROM traffic_reports WHERE mac=$mac AND date=$date ORDER BY period_start"
      .query[R]
      .map(toT)
      .to[List]
      .transact(xa)
  def listForRouter(routerId: UUID, limit: Int)       =
    sql"SELECT id,router_id,mac,ip,hostname,date::TEXT,period_start::TEXT,period_end::TEXT,active_seconds,bytes_in,bytes_out FROM traffic_reports WHERE router_id=$routerId ORDER BY period_start DESC LIMIT $limit"
      .query[R]
      .map(toT)
      .to[List]
      .transact(xa)

  def listSessionRows(f: SessionFilter) = {
    type Row = (UUID, String, String, LocalDate, Instant, Instant, Int, Long, Long)
    val base    = fr"""SELECT router_id, mac, hostname, date, period_start, period_end,
                              active_seconds, bytes_in, bytes_out
                       FROM traffic_reports
                       WHERE 1=1"""
    val byMacs  = f.macs match {
      case None      => fr""
      case Some(Nil) => fr"AND FALSE"
      case Some(ms)  =>
        val nel = cats.data.NonEmptyList.fromListUnsafe(ms)
        fr"AND " ++ Fragments.in(fr"mac", nel)
    }
    val byHost  = f.host.fold(fr"")(h => fr"AND hostname ILIKE ${s"%$h%"}")
    val bySince = f.since.fold(fr"")(s => fr"AND period_end > $s")
    val byUntil = f.until.fold(fr"")(u => fr"AND period_start < $u")
    val sql_    = base ++ byMacs ++ byHost ++ bySince ++ byUntil ++
      fr"ORDER BY router_id, mac, hostname, date, period_start"
    sql_
      .query[Row]
      .map { r =>
        familydns.api.sessions.SessionRow(
          routerId = r._1,
          mac = r._2,
          hostname = r._3,
          date = r._4,
          periodStart = r._5,
          periodEnd = r._6,
          activeSeconds = r._7,
          bytesIn = r._8,
          bytesOut = r._9,
        )
      }
      .to[List]
      .transact(xa)
  }
}

class BlockEventRepoLive(xa: Transactor[Task]) extends BlockEventRepo {
  private type R = (Long, Option[String], String, String, String)
  private def toB(r: R)                           = BlockEvent(r._1, r._2, r._3, r._4, r._5)
  def insertBatch(events: List[BlockEventInsert]) =
    Update[BlockEventInsert](
      "INSERT INTO block_events(mac,hostname,reason) VALUES(?,?,?)",
    ).updateMany(events).transact(xa)
  def recent(limit: Int)                          =
    sql"SELECT id,mac,hostname,reason,ts::TEXT FROM block_events ORDER BY ts DESC LIMIT $limit"
      .query[R]
      .map(toB)
      .to[List]
      .transact(xa)
  def listForMac(mac: String, limit: Int)         =
    sql"SELECT id,mac,hostname,reason,ts::TEXT FROM block_events WHERE mac=$mac ORDER BY ts DESC LIMIT $limit"
      .query[R]
      .map(toB)
      .to[List]
      .transact(xa)
}

class ConnectionEventRepoLive(xa: Transactor[Task]) extends ConnectionEventRepo {
  private type R =
    (Long, UUID, Option[String], String, Option[String], Boolean, String, String)
  private def toC(r: R) =
    ConnectionEvent(r._1, r._2, r._3, r._4, r._5, r._6, r._7, r._8)

  def insertBatch(events: List[ConnectionEventInsert]) =
    Update[ConnectionEventInsert](
      "INSERT INTO connection_events(router_id,mac,hostname,dest_ip,allowed,reason,ts) VALUES(?,?,?,?,?,?,?)",
    ).updateMany(events).transact(xa)

  def recent(limit: Int) =
    sql"SELECT id,router_id,mac,hostname,dest_ip,allowed,reason,ts::TEXT FROM connection_events ORDER BY ts DESC LIMIT $limit"
      .query[R]
      .map(toC)
      .to[List]
      .transact(xa)

  def listForMac(mac: String, limit: Int) =
    sql"SELECT id,router_id,mac,hostname,dest_ip,allowed,reason,ts::TEXT FROM connection_events WHERE mac=$mac ORDER BY ts DESC LIMIT $limit"
      .query[R]
      .map(toC)
      .to[List]
      .transact(xa)

  def listForRouter(routerId: UUID, limit: Int) =
    sql"SELECT id,router_id,mac,hostname,dest_ip,allowed,reason,ts::TEXT FROM connection_events WHERE router_id=$routerId ORDER BY ts DESC LIMIT $limit"
      .query[R]
      .map(toC)
      .to[List]
      .transact(xa)

  // ── Dashboard / log API ──────────────────────────────────────────────────

  def query(f: LogFilter) = {
    // location is sourced from routers.name until routers.location lands (#136)
    val base  =
      fr"""SELECT ce.id, ce.mac, d.name, d.profile_id, p.name,
                  ce.hostname, 1, NOT ce.allowed, ce.reason, r.name, ce.ts::TEXT
           FROM connection_events ce
           LEFT JOIN devices d  ON d.mac    = ce.mac
           LEFT JOIN profiles p ON p.id     = d.profile_id
           LEFT JOIN routers r  ON r.id     = ce.router_id
           WHERE 1=1"""
    val since = fr"AND ce.ts > NOW() - make_interval(hours => ${f.hours})"
    val byMac = f.mac.fold(fr"")(m => fr"AND ce.mac = $m")
    val byBl  = f.blocked.fold(fr"")(b => fr"AND ce.allowed = ${!b}")
    val byDom = f.domain.fold(fr"")(d => fr"AND ce.hostname ILIKE ${s"%$d%"}")
    val byLoc = f.location.fold(fr"")(l => fr"AND r.name = $l")
    (base ++ since ++ byMac ++ byBl ++ byDom ++ byLoc ++
      fr"ORDER BY ce.ts DESC LIMIT ${f.limit} OFFSET ${f.offset}")
      .query[
        (
            Long,
            Option[String],
            Option[String],
            Option[Long],
            Option[String],
            String,
            Int,
            Boolean,
            String,
            Option[String],
            String,
        ),
      ]
      .map(QueryLog.apply)
      .to[List]
      .transact(xa)
  }

  def stats =
    for {
      tt  <- sql"SELECT COUNT(*)::INT FROM connection_events WHERE ts > NOW()-INTERVAL '24 hours'"
        .query[Int]
        .unique
        .transact(xa)
      bt  <-
        sql"SELECT COUNT(*)::INT FROM connection_events WHERE ts > NOW()-INTERVAL '24 hours' AND NOT allowed"
          .query[Int]
          .unique
          .transact(xa)
      th  <- sql"SELECT COUNT(*)::INT FROM connection_events WHERE ts > NOW()-INTERVAL '1 hour'"
        .query[Int]
        .unique
        .transact(xa)
      bh  <-
        sql"SELECT COUNT(*)::INT FROM connection_events WHERE ts > NOW()-INTERVAL '1 hour' AND NOT allowed"
          .query[Int]
          .unique
          .transact(xa)
      top <- sql"""SELECT hostname, COUNT(*)::INT
                   FROM connection_events
                   WHERE NOT allowed AND ts > NOW()-INTERVAL '24 hours'
                   GROUP BY hostname ORDER BY COUNT(*) DESC LIMIT 10"""
        .query[(String, Int)]
        .map(DomainCount.apply)
        .to[List]
        .transact(xa)
      dev <- sql"""SELECT COALESCE(ce.mac,'unknown'),
                          COALESCE(d.name, ce.mac, 'unknown'),
                          COUNT(*)::INT,
                          SUM(CASE WHEN NOT ce.allowed THEN 1 ELSE 0 END)::INT
                   FROM connection_events ce
                   LEFT JOIN devices d ON d.mac = ce.mac
                   WHERE ce.ts > NOW()-INTERVAL '24 hours'
                   GROUP BY ce.mac, d.name
                   ORDER BY COUNT(*) DESC LIMIT 20"""
        .query[(String, String, Int, Int)]
        .map(DeviceStats.apply)
        .to[List]
        .transact(xa)
    } yield DashboardStats(tt, bt, th, bh, top, dev)

  def topBlocked(hours: Int, lim: Int) =
    sql"""SELECT hostname, COUNT(*)::INT
          FROM connection_events
          WHERE NOT allowed AND ts > NOW() - make_interval(hours => $hours)
          GROUP BY hostname ORDER BY COUNT(*) DESC LIMIT $lim"""
      .query[(String, Int)]
      .map(DomainCount.apply)
      .to[List]
      .transact(xa)
}

object Repos {
  val userRepo          = ZLayer.fromFunction(UserRepoLive(_))
  val userProfileRepo   = ZLayer.fromFunction(UserProfileRepoLive(_))
  val profileRepo       = ZLayer.fromFunction(ProfileRepoLive(_))
  val scheduleRepo      = ZLayer.fromFunction(ScheduleRepoLive(_))
  val timeLimitRepo     = ZLayer.fromFunction(TimeLimitRepoLive(_))
  val siteTimeLimitRepo = ZLayer.fromFunction(SiteTimeLimitRepoLive(_))
  val deviceRepo        = ZLayer.fromFunction(DeviceRepoLive(_))
  val blocklistRepo     = ZLayer.fromFunction(BlocklistRepoLive(_))
  val timeUsageRepo     = ZLayer.fromFunction(TimeUsageRepoLive(_))
  val timeExtRepo       = ZLayer.fromFunction(TimeExtensionRepoLive(_))
  val routerRepo        = ZLayer.fromFunction(RouterRepoLive(_))
  val trafficReportRepo = ZLayer.fromFunction(TrafficReportRepoLive(_))
  val blockEventRepo    = ZLayer.fromFunction(BlockEventRepoLive(_))
  val connEventRepo     = ZLayer.fromFunction(ConnectionEventRepoLive(_))
  val all               =
    userRepo ++ userProfileRepo ++ profileRepo ++ scheduleRepo ++ timeLimitRepo ++ siteTimeLimitRepo ++ deviceRepo ++ blocklistRepo ++ timeUsageRepo ++ timeExtRepo ++ routerRepo ++ trafficReportRepo ++ blockEventRepo ++ connEventRepo
}
