package wifihaven.api.db

import cats.syntax.all.*
import doobie.*
import doobie.implicits.*
import doobie.postgres.implicits.*
import wifihaven.shared.*
import wifihaven.shared.types.*
import wifihaven.shared.Schedule
import wifihaven.api.db.TypeMeta.given
import zio.*
import zio.interop.catz.*
import java.time.{Instant, LocalDate, LocalTime, ZoneId}

given Meta[List[String]] = Meta[Array[String]].imap(_.toList)(_.toArray)

case class DbUser(
    id: UserId,
    username: String,
    passwordHash: String,
    role: UserRole,
    createdAt: Instant,
    mustChangePassword: Boolean = false,
)
case class LogFilter(
    mac: Option[String] = None,
    deviceId: Option[DeviceId] = None,
    profileId: Option[ProfileId] = None,
    blocked: Option[Boolean] = None,
    domain: Option[String] = None,
    location: Option[String] = None,
    hours: Int = 24,
    limit: Int = 200,
    offset: Int = 0,
)

case class TrafficRollupFilter(
    macs: Option[List[MacAddress]] = None, // None = no MAC restriction; Some(Nil) = match nothing
    host: Option[String] = None,
    since: Option[Instant] = None,
    until: Option[Instant] = None,
)

/**
 * One row per 5-min traffic_reports period (with ipv4/ipv6 hosts resolved to their attributed FQDN
 * when possible). Used by [[DashboardNowRoutes]] to compute per-device top hosts.
 */
case class TrafficRollupRow(
    routerId: RouterId,
    mac: MacAddress,
    host: HostId,
    date: LocalDate,
    periodStart: Instant,
    periodEnd: Instant,
    activeSeconds: Int,
    bytesIn: Long,
    bytesOut: Long,
)

trait UserRepo {
  def findByUsername(u: String): Task[Option[DbUser]]
  def findById(id: UserId): Task[Option[DbUser]]
  def create(u: String, h: String, r: String): Task[UserId]
  def updatePassword(id: UserId, h: String): Task[Unit]
  def clearMustChangePassword(id: UserId): Task[Unit]
  def listAll: Task[List[DbUser]]
  def delete(id: UserId): Task[Unit]
}

trait UserProfileRepo {
  def listProfilesForUser(userId: UserId): Task[List[ProfileId]]
  def listProfilesForUsername(username: String): Task[List[ProfileId]]
  def listUsersForProfile(profileId: ProfileId): Task[List[UserId]]
  def listAllMappings: Task[List[(UserId, ProfileId)]] // (userId, profileId)
  def setProfilesForUser(userId: UserId, profileIds: List[ProfileId]): Task[Unit]
  def setUsersForProfile(profileId: ProfileId, userIds: List[UserId]): Task[Unit]
  def addLink(userId: UserId, profileId: ProfileId): Task[Unit]
  def removeLink(userId: UserId, profileId: ProfileId): Task[Unit]
  def hasAccess(userId: UserId, profileId: ProfileId): Task[Boolean]
}

trait ProfileRepo {
  def listAll: Task[List[Profile]]
  def findById(id: ProfileId): Task[Option[Profile]]
  def create(name: String, cats: List[BlocklistId]): Task[ProfileId]
  def update(p: Profile): Task[Unit]
  def delete(id: ProfileId): Task[Unit]
  def setPaused(id: ProfileId, paused: Boolean): Task[Unit]
}

trait ScheduleRepo {
  def listAll: Task[List[Schedule]]
  def listForProfile(pid: ProfileId): Task[List[Schedule]]
  def replaceForProfile(pid: ProfileId, scheds: List[ScheduleRequest]): Task[Unit]
}

trait HouseholdSettingsRepo {
  def get: Task[HouseholdSettings]
  def update(s: HouseholdSettings): Task[Unit]

  /** Insert the default row if missing, using `defaultZone` as the install-time tz. */
  def ensureDefault(defaultZone: ZoneId): Task[Unit]
}

trait TimeLimitRepo {
  def findForProfile(pid: ProfileId): Task[Option[TimeLimit]]
  def upsert(pid: ProfileId, mins: Int): Task[Unit]
  def delete(pid: ProfileId): Task[Unit]
  def listAll: Task[List[TimeLimit]]
}

trait SiteTimeLimitRepo {
  def listForProfile(pid: ProfileId): Task[List[SiteTimeLimit]]
  def listAll: Task[List[SiteTimeLimit]]
  def replaceForProfile(pid: ProfileId, limits: List[SiteTimeLimitRequest]): Task[Unit]
}

trait DeviceRepo {
  def listAll: Task[List[Device]]
  def findByMac(mac: MacAddress): Task[Option[Device]]
  def upsert(mac: MacAddress, name: String, pid: Option[ProfileId], ip: String): Task[DeviceId]
  def updateLastSeen(mac: MacAddress, ip: String): Task[Unit]

  /**
   * Update last_seen_ip/at only if the device row exists. Used by router ingest where we don't want
   * to create rows here (events does that).
   */
  def touchLastSeen(mac: MacAddress, ip: Option[IpAddress], at: Instant): Task[Int]

  /**
   * Insert a row for a previously unknown device with NULL profile_id, or refresh last_seen_ip/at
   * on an existing row. Used by /api/router/events.
   */
  def upsertUnknown(
      mac: MacAddress,
      name: String,
      ip: Option[IpAddress],
      at: Instant,
  ): Task[DeviceId]

  /**
   * Rename a device only if its current name is an auto-generated placeholder ("unknown" or
   * "device-XXXXXX"). Used by router ingest to upgrade names once a later DHCP lease carries a real
   * hostname (#249). Returns the number of rows updated (0 if the name was admin-curated).
   */
  def renameIfAutoGenerated(mac: MacAddress, newName: String): Task[Int]
  def updateProfile(mac: MacAddress, pid: ProfileId): Task[Unit]
  def delete(mac: MacAddress): Task[Unit]
}

trait BlocklistRepo {
  def insertBatch(domains: List[(String, String)]): Task[Int]
  def clearCategory(cat: BlocklistId): Task[Unit]
  def listCategories: Task[List[BlocklistId]]
  def countByCategory: Task[List[(BlocklistId, Int)]]
  def loadCategory(cat: BlocklistId): Task[Set[Hostname]]
  def loadAll: Task[Map[BlocklistId, Set[Hostname]]]
}

trait TimeUsageRepo {

  /**
   * Increment seconds + byte counters for (mac, host, date). Repeats are *additive* — the caller is
   * responsible for idempotency at the request level (traffic_reports unique key).
   *
   * `seconds` is the bucket-presence count (bucket duration credited in full to every host the
   * device touched in the bucket). `proportionalSeconds` is the same bucket duration weighted by
   * this host's byte share of the bucket (#715) — a fairer wall-clock attribution for per-host
   * screen-time UI. Daily-cap math reads neither directly: it goes through the presence-based
   * `totalMinutesByMac` over `traffic_reports`.
   */
  def incrementSecondsAndBytes(
      mac: MacAddress,
      host: HostId,
      date: LocalDate,
      seconds: Long,
      bytesIn: Long,
      bytesOut: Long,
      proportionalSeconds: Long = 0L,
  ): Task[Unit]

  /** Read seconds_used for a (mac, host, date) row. Returns 0 if no row. */
  def getSecondsUsed(mac: MacAddress, host: HostId, date: LocalDate): Task[Long]

  /** Read (seconds_used, bytes_in, bytes_out) for a (mac, host, date) row. */
  def getSecondsAndBytes(
      mac: MacAddress,
      host: HostId,
      date: LocalDate,
  ): Task[(Long, Long, Long)]

  /**
   * #715: read the byte-share-weighted proportional seconds for a (mac, host, date) row. Returns 0
   * if no row. Cap math doesn't read this; it's stored so the column stays in sync with
   * `seconds_used` for any consumer that wants a fairer per-host attribution.
   */
  def getProportionalSeconds(mac: MacAddress, host: HostId, date: LocalDate): Task[Long]
  def listForDevice(mac: MacAddress, date: LocalDate): Task[List[TimeUsage]]
  def listForDeviceMacs(macs: List[MacAddress], date: LocalDate): Task[List[TimeUsage]]
  def snapshotAll(date: LocalDate): Task[Map[(MacAddress, HostId), Int]]
}

trait TimeExtensionRepo {
  def getTotalExtension(mac: MacAddress, date: LocalDate): Task[Int]
  def grant(
      mac: MacAddress,
      date: LocalDate,
      mins: Int,
      by: String,
      note: Option[String],
  ): Task[TimeExtensionId]
  def listForDevice(mac: MacAddress, date: LocalDate): Task[List[TimeExtension]]
  def snapshotAll(date: LocalDate): Task[Map[MacAddress, Int]]
  // Profile-level extension methods (V5+)
  def grantForProfile(
      profileId: ProfileId,
      date: LocalDate,
      mins: Int,
      by: String,
      note: Option[String],
  ): Task[TimeExtensionId]
  def getProfileTotalExtension(profileId: ProfileId, date: LocalDate): Task[Int]
  def listForProfile(profileId: ProfileId, date: LocalDate): Task[List[TimeExtension]]
  def snapshotAllByProfile(date: LocalDate): Task[Map[ProfileId, Int]]
}

case class TrafficReportInsert(
    routerId: RouterId,
    mac: MacAddress,
    ip: Option[IpAddress],
    host: HostId,
    date: LocalDate,
    periodStart: Instant,
    periodEnd: Instant,
    activeSeconds: Int,
    bytesIn: Long,
    bytesOut: Long,
)

case class BlockEventInsert(
    mac: Option[MacAddress],
    host: HostId,
    reason: String,
)

case class ConnectionEventInsert(
    routerId: RouterId,
    mac: Option[MacAddress],
    host: HostId,
    destIp: Option[IpAddress],
    allowed: Boolean,
    reason: String,
    ts: Instant,
    // #338: client-supplied idempotency key. None → SQL COALESCEs to
    // gen_random_uuid() so older agents that don't ship an eventId keep
    // inserting cleanly (one fresh UUID per replay, no dedup possible).
    eventId: Option[java.util.UUID] = None,
    // #720: server-side FQDN attribution looked up from prior fqdn-typed
    // events sharing (router_id, dest_ip). NULL when host is already fqdn
    // or when no sibling resolution was found within the lookup window.
    resolvedHost: Option[Hostname] = None,
)

trait RouterRepo {
  def listAll: Task[List[Router]]
  def findById(id: RouterId): Task[Option[Router]]
  def findByEnrollmentTokenHash(h: Sha256Hex): Task[Option[Router]]
  def findByTokenHash(h: Sha256Hex): Task[Option[Router]]
  def create(name: String, enrollmentTokenHash: Sha256Hex): Task[RouterId]
  def completeEnrollment(id: RouterId, tokenHash: Sha256Hex): Task[Unit]
  def touch(id: RouterId, etag: Option[ETag]): Task[Unit]

  def delete(id: RouterId): Task[Unit]
}

trait TrafficReportRepo {
  def insertBatch(reports: List[TrafficReportInsert]): Task[Int]
  def listForDevice(mac: MacAddress, date: LocalDate): Task[List[TrafficReport]]
  def listForRouter(routerId: RouterId, limit: Int): Task[List[TrafficReport]]

  /**
   * Per-5-min traffic_reports rows for aggregation: returned ordered by (router_id, mac, hostname,
   * date, period_start). Filters are AND-composed. `macs = Some(Nil)` returns an empty list (no
   * devices match).
   */
  def listTrafficRollupRows(f: TrafficRollupFilter): Task[List[TrafficRollupRow]]

  /**
   * Minimal projection used by presence-based minute accounting (see
   * [[wifihaven.api.presence.Presence]]). One row per (mac, period_start, hostname) for the given
   * macs/date; the caller deduplicates by `(mac, period_start)` so per-hostname rows in a single
   * bucket don't inflate total screen time.
   */
  def listPresenceRows(
      macs: List[MacAddress],
      date: LocalDate,
  ): Task[List[wifihaven.api.presence.PresenceRow]]

  /**
   * Range variant of [[listPresenceRows]] — inclusive `from`..`to`. Used by the #723 weekly profile
   * screen-time view to compute range-deduped per-mac / per-host totals AND per-period breakdown
   * from one query. Bucketing is UTC end-to-end (storage AND read); household-local-time
   * re-bucketing for the chart happens in the SPA against the UTC `periodStart` instants (#794).
   */
  def listPresenceRows(
      macs: List[MacAddress],
      from: LocalDate,
      to: LocalDate,
  ): Task[List[wifihaven.api.presence.PresenceRow]]

  /**
   * #846: raw rows in `[fromInstant, toInstant)` for the given macs. `macs = Nil` means "all macs"
   * (used by the Traffic Usage page in unfiltered mode). Returns Instants (not String date columns)
   * so callers can bucket without re-parsing.
   */
  def listRawInRange(
      macs: List[MacAddress],
      fromInstant: Instant,
      toInstant: Instant,
  ): Task[List[wifihaven.api.usage.TrafficUsageDbRow]]

  /**
   * #846: earliest `period_start` across all rows. Used by Traffic Usage page to reject `from`
   * instants that fall outside the retention horizon — naïve until #809/#814 land.
   */
  def earliestPeriodStart: Task[Option[Instant]]
}

trait BlockEventRepo {
  def insertBatch(events: List[BlockEventInsert]): Task[Int]
  def recent(limit: Int): Task[List[BlockEvent]]
  def listForMac(mac: MacAddress, limit: Int): Task[List[BlockEvent]]
}

trait ConnectionEventRepo {
  def insertBatch(events: List[ConnectionEventInsert]): Task[Int]
  def recent(limit: Int): Task[List[ConnectionEvent]]
  def listForMac(mac: MacAddress, limit: Int): Task[List[ConnectionEvent]]
  def listForRouter(routerId: RouterId, limit: Int): Task[List[ConnectionEvent]]
  def query(f: LogFilter): Task[List[QueryLog]]
  // #846: multi-column grouping. `groupBy` is the set of column names from
  // {"domain","device","profile"}; the repo returns one row per
  // (window, *grouped-column-values*) with distinct-counts for the rest.
  def querySeries(
      f: LogFilter,
      bucketSeconds: Int,
      groupBy: Set[String],
  ): Task[List[ConnectionEventAggRow]]
  def stats: Task[DashboardStats]
  def topBlocked(hours: Int, limit: Int): Task[List[DomainCount]]

  /**
   * Latest `ts` per mac for events strictly newer than `since`. Used by the "now" dashboard to
   * detect devices that produced at least one connection attempt in the recent window.
   */
  def lastSeenByMacSince(since: Instant): Task[Map[MacAddress, Instant]]

  /**
   * #720 backfill: look up the most recent fqdn-typed connection_event with the given (router_id,
   * dest_ip) whose `ts` is at-or-after `since`. Returns the resolved hostname if any. Used at
   * ingest time to attach a resolution to a fresh ipv4/ipv6-typed event whose agent-side DNS cache
   * lost the race.
   */
  def findRecentFqdnFor(
      routerId: RouterId,
      destIp: IpAddress,
      since: Instant,
  ): Task[Option[Hostname]]

  /**
   * #720 backfill: patch the `resolved_host_value` column on existing ipv4/ipv6-typed rows for the
   * given (router_id, dest_ip) that landed at-or-after `since` and don't yet carry a resolution.
   * Called when a fqdn-typed event lands and "teaches" the API the IP→hostname mapping
   * retroactively. Returns the row count actually updated.
   */
  def backfillResolvedFor(
      routerId: RouterId,
      destIp: IpAddress,
      fqdn: Hostname,
      since: Instant,
  ): Task[Int]
}

class UserRepoLive(xa: Transactor[Task]) extends UserRepo {
  def findByUsername(u: String)             =
    sql"SELECT id,username,password_hash,role,created_at,must_change_password FROM users WHERE username=$u"
      .query[(UserId, String, String, UserRole, Instant, Boolean)]
      .map { case (id, un, ph, role, ca, mcp) => DbUser(id, un, ph, role, ca, mcp) }
      .option
      .transact(xa)
  def findById(id: UserId)                  =
    sql"SELECT id,username,password_hash,role,created_at,must_change_password FROM users WHERE id=$id"
      .query[(UserId, String, String, UserRole, Instant, Boolean)]
      .map { case (id, un, ph, role, ca, mcp) => DbUser(id, un, ph, role, ca, mcp) }
      .option
      .transact(xa)
  def create(u: String, h: String, r: String) =
    // Always force a password change on first login for admin-created users (#599).
    sql"INSERT INTO users(username,password_hash,role,must_change_password) VALUES($u,$h,$r,true) RETURNING id"
      .query[UserId]
      .unique
      .transact(xa)
  def updatePassword(id: UserId, h: String) =
    sql"UPDATE users SET password_hash=$h WHERE id=$id".update.run.transact(xa).unit
  def clearMustChangePassword(id: UserId)   =
    sql"UPDATE users SET must_change_password=false WHERE id=$id".update.run.transact(xa).unit
  def listAll                               =
    sql"SELECT id,username,password_hash,role,created_at,must_change_password FROM users ORDER BY id"
      .query[(UserId, String, String, UserRole, Instant, Boolean)]
      .map { case (id, un, ph, role, ca, mcp) => DbUser(id, un, ph, role, ca, mcp) }
      .to[List]
      .transact(xa)
  def delete(id: UserId) = sql"DELETE FROM users WHERE id=$id".update.run.transact(xa).unit
}

class UserProfileRepoLive(xa: Transactor[Task]) extends UserProfileRepo {
  def listProfilesForUser(userId: UserId)                          =
    sql"SELECT profile_id FROM user_profiles WHERE user_id=$userId ORDER BY profile_id"
      .query[ProfileId]
      .to[List]
      .transact(xa)
  def listProfilesForUsername(u: String)                           =
    sql"SELECT up.profile_id FROM user_profiles up JOIN users us ON us.id=up.user_id WHERE us.username=$u ORDER BY up.profile_id"
      .query[ProfileId]
      .to[List]
      .transact(xa)
  def listUsersForProfile(profileId: ProfileId)                    =
    sql"SELECT user_id FROM user_profiles WHERE profile_id=$profileId ORDER BY user_id"
      .query[UserId]
      .to[List]
      .transact(xa)
  def listAllMappings                                              =
    sql"SELECT user_id, profile_id FROM user_profiles"
      .query[(UserId, ProfileId)]
      .to[List]
      .transact(xa)
  def setProfilesForUser(userId: UserId, pids: List[ProfileId])    = {
    val del = sql"DELETE FROM user_profiles WHERE user_id=$userId".update.run
    val ins = pids.distinct.map(pid =>
      sql"INSERT INTO user_profiles(user_id,profile_id) VALUES($userId,$pid) ON CONFLICT DO NOTHING".update.run,
    )
    (del *> ins.foldLeft(FC.unit)(_ *> _.void)).transact(xa)
  }
  def setUsersForProfile(profileId: ProfileId, uids: List[UserId]) = {
    val del = sql"DELETE FROM user_profiles WHERE profile_id=$profileId".update.run
    val ins = uids.distinct.map(uid =>
      sql"INSERT INTO user_profiles(user_id,profile_id) VALUES($uid,$profileId) ON CONFLICT DO NOTHING".update.run,
    )
    (del *> ins.foldLeft(FC.unit)(_ *> _.void)).transact(xa)
  }
  def addLink(userId: UserId, pid: ProfileId)                      =
    sql"INSERT INTO user_profiles(user_id,profile_id) VALUES($userId,$pid) ON CONFLICT DO NOTHING".update.run
      .transact(xa)
      .unit
  def removeLink(userId: UserId, pid: ProfileId)                   =
    sql"DELETE FROM user_profiles WHERE user_id=$userId AND profile_id=$pid".update.run
      .transact(xa)
      .unit
  def hasAccess(userId: UserId, pid: ProfileId)                    =
    sql"SELECT 1 FROM user_profiles WHERE user_id=$userId AND profile_id=$pid"
      .query[Int]
      .option
      .transact(xa)
      .map(_.isDefined)
}

class ProfileRepoLive(xa: Transactor[Task]) extends ProfileRepo {
  private type R = (
      ProfileId,
      String,
      List[String],
      List[String],
      List[String],
      Boolean,
      String,
      Boolean,
  )
  private def toP(r: R)                             = Profile(
    r._1,
    r._2,
    r._3.map(BlocklistId.unsafe),
    r._4.map(Hostname.unsafe),
    r._5.map(Hostname.unsafe),
    r._6,
    FailureMode.parse(r._7).getOrElse(FailureMode.LastKnownGood),
    r._8,
  )
  def listAll                                       =
    sql"SELECT id,name,blocked_categories,extra_blocked,extra_allowed,paused,failure_mode,block_ip_only FROM profiles ORDER BY id"
      .query[R]
      .map(toP)
      .to[List]
      .transact(xa)
  def findById(id: ProfileId)                       =
    sql"SELECT id,name,blocked_categories,extra_blocked,extra_allowed,paused,failure_mode,block_ip_only FROM profiles WHERE id=$id"
      .query[R]
      .map(toP)
      .option
      .transact(xa)
  def create(name: String, cats: List[BlocklistId]) =
    sql"INSERT INTO profiles(name,blocked_categories) VALUES($name,${cats.map(_.value).toArray}) RETURNING id"
      .query[ProfileId]
      .unique
      .transact(xa)
  def update(p: Profile)                            =
    sql"""UPDATE profiles SET
            name=${p.name},
            blocked_categories=${p.blockedCategories.map(_.value).toArray},
            extra_blocked=${p.extraBlocked.map(_.value).toArray},
            extra_allowed=${p.extraAllowed.map(_.value).toArray},
            paused=${p.paused},
            failure_mode=${FailureMode.asString(p.failureMode)},
            block_ip_only=${p.blockIpOnly}
          WHERE id=${p.id}""".update.run
      .transact(xa)
      .unit
  def delete(id: ProfileId) = sql"DELETE FROM profiles WHERE id=$id".update.run.transact(xa).unit
  def setPaused(id: ProfileId, p: Boolean) =
    sql"UPDATE profiles SET paused=$p WHERE id=$id".update.run.transact(xa).unit
}

class ScheduleRepoLive(xa: Transactor[Task]) extends ScheduleRepo {
  private type R = (ScheduleId, ProfileId, String, List[String], LocalTime, LocalTime, ZoneId)
  private def toS(r: R)              = Schedule(r._1, r._2, r._3, r._4, r._5, r._6, r._7)
  def listAll                        =
    sql"SELECT id,profile_id,name,days,start_local,end_local,tz FROM schedules ORDER BY id"
      .query[R]
      .map(toS)
      .to[List]
      .transact(xa)
  def listForProfile(pid: ProfileId) =
    sql"SELECT id,profile_id,name,days,start_local,end_local,tz FROM schedules WHERE profile_id=$pid ORDER BY id"
      .query[R]
      .map(toS)
      .to[List]
      .transact(xa)
  def replaceForProfile(pid: ProfileId, ss: List[ScheduleRequest]) = {
    val del = sql"DELETE FROM schedules WHERE profile_id=$pid".update.run
    val ins = ss.map(s =>
      sql"INSERT INTO schedules(profile_id,name,days,start_local,end_local,tz) VALUES($pid,${s.name},${s.days.toArray},${s.startLocal},${s.endLocal},${s.tz})".update.run,
    )
    (del *> ins.foldLeft(FC.unit)(_ *> _.void)).transact(xa)
  }
}

class HouseholdSettingsRepoLive(xa: Transactor[Task]) extends HouseholdSettingsRepo {
  def get: Task[HouseholdSettings] =
    sql"""SELECT daily_reset_time, daily_reset_tz,
                 heartbeat_filter_enabled, heartbeat_bytes_threshold,
                 heartbeat_host_patterns
            FROM household_settings WHERE id=1"""
      .query[(LocalTime, ZoneId, Boolean, Int, List[String])]
      .unique
      .map { case (t, z, hbEnabled, hbBytes, hbHosts) =>
        HouseholdSettings(t, z, HeartbeatFilter(hbEnabled, hbBytes, hbHosts))
      }
      .transact(xa)

  def update(s: HouseholdSettings): Task[Unit] =
    sql"""UPDATE household_settings
            SET daily_reset_time=${s.dailyResetTime},
                daily_reset_tz=${s.dailyResetTz},
                heartbeat_filter_enabled=${s.heartbeatFilter.enabled},
                heartbeat_bytes_threshold=${s.heartbeatFilter.bytesThreshold},
                heartbeat_host_patterns=${s.heartbeatFilter.heartbeatHostPatterns.toArray},
                updated_at=NOW()
          WHERE id=1""".update.run.transact(xa).unit

  def ensureDefault(defaultZone: ZoneId): Task[Unit] =
    sql"""INSERT INTO household_settings (id, daily_reset_time, daily_reset_tz)
          VALUES (1, '00:00', ${defaultZone})
          ON CONFLICT (id) DO NOTHING""".update.run.transact(xa).unit
}

class TimeLimitRepoLive(xa: Transactor[Task]) extends TimeLimitRepo {
  def findForProfile(pid: ProfileId)    =
    sql"SELECT id,profile_id,daily_minutes FROM time_limits WHERE profile_id=$pid"
      .query[(TimeLimitId, ProfileId, Int)]
      .map(TimeLimit.apply)
      .option
      .transact(xa)
  def upsert(pid: ProfileId, mins: Int) =
    sql"INSERT INTO time_limits(profile_id,daily_minutes) VALUES($pid,$mins) ON CONFLICT(profile_id) DO UPDATE SET daily_minutes=EXCLUDED.daily_minutes".update.run
      .transact(xa)
      .unit
  def delete(pid: ProfileId)            =
    sql"DELETE FROM time_limits WHERE profile_id=$pid".update.run.transact(xa).unit
  def listAll                           = sql"SELECT id,profile_id,daily_minutes FROM time_limits"
    .query[(TimeLimitId, ProfileId, Int)]
    .map(TimeLimit.apply)
    .to[List]
    .transact(xa)
}

class SiteTimeLimitRepoLive(xa: Transactor[Task]) extends SiteTimeLimitRepo {
  private type R = (SiteTimeLimitId, ProfileId, String, Int, String, Boolean)
  private def toS(r: R)              = SiteTimeLimit(r._1, r._2, r._3, r._4, r._5, r._6)
  def listForProfile(pid: ProfileId) =
    sql"SELECT id,profile_id,domain_pattern,daily_minutes,label,exempt_from_daily FROM site_time_limits WHERE profile_id=$pid ORDER BY id"
      .query[R]
      .map(toS)
      .to[List]
      .transact(xa)
  def listAll                        =
    sql"SELECT id,profile_id,domain_pattern,daily_minutes,label,exempt_from_daily FROM site_time_limits ORDER BY id"
      .query[R]
      .map(toS)
      .to[List]
      .transact(xa)
  def replaceForProfile(pid: ProfileId, ls: List[SiteTimeLimitRequest]) = {
    val del = sql"DELETE FROM site_time_limits WHERE profile_id=$pid".update.run
    val ins = ls.map(l =>
      sql"INSERT INTO site_time_limits(profile_id,domain_pattern,daily_minutes,label,exempt_from_daily) VALUES($pid,${l.domainPattern},${l.dailyMinutes},${l.label},${l.exemptFromDaily})".update.run,
    )
    (del *> ins.foldLeft(FC.unit)(_ *> _.void)).transact(xa)
  }
}

class DeviceRepoLive(xa: Transactor[Task]) extends DeviceRepo {
  def listAll                                                                          =
    sql"SELECT d.id,d.mac,d.name,d.profile_id,p.name,d.last_seen_ip,d.last_seen_at::TEXT FROM devices d LEFT JOIN profiles p ON p.id=d.profile_id ORDER BY d.name"
      .query[
        (
            DeviceId,
            MacAddress,
            String,
            Option[ProfileId],
            Option[String],
            Option[IpAddress],
            Option[String],
        ),
      ]
      .map(r => Device(r._1, r._2, r._3, r._4, r._5, r._6, r._7))
      .to[List]
      .transact(xa)
  def findByMac(mac: MacAddress)                                                       =
    sql"SELECT d.id,d.mac,d.name,d.profile_id,p.name,d.last_seen_ip,d.last_seen_at::TEXT FROM devices d LEFT JOIN profiles p ON p.id=d.profile_id WHERE d.mac=$mac"
      .query[
        (
            DeviceId,
            MacAddress,
            String,
            Option[ProfileId],
            Option[String],
            Option[IpAddress],
            Option[String],
        ),
      ]
      .map(r => Device(r._1, r._2, r._3, r._4, r._5, r._6, r._7))
      .option
      .transact(xa)
  def upsert(mac: MacAddress, name: String, pid: Option[ProfileId], ip: String) =
    // #708: pid=None writes NULL (device unassigned). Devices without a profile
    // are a supported state — same shape auto-discovery produces.
    sql"INSERT INTO devices(mac,name,profile_id,last_seen_ip,last_seen_at) VALUES($mac,$name,$pid,NULLIF($ip,''),NOW()) ON CONFLICT(mac) DO UPDATE SET name=EXCLUDED.name,profile_id=EXCLUDED.profile_id RETURNING id"
      .query[DeviceId]
      .unique
      .transact(xa)
  def updateLastSeen(mac: MacAddress, ip: String)                                      =
    sql"UPDATE devices SET last_seen_ip=$ip,last_seen_at=NOW() WHERE mac=$mac".update.run
      .transact(xa)
      .unit
  def touchLastSeen(mac: MacAddress, ip: Option[IpAddress], at: Instant)               =
    sql"UPDATE devices SET last_seen_ip=COALESCE($ip,last_seen_ip),last_seen_at=$at WHERE mac=$mac".update.run
      .transact(xa)
  def upsertUnknown(mac: MacAddress, name: String, ip: Option[IpAddress], at: Instant) =
    sql"""INSERT INTO devices(mac,name,profile_id,last_seen_ip,last_seen_at)
          VALUES($mac,$name,NULL,$ip,$at)
          ON CONFLICT(mac) DO UPDATE
          SET last_seen_ip=COALESCE(EXCLUDED.last_seen_ip,devices.last_seen_ip),
              last_seen_at=EXCLUDED.last_seen_at
          RETURNING id"""
      .query[DeviceId]
      .unique
      .transact(xa)
  def renameIfAutoGenerated(mac: MacAddress, newName: String)                          = {
    val autoNamePattern = "^device-[0-9a-fA-F]+$"
    sql"""UPDATE devices SET name=$newName
          WHERE mac=$mac AND (name='unknown' OR name ~ $autoNamePattern)""".update.run
      .transact(xa)
  }
  def updateProfile(mac: MacAddress, pid: ProfileId)                                   =
    sql"UPDATE devices SET profile_id=$pid WHERE mac=$mac".update.run.transact(xa).unit
  def delete(mac: MacAddress) = sql"DELETE FROM devices WHERE mac=$mac".update.run.transact(xa).unit
}

class BlocklistRepoLive(xa: Transactor[Task]) extends BlocklistRepo {
  def insertBatch(ds: List[(String, String)]) = Update[(String, String)](
    "INSERT INTO blocklist_domains(domain,category) VALUES(?,?) ON CONFLICT DO NOTHING",
  ).updateMany(ds).transact(xa)
  def clearCategory(cat: BlocklistId)         =
    sql"DELETE FROM blocklist_domains WHERE category=${cat.value}".update.run.transact(xa).unit
  def listCategories  = sql"SELECT DISTINCT category FROM blocklist_domains ORDER BY category"
    .query[BlocklistId]
    .to[List]
    .transact(xa)
  def countByCategory =
    sql"SELECT category,COUNT(*)::INT FROM blocklist_domains GROUP BY category ORDER BY category"
      .query[(BlocklistId, Int)]
      .to[List]
      .transact(xa)
  def loadCategory(cat: BlocklistId) =
    sql"SELECT domain FROM blocklist_domains WHERE category=${cat.value}"
      .query[Hostname]
      .to[List]
      .transact(xa)
      .map(_.toSet)
  def loadAll                        = sql"SELECT category,domain FROM blocklist_domains"
    .query[(BlocklistId, Hostname)]
    .to[List]
    .transact(xa)
    .map(_.groupBy(_._1).map((k, vs) => k -> vs.map(_._2).toSet))
}

class TimeUsageRepoLive(xa: Transactor[Task]) extends TimeUsageRepo {
  def incrementSecondsAndBytes(
      mac: MacAddress,
      host: HostId,
      d: LocalDate,
      seconds: Long,
      bytesIn: Long,
      bytesOut: Long,
      proportionalSeconds: Long = 0L,
  ): Task[Unit] =
    sql"""INSERT INTO time_usage(device_mac,host_type,host_value,date,seconds_used,proportional_seconds,bytes_in,bytes_out,last_seen_at)
          VALUES($mac,${host.kind},${host.value},$d,$seconds,$proportionalSeconds,$bytesIn,$bytesOut,NOW())
          ON CONFLICT(device_mac,host_type,host_value,date) DO UPDATE
          SET seconds_used=time_usage.seconds_used+EXCLUDED.seconds_used,
              proportional_seconds=time_usage.proportional_seconds+EXCLUDED.proportional_seconds,
              bytes_in=time_usage.bytes_in+EXCLUDED.bytes_in,
              bytes_out=time_usage.bytes_out+EXCLUDED.bytes_out,
              last_seen_at=NOW()""".update.run
      .transact(xa)
      .unit
  def getProportionalSeconds(mac: MacAddress, host: HostId, d: LocalDate): Task[Long]           =
    sql"SELECT COALESCE(proportional_seconds,0) FROM time_usage WHERE device_mac=$mac AND host_type=${host.kind} AND host_value=${host.value} AND date=$d"
      .query[Long]
      .option
      .transact(xa)
      .map(_.getOrElse(0L))
  def getSecondsUsed(mac: MacAddress, host: HostId, d: LocalDate): Task[Long]                   =
    sql"SELECT COALESCE(seconds_used,0) FROM time_usage WHERE device_mac=$mac AND host_type=${host.kind} AND host_value=${host.value} AND date=$d"
      .query[Long]
      .option
      .transact(xa)
      .map(_.getOrElse(0L))
  def getSecondsAndBytes(mac: MacAddress, host: HostId, d: LocalDate): Task[(Long, Long, Long)] =
    sql"SELECT COALESCE(seconds_used,0),COALESCE(bytes_in,0),COALESCE(bytes_out,0) FROM time_usage WHERE device_mac=$mac AND host_type=${host.kind} AND host_value=${host.value} AND date=$d"
      .query[(Long, Long, Long)]
      .option
      .transact(xa)
      .map(_.getOrElse((0L, 0L, 0L)))
  // TODO(#730): remove this read-side join once usage records carry dest_ip.
  // The LATERAL subquery promotes ipv4-typed time_usage rows to their resolved
  // fqdn by looking up the most recent connection_events row for the same
  // (mac, dest_ip) that has a resolved_host_value. The partial index added in
  // V22 (idx_conn_events_mac_dest_resolved) keeps the join cheap.
  def listForDevice(mac: MacAddress, d: LocalDate)                                              =
    sql"""SELECT tu.id,
                 tu.device_mac,
                 CASE WHEN tu.host_type IN ('ipv4','ipv6') AND ce.resolved_host_value IS NOT NULL
                      THEN 'fqdn' ELSE tu.host_type END,
                 COALESCE(CASE WHEN tu.host_type IN ('ipv4','ipv6') THEN ce.resolved_host_value END,
                          tu.host_value),
                 tu.date::TEXT,
                 (COALESCE(tu.seconds_used,0)/60)::INT,
                 tu.last_seen_at::TEXT
          FROM time_usage tu
          LEFT JOIN LATERAL (
            SELECT resolved_host_value
            FROM connection_events
            WHERE mac          = tu.device_mac
              AND dest_ip      = tu.host_value
              AND resolved_host_value IS NOT NULL
              AND ts >= $d::TIMESTAMPTZ
              AND ts <  ($d::DATE + INTERVAL '1 day')::TIMESTAMPTZ
            ORDER BY ts DESC LIMIT 1
          ) ce ON tu.host_type IN ('ipv4','ipv6')
          WHERE tu.device_mac = $mac AND tu.date = $d
          ORDER BY tu.seconds_used DESC"""
      .query[(TimeUsageId, MacAddress, HostId, String, Int, String)]
      .map(TimeUsage.apply)
      .to[List]
      .transact(xa)
  // TODO(#730): remove this read-side join once usage records carry dest_ip.
  def listForDeviceMacs(macs: List[MacAddress], d: LocalDate)                                   =
    if macs.isEmpty then ZIO.succeed(Nil)
    else {
      val arr = macs.map(_.value).toArray
      sql"""SELECT tu.id,
                   tu.device_mac,
                   CASE WHEN tu.host_type IN ('ipv4','ipv6') AND ce.resolved_host_value IS NOT NULL
                        THEN 'fqdn' ELSE tu.host_type END,
                   COALESCE(CASE WHEN tu.host_type IN ('ipv4','ipv6') THEN ce.resolved_host_value END,
                            tu.host_value),
                   tu.date::TEXT,
                   (COALESCE(tu.seconds_used,0)/60)::INT,
                   tu.last_seen_at::TEXT
            FROM time_usage tu
            LEFT JOIN LATERAL (
              SELECT resolved_host_value
              FROM connection_events
              WHERE mac          = tu.device_mac
                AND dest_ip      = tu.host_value
                AND resolved_host_value IS NOT NULL
                AND ts >= $d::TIMESTAMPTZ
                AND ts <  ($d::DATE + INTERVAL '1 day')::TIMESTAMPTZ
              ORDER BY ts DESC LIMIT 1
            ) ce ON tu.host_type IN ('ipv4','ipv6')
            WHERE tu.device_mac = ANY($arr) AND tu.date = $d
            ORDER BY tu.device_mac, tu.seconds_used DESC"""
        .query[(TimeUsageId, MacAddress, HostId, String, Int, String)]
        .map(TimeUsage.apply)
        .to[List]
        .transact(xa)
    }
  // TODO(#730): remove this read-side join once usage records carry dest_ip.
  def snapshotAll(d: LocalDate)                                                                 =
    sql"""SELECT tu.device_mac,
                 CASE WHEN tu.host_type IN ('ipv4','ipv6') AND ce.resolved_host_value IS NOT NULL
                      THEN 'fqdn' ELSE tu.host_type END,
                 COALESCE(CASE WHEN tu.host_type IN ('ipv4','ipv6') THEN ce.resolved_host_value END,
                          tu.host_value),
                 (COALESCE(tu.seconds_used,0)/60)::INT
          FROM time_usage tu
          LEFT JOIN LATERAL (
            SELECT resolved_host_value
            FROM connection_events
            WHERE mac          = tu.device_mac
              AND dest_ip      = tu.host_value
              AND resolved_host_value IS NOT NULL
              AND ts >= $d::TIMESTAMPTZ
              AND ts <  ($d::DATE + INTERVAL '1 day')::TIMESTAMPTZ
            ORDER BY ts DESC LIMIT 1
          ) ce ON tu.host_type IN ('ipv4','ipv6')
          WHERE tu.date = $d"""
      .query[(MacAddress, HostId, Int)]
      .to[List]
      .transact(xa)
      .map(_.map((m, host, mins) => (m, host) -> mins).toMap)
}

class TimeExtensionRepoLive(xa: Transactor[Task]) extends TimeExtensionRepo {
  def getTotalExtension(mac: MacAddress, d: LocalDate)                                           =
    sql"SELECT COALESCE(SUM(extra_minutes),0)::INT FROM time_extensions WHERE device_mac=$mac AND date=$d"
      .query[Int]
      .unique
      .transact(xa)
  def grant(mac: MacAddress, d: LocalDate, mins: Int, by: String, note: Option[String])          =
    sql"INSERT INTO time_extensions(device_mac,date,extra_minutes,granted_by,note) VALUES($mac,$d,$mins,$by,$note) RETURNING id"
      .query[TimeExtensionId]
      .unique
      .transact(xa)
  def listForDevice(mac: MacAddress, d: LocalDate)                                               =
    sql"SELECT id,profile_id,device_mac,date::TEXT,extra_minutes,granted_by,note,created_at::TEXT FROM time_extensions WHERE device_mac=$mac AND date=$d ORDER BY created_at"
      .query[
        (
            TimeExtensionId,
            Option[ProfileId],
            Option[MacAddress],
            String,
            Int,
            String,
            Option[String],
            String,
        ),
      ]
      .map(TimeExtension.apply)
      .to[List]
      .transact(xa)
  def snapshotAll(d: LocalDate)                                                                  =
    sql"SELECT device_mac,SUM(extra_minutes)::INT FROM time_extensions WHERE date=$d AND device_mac IS NOT NULL GROUP BY device_mac"
      .query[(MacAddress, Int)]
      .to[List]
      .transact(xa)
      .map(_.toMap)
  def grantForProfile(pid: ProfileId, d: LocalDate, mins: Int, by: String, note: Option[String]) =
    sql"INSERT INTO time_extensions(profile_id,date,extra_minutes,granted_by,note) VALUES($pid,$d,$mins,$by,$note) RETURNING id"
      .query[TimeExtensionId]
      .unique
      .transact(xa)
  def getProfileTotalExtension(pid: ProfileId, d: LocalDate)                                     =
    sql"SELECT COALESCE(SUM(extra_minutes),0)::INT FROM time_extensions WHERE profile_id=$pid AND date=$d"
      .query[Int]
      .unique
      .transact(xa)
  def listForProfile(pid: ProfileId, d: LocalDate)                                               =
    sql"SELECT id,profile_id,device_mac,date::TEXT,extra_minutes,granted_by,note,created_at::TEXT FROM time_extensions WHERE profile_id=$pid AND date=$d ORDER BY created_at"
      .query[
        (
            TimeExtensionId,
            Option[ProfileId],
            Option[MacAddress],
            String,
            Int,
            String,
            Option[String],
            String,
        ),
      ]
      .map(TimeExtension.apply)
      .to[List]
      .transact(xa)
  def snapshotAllByProfile(d: LocalDate)                                                         =
    sql"SELECT profile_id,SUM(extra_minutes)::INT FROM time_extensions WHERE date=$d AND profile_id IS NOT NULL GROUP BY profile_id"
      .query[(ProfileId, Int)]
      .to[List]
      .transact(xa)
      .map(_.toMap)
}

class RouterRepoLive(xa: Transactor[Task]) extends RouterRepo {
  private type R =
    (
        RouterId,
        String,
        Option[Sha256Hex],
        Option[Sha256Hex],
        Option[Instant],
        Option[ETag],
        Instant,
    )
  private def toR(r: R)                                      =
    Router(
      r._1,
      r._2,
      r._3,
      r._4,
      r._5.map(_.toString),
      r._6,
      r._7.toString,
    )
  private val cols                                           =
    fr"id,name,enrollment_token_hash,token_hash,last_seen_at,last_etag,created_at"
  def listAll                                                =
    (fr"SELECT " ++ cols ++ fr" FROM routers ORDER BY created_at")
      .query[R]
      .map(toR)
      .to[List]
      .transact(xa)
  def findById(id: RouterId)                                 =
    (fr"SELECT " ++ cols ++ fr" FROM routers WHERE id=$id")
      .query[R]
      .map(toR)
      .option
      .transact(xa)
  def findByEnrollmentTokenHash(h: Sha256Hex)                =
    (fr"SELECT " ++ cols ++ fr" FROM routers WHERE enrollment_token_hash=$h")
      .query[R]
      .map(toR)
      .option
      .transact(xa)
  def findByTokenHash(h: Sha256Hex)                          =
    (fr"SELECT " ++ cols ++ fr" FROM routers WHERE token_hash=$h")
      .query[R]
      .map(toR)
      .option
      .transact(xa)
  def create(name: String, enrollmentTokenHash: Sha256Hex)   =
    sql"INSERT INTO routers(name,enrollment_token_hash) VALUES($name,$enrollmentTokenHash) RETURNING id"
      .query[RouterId]
      .unique
      .transact(xa)
  def completeEnrollment(id: RouterId, tokenHash: Sha256Hex) =
    sql"UPDATE routers SET token_hash=$tokenHash, enrollment_token_hash=NULL, last_seen_at=NOW() WHERE id=$id".update.run
      .transact(xa)
      .unit
  def touch(id: RouterId, etag: Option[ETag])                =
    sql"UPDATE routers SET last_seen_at=NOW(), last_etag=COALESCE($etag,last_etag) WHERE id=$id".update.run
      .transact(xa)
      .unit
  def delete(id: RouterId)                                   =
    sql"DELETE FROM routers WHERE id=$id".update.run.transact(xa).unit
}

class TrafficReportRepoLive(xa: Transactor[Task]) extends TrafficReportRepo {
  private type R =
    (
        TrafficReportId,
        RouterId,
        MacAddress,
        Option[IpAddress],
        HostId,
        String,
        String,
        String,
        Int,
        Long,
        Long,
    )
  private def toT(r: R)                               =
    TrafficReport(r._1, r._2, r._3, r._4, r._5, r._6, r._7, r._8, r._9, r._10, r._11)
  def insertBatch(reports: List[TrafficReportInsert]) =
    Update[TrafficReportInsert](
      "INSERT INTO traffic_reports(router_id,mac,ip,host_type,host_value,date,period_start,period_end,active_seconds,bytes_in,bytes_out) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(router_id,period_start,mac,host_type,host_value) DO NOTHING",
    ).updateMany(reports).transact(xa)
  // TODO(#730): remove this read-side join once usage records carry dest_ip.
  // Promotes ipv4/ipv6-typed traffic_reports rows to their resolved fqdn at
  // SELECT time via the same LATERAL join used in TimeUsageRepoLive.
  def listForDevice(mac: MacAddress, date: LocalDate) =
    sql"""SELECT tr.id, tr.router_id, tr.mac, tr.ip,
                 CASE WHEN tr.host_type IN ('ipv4','ipv6') AND ce.resolved_host_value IS NOT NULL
                      THEN 'fqdn' ELSE tr.host_type END,
                 COALESCE(CASE WHEN tr.host_type IN ('ipv4','ipv6') THEN ce.resolved_host_value END,
                          tr.host_value),
                 tr.date::TEXT, tr.period_start::TEXT, tr.period_end::TEXT,
                 tr.active_seconds, tr.bytes_in, tr.bytes_out
          FROM traffic_reports tr
          LEFT JOIN LATERAL (
            SELECT resolved_host_value
            FROM connection_events
            WHERE mac          = tr.mac
              AND dest_ip      = tr.host_value
              AND resolved_host_value IS NOT NULL
              AND ts >= $date::TIMESTAMPTZ
              AND ts <  ($date::DATE + INTERVAL '1 day')::TIMESTAMPTZ
            ORDER BY ts DESC LIMIT 1
          ) ce ON tr.host_type IN ('ipv4','ipv6')
          WHERE tr.mac = $mac AND tr.date = $date
          ORDER BY tr.period_start"""
      .query[R]
      .map(toT)
      .to[List]
      .transact(xa)
  // TODO(#730): remove this read-side join once usage records carry dest_ip.
  def listForRouter(routerId: RouterId, limit: Int)   =
    sql"""SELECT tr.id, tr.router_id, tr.mac, tr.ip,
                 CASE WHEN tr.host_type IN ('ipv4','ipv6') AND ce.resolved_host_value IS NOT NULL
                      THEN 'fqdn' ELSE tr.host_type END,
                 COALESCE(CASE WHEN tr.host_type IN ('ipv4','ipv6') THEN ce.resolved_host_value END,
                          tr.host_value),
                 tr.date::TEXT, tr.period_start::TEXT, tr.period_end::TEXT,
                 tr.active_seconds, tr.bytes_in, tr.bytes_out
          FROM traffic_reports tr
          LEFT JOIN LATERAL (
            SELECT resolved_host_value
            FROM connection_events
            WHERE mac          = tr.mac
              AND dest_ip      = tr.host_value
              AND resolved_host_value IS NOT NULL
              AND ts >= tr.date::TIMESTAMPTZ
              AND ts <  (tr.date + INTERVAL '1 day')::TIMESTAMPTZ
            ORDER BY ts DESC LIMIT 1
          ) ce ON tr.host_type IN ('ipv4','ipv6')
          WHERE tr.router_id = $routerId
          ORDER BY tr.period_start DESC LIMIT $limit"""
      .query[R]
      .map(toT)
      .to[List]
      .transact(xa)

  def listPresenceRows(macs: List[MacAddress], date: LocalDate) =
    listPresenceRowsBetween(macs, date, date)

  def listPresenceRows(macs: List[MacAddress], from: LocalDate, to: LocalDate) =
    listPresenceRowsBetween(macs, from, to)

  // TODO(#730): remove this read-side join once usage records carry dest_ip.
  private def listPresenceRowsBetween(
      macs: List[MacAddress],
      from: LocalDate,
      to: LocalDate,
  ) = {
    type Row = (MacAddress, LocalDate, Instant, HostId, Int, Long, Long, Instant, Instant)
    macs match {
      case Nil => ZIO.succeed(List.empty[wifihaven.api.presence.PresenceRow])
      case ms  =>
        val nel = cats.data.NonEmptyList.fromListUnsafe(ms.map(_.value))
        val q   =
          fr"""SELECT tr.mac, tr.date, tr.period_start,
                      CASE WHEN tr.host_type IN ('ipv4','ipv6') AND ce.resolved_host_value IS NOT NULL
                           THEN 'fqdn' ELSE tr.host_type END,
                      COALESCE(CASE WHEN tr.host_type IN ('ipv4','ipv6') THEN ce.resolved_host_value END,
                               tr.host_value),
                      tr.active_seconds, tr.bytes_in, tr.bytes_out, tr.period_start, tr.period_end
               FROM traffic_reports tr
               LEFT JOIN LATERAL (
                 SELECT resolved_host_value
                 FROM connection_events
                 WHERE mac          = tr.mac
                   AND dest_ip      = tr.host_value
                   AND resolved_host_value IS NOT NULL
                   AND ts >= tr.date::TIMESTAMPTZ
                   AND ts <  (tr.date + INTERVAL '1 day')::TIMESTAMPTZ
                 ORDER BY ts DESC LIMIT 1
               ) ce ON tr.host_type IN ('ipv4','ipv6')
               WHERE tr.date BETWEEN $from AND $to
                 AND (tr.active_seconds > 0 OR tr.bytes_in > 0 OR tr.bytes_out > 0)
                 AND """ ++ Fragments.in(fr"tr.mac", nel)
        q.query[Row]
          .map { case (m, d, ps, host, secs, bin, bout, pStart, pEnd) =>
            val periodSeconds = math.max(0L, pEnd.getEpochSecond - pStart.getEpochSecond).toInt
            wifihaven.api.presence.PresenceRow(m, d, ps, host, secs, bin + bout, periodSeconds)
          }
          .to[List]
          .transact(xa)
    }
  }

  // #846: raw row range pull. Wide range × all-macs scans traffic_reports — caller
  // (UsageTrafficService) enforces a window cap that keeps this from melting prod.
  // TODO(#730): remove this read-side join once usage records carry dest_ip.
  def listRawInRange(macs: List[MacAddress], fromInstant: Instant, toInstant: Instant) = {
    type Row =
      (MacAddress, HostId, Instant, Instant, Int, Long, Long)
    val baseSelect =
      fr"""SELECT tr.mac,
                  CASE WHEN tr.host_type IN ('ipv4','ipv6') AND ce.resolved_host_value IS NOT NULL
                       THEN 'fqdn' ELSE tr.host_type END,
                  COALESCE(CASE WHEN tr.host_type IN ('ipv4','ipv6') THEN ce.resolved_host_value END,
                           tr.host_value),
                  tr.period_start, tr.period_end,
                  tr.active_seconds, tr.bytes_in, tr.bytes_out
           FROM traffic_reports tr
           LEFT JOIN LATERAL (
             SELECT resolved_host_value
             FROM connection_events
             WHERE mac          = tr.mac
               AND dest_ip      = tr.host_value
               AND resolved_host_value IS NOT NULL
               AND ts >= tr.date::TIMESTAMPTZ
               AND ts <  (tr.date + INTERVAL '1 day')::TIMESTAMPTZ
             ORDER BY ts DESC LIMIT 1
           ) ce ON tr.host_type IN ('ipv4','ipv6')
           WHERE tr.period_start >= $fromInstant AND tr.period_start < $toInstant
             AND (tr.active_seconds > 0 OR tr.bytes_in > 0 OR tr.bytes_out > 0) """
    val macFilter  = macs match {
      case Nil => fr""
      case ms  =>
        val nel = cats.data.NonEmptyList.fromListUnsafe(ms.map(_.value))
        fr"AND " ++ Fragments.in(fr"tr.mac", nel)
    }
    // #846 audit: newest-first ordering so the SPA renders most-recent at top
    // and the route's `take(rawLimit)` returns the most recent N rows.
    val select     = baseSelect ++ macFilter ++ fr"ORDER BY tr.period_start DESC"
    select
      .query[Row]
      .map { case (m, h, ps, pe, secs, bi, bo) =>
        wifihaven.api.usage.TrafficUsageDbRow(m, h, ps, pe, secs, bi, bo)
      }
      .to[List]
      .transact(xa)
  }

  def earliestPeriodStart =
    sql"SELECT MIN(period_start) FROM traffic_reports"
      .query[Option[Instant]]
      .unique
      .transact(xa)

  // TODO(#730): remove this read-side join once usage records carry dest_ip.
  def listTrafficRollupRows(f: TrafficRollupFilter) = {
    type Row = (RouterId, MacAddress, HostId, LocalDate, Instant, Instant, Int, Long, Long)
    val base    =
      fr"""SELECT tr.router_id, tr.mac,
                  CASE WHEN tr.host_type IN ('ipv4','ipv6') AND ce.resolved_host_value IS NOT NULL
                       THEN 'fqdn' ELSE tr.host_type END,
                  COALESCE(CASE WHEN tr.host_type IN ('ipv4','ipv6') THEN ce.resolved_host_value END,
                           tr.host_value),
                  tr.date, tr.period_start, tr.period_end,
                  tr.active_seconds, tr.bytes_in, tr.bytes_out
           FROM traffic_reports tr
           LEFT JOIN LATERAL (
             SELECT resolved_host_value
             FROM connection_events
             WHERE mac          = tr.mac
               AND dest_ip      = tr.host_value
               AND resolved_host_value IS NOT NULL
               AND ts >= tr.date::TIMESTAMPTZ
               AND ts <  (tr.date + INTERVAL '1 day')::TIMESTAMPTZ
             ORDER BY ts DESC LIMIT 1
           ) ce ON tr.host_type IN ('ipv4','ipv6')
           WHERE 1=1"""
    val byMacs  = f.macs match {
      case None      => fr""
      case Some(Nil) => fr"AND FALSE"
      case Some(ms)  =>
        val nel = cats.data.NonEmptyList.fromListUnsafe(ms.map(_.value))
        fr"AND " ++ Fragments.in(fr"tr.mac", nel)
    }
    val byHost  = f.host.fold(fr"")(h => fr"AND tr.host_value ILIKE ${s"%$h%"}")
    val bySince = f.since.fold(fr"")(s => fr"AND tr.period_end > $s")
    val byUntil = f.until.fold(fr"")(u => fr"AND tr.period_start < $u")
    val sql_    = base ++ byMacs ++ byHost ++ bySince ++ byUntil ++
      fr"ORDER BY tr.router_id, tr.mac, tr.host_type, tr.host_value, tr.date, tr.period_start"
    sql_
      .query[Row]
      .map { r =>
        TrafficRollupRow(
          routerId = r._1,
          mac = r._2,
          host = r._3,
          date = r._4,
          periodStart = r._5,
          periodEnd = r._6,
          activeSeconds = r._7,
          bytesIn = r._8,
          bytesOut = r._9,
        )
      }
      .to[List]
      .transact(xa)
  }
}

class BlockEventRepoLive(xa: Transactor[Task]) extends BlockEventRepo {
  private type R = (BlockEventId, Option[MacAddress], HostId, String, String)
  private def toB(r: R)                           = BlockEvent(r._1, r._2, r._3, r._4, r._5)
  def insertBatch(events: List[BlockEventInsert]) =
    Update[BlockEventInsert](
      "INSERT INTO block_events(mac,host_type,host_value,reason) VALUES(?,?,?,?)",
    ).updateMany(events).transact(xa)
  def recent(limit: Int)                          =
    sql"SELECT id,mac,host_type,host_value,reason,ts::TEXT FROM block_events ORDER BY ts DESC LIMIT $limit"
      .query[R]
      .map(toB)
      .to[List]
      .transact(xa)
  def listForMac(mac: MacAddress, limit: Int)     =
    sql"SELECT id,mac,host_type,host_value,reason,ts::TEXT FROM block_events WHERE mac=$mac ORDER BY ts DESC LIMIT $limit"
      .query[R]
      .map(toB)
      .to[List]
      .transact(xa)
}

class ConnectionEventRepoLive(xa: Transactor[Task]) extends ConnectionEventRepo {
  private type R =
    (
        ConnectionEventId,
        RouterId,
        Option[MacAddress],
        HostId,
        Option[IpAddress],
        Boolean,
        String,
        String,
    )
  private def toC(r: R) =
    ConnectionEvent(r._1, r._2, r._3, r._4, r._5, r._6, r._7, r._8)

  // #338: idempotent insert. Client-supplied eventId is the dedup key for
  // retry-queue replays (#330). NULL → server-generated via gen_random_uuid()
  // (older agents pre-eventId support). ON CONFLICT DO NOTHING collapses
  // replays; updateMany returns count of rows actually inserted.
  // #720: resolved_host_value carries an API-side FQDN attribution for
  // ipv4/ipv6-typed events; ingest sets it from sibling fqdn events.
  def insertBatch(events: List[ConnectionEventInsert]) =
    Update[ConnectionEventInsert](
      "INSERT INTO connection_events(router_id,mac,host_type,host_value,dest_ip,allowed,reason,ts,event_id,resolved_host_value) " +
        "VALUES(?,?,?,?,?,?,?,?,COALESCE(?, gen_random_uuid()),?) " +
        "ON CONFLICT (event_id) DO NOTHING",
    ).updateMany(events).transact(xa)

  // #720: read paths coalesce a populated resolved_host_value into the host
  // tuple so callers see ('fqdn', resolved) instead of ('ipv4', literal-ip).
  // The raw columns remain untouched on disk; this is purely a render-time
  // promotion. Done in SQL so doobie's tuple decoder receives the already-
  // resolved values.
  private val selectCols: Fragment =
    fr"""id,
         router_id,
         mac,
         CASE WHEN resolved_host_value IS NOT NULL THEN 'fqdn' ELSE host_type END AS host_type,
         COALESCE(resolved_host_value, host_value) AS host_value,
         dest_ip,
         allowed,
         reason,
         ts::TEXT"""

  def recent(limit: Int) =
    (fr"SELECT" ++ selectCols ++ fr"FROM connection_events ORDER BY ts DESC LIMIT $limit")
      .query[R]
      .map(toC)
      .to[List]
      .transact(xa)

  def listForMac(mac: MacAddress, limit: Int) =
    (fr"SELECT" ++ selectCols ++ fr"FROM connection_events WHERE mac=$mac ORDER BY ts DESC LIMIT $limit")
      .query[R]
      .map(toC)
      .to[List]
      .transact(xa)

  def listForRouter(routerId: RouterId, limit: Int) =
    (fr"SELECT" ++ selectCols ++ fr"FROM connection_events WHERE router_id=$routerId ORDER BY ts DESC LIMIT $limit")
      .query[R]
      .map(toC)
      .to[List]
      .transact(xa)

  def findRecentFqdnFor(routerId: RouterId, destIp: IpAddress, since: Instant) =
    sql"""SELECT host_value FROM connection_events
          WHERE router_id = $routerId
            AND dest_ip   = $destIp
            AND host_type = 'fqdn'
            AND ts >= $since
          ORDER BY ts DESC
          LIMIT 1"""
      .query[Hostname]
      .option
      .transact(xa)

  def backfillResolvedFor(
      routerId: RouterId,
      destIp: IpAddress,
      fqdn: Hostname,
      since: Instant,
  ) =
    sql"""UPDATE connection_events
          SET resolved_host_value = ${fqdn.value}
          WHERE router_id = $routerId
            AND dest_ip   = $destIp
            AND host_type IN ('ipv4','ipv6')
            AND resolved_host_value IS NULL
            AND ts >= $since""".update.run.transact(xa)

  // ── Dashboard / log API ──────────────────────────────────────────────────

  def query(f: LogFilter) = {
    // location is sourced from routers.name until routers.location lands (#136)
    // #720: coalesce resolved_host_value into the returned host tuple so
    // race-loser ipv4 rows show up under their resolved FQDN in the log UI
    // and in domain ILIKE filters.
    val base  =
      fr"""SELECT ce.id, ce.mac, d.name, d.profile_id, p.name,
                  CASE WHEN ce.resolved_host_value IS NOT NULL THEN 'fqdn' ELSE ce.host_type END,
                  COALESCE(ce.resolved_host_value, ce.host_value),
                  1, NOT ce.allowed, ce.reason, r.name, ce.ts::TEXT
           FROM connection_events ce
           LEFT JOIN devices d  ON d.mac    = ce.mac
           LEFT JOIN profiles p ON p.id     = d.profile_id
           LEFT JOIN routers r  ON r.id     = ce.router_id
           WHERE 1=1"""
    val since = fr"AND ce.ts > NOW() - make_interval(hours => ${f.hours})"
    val byMac = f.mac.fold(fr"")(m => fr"AND ce.mac = $m")
    val byDev = f.deviceId.fold(fr"")(id => fr"AND d.id = $id")
    val byPid = f.profileId.fold(fr"")(pid => fr"AND d.profile_id = $pid")
    val byBl  = f.blocked.fold(fr"")(b => fr"AND ce.allowed = ${!b}")
    val byDom = f.domain.fold(fr"")(d =>
      // #720: domain filter has to look through the resolution too — otherwise
      // a search for "youtube.com" would miss race-loser ipv4 rows we just
      // attributed.
      fr"AND COALESCE(ce.resolved_host_value, ce.host_value) ILIKE ${s"%$d%"}",
    )
    val byLoc = f.location.fold(fr"")(l => fr"AND r.name = $l")
    (base ++ since ++ byMac ++ byDev ++ byPid ++ byBl ++ byDom ++ byLoc ++
      fr"ORDER BY ce.ts DESC LIMIT ${f.limit} OFFSET ${f.offset}")
      .query[
        (
            QueryLogId,
            Option[MacAddress],
            Option[String],
            Option[ProfileId],
            Option[String],
            HostId,
            Int,
            Boolean,
            String,
            Option[String],
            String,
        ),
      ]
      .map(QueryLog.apply)
      .to[List]
      .transact(xa)
  }

  // #847 + #846: multi-column aggregation over connection_events. Buckets are
  // computed in UTC via date_bin — UI re-renders boundaries in household-local
  // tz for display. No rollup table exists yet (#809 in flight); for now even
  // wide buckets compute on-the-fly from connection_events.
  //
  // #846 audit: emit ISO 8601 with T separator + trailing Z so JS Date.parse
  // accepts these without a per-field workaround. Postgres TIMESTAMPTZ::TEXT
  // defaults to "2026-05-21 22:00:00+00" (space separator) which `new Date(...)`
  // rejects as Invalid Date.
  def querySeries(f: LogFilter, bucketSeconds: Int, groupBy: Set[String]) = {
    val bucketIv    = fr"make_interval(secs => $bucketSeconds)"
    val domainExpr  = fr"COALESCE(ce.resolved_host_value, ce.host_value)"
    val deviceExpr  = fr"COALESCE(d.name, ce.mac::TEXT)"
    val profileExpr = fr"COALESCE(p.name, '(unassigned)')"

    // Default group: domain (matches pre-#846 behaviour). Multi-group composes
    // freely across {domain, device, profile} — apex/app rejected at route.
    val wantsDomain  = groupBy.contains("domain") || groupBy.isEmpty
    val wantsDevice  = groupBy.contains("device")
    val wantsProfile = groupBy.contains("profile")

    // Always SELECT all three group expressions (NULL when not requested) so
    // the result tuple has a constant shape and doobie can decode it.
    val selDomain  = if (wantsDomain) domainExpr else fr"NULL::TEXT"
    val selDevice  = if (wantsDevice) deviceExpr else fr"NULL::TEXT"
    val selProfile = if (wantsProfile) profileExpr else fr"NULL::TEXT"

    // GROUP BY only the requested columns, plus the window bucket.
    val groupByParts = List(
      Some(fr"window_start"),
      Option.when(wantsDomain)(domainExpr),
      Option.when(wantsDevice)(deviceExpr),
      Option.when(wantsProfile)(profileExpr),
    ).flatten
    val groupByCols  = groupByParts.reduce(_ ++ fr"," ++ _)

    val base  =
      fr"""SELECT """ ++ selDomain ++ fr"AS grp_domain," ++
        selDevice ++ fr"AS grp_device," ++
        selProfile ++ fr"""AS grp_profile,
                  to_char(date_bin($bucketIv, ce.ts, TIMESTAMP '2000-01-01 00:00:00')
                          AT TIME ZONE 'UTC',
                          'YYYY-MM-DD"T"HH24:MI:SS"Z"') AS window_start,
                  COUNT(*) FILTER (WHERE ce.allowed)::INT      AS count_succeeded,
                  COUNT(*) FILTER (WHERE NOT ce.allowed)::INT  AS count_blocked,
                  to_char(MAX(ce.ts) AT TIME ZONE 'UTC',
                          'YYYY-MM-DD"T"HH24:MI:SS"Z"')  AS last_seen,
                  mode() WITHIN GROUP (ORDER BY """ ++ deviceExpr ++ fr""") AS top_device,
                  COUNT(DISTINCT """ ++ deviceExpr ++ fr""")::INT          AS distinct_devices,
                  COUNT(DISTINCT """ ++ profileExpr ++ fr""")::INT         AS distinct_profiles,
                  COUNT(DISTINCT """ ++ domainExpr ++ fr""")::INT          AS distinct_domains,
                  CASE WHEN COUNT(DISTINCT """ ++ deviceExpr ++ fr""") = 1
                       THEN MAX(""" ++ deviceExpr ++ fr""") END            AS sole_device,
                  CASE WHEN COUNT(DISTINCT """ ++ profileExpr ++ fr""") = 1
                       THEN MAX(""" ++ profileExpr ++ fr""") END           AS sole_profile,
                  CASE WHEN COUNT(DISTINCT """ ++ domainExpr ++ fr""") = 1
                       THEN MAX(""" ++ domainExpr ++ fr""") END            AS sole_domain
           FROM connection_events ce
           LEFT JOIN devices d  ON d.mac = ce.mac
           LEFT JOIN profiles p ON p.id  = d.profile_id
           LEFT JOIN routers r  ON r.id  = ce.router_id
           WHERE 1=1"""
    val since = fr"AND ce.ts > NOW() - make_interval(hours => ${f.hours})"
    val byMac = f.mac.fold(fr"")(m => fr"AND ce.mac = $m")
    val byDev = f.deviceId.fold(fr"")(id => fr"AND d.id = $id")
    val byPid = f.profileId.fold(fr"")(pid => fr"AND d.profile_id = $pid")
    val byBl  = f.blocked.fold(fr"")(b => fr"AND ce.allowed = ${!b}")
    val byDom = f.domain.fold(fr"")(d =>
      fr"AND COALESCE(ce.resolved_host_value, ce.host_value) ILIKE ${s"%$d%"}",
    )
    val byLoc = f.location.fold(fr"")(l => fr"AND r.name = $l")
    (base ++ since ++ byMac ++ byDev ++ byPid ++ byBl ++ byDom ++ byLoc ++
      fr"GROUP BY " ++ groupByCols ++
      // #846 audit: order by newest window first, then biggest count within
      // window — was sorting by total count only which scrambled the
      // chronology.
      fr"ORDER BY window_start DESC, COUNT(*) DESC LIMIT ${f.limit} OFFSET ${f.offset}")
      .query[
        (
            Option[String], // grp_domain
            Option[String], // grp_device
            Option[String], // grp_profile
            String,         // window_start
            Int,            // count_succeeded
            Int,            // count_blocked
            String,         // last_seen
            Option[String], // top_device
            Int,            // distinct_devices
            Int,            // distinct_profiles
            Int,            // distinct_domains
            Option[String], // sole_device   (null when distinct != 1)
            Option[String], // sole_profile
            Option[String], // sole_domain
        ),
      ]
      .map { case (gd, gv, gp, ws, sc, bl, ls, td, dd, dpr, dm, sde, spr, sdo) =>
        val groupMap = scala.collection.mutable.LinkedHashMap.empty[String, String]
        gd.foreach(v => groupMap += ("domain" -> v))
        gv.foreach(v => groupMap += ("device" -> v))
        gp.foreach(v => groupMap += ("profile" -> v))
        // Only surface sole* when the column is NOT in groupBy — when it IS,
        // the value is already in `groups`.
        ConnectionEventAggRow(
          groups = groupMap.toMap,
          windowStart = ws,
          countSucceeded = sc,
          countBlocked = bl,
          lastSeen = ls,
          topDevice = td,
          distinctDevices = dd,
          distinctProfiles = dpr,
          distinctDomains = dm,
          soleDevice = if (wantsDevice) None else sde,
          soleProfile = if (wantsProfile) None else spr,
          soleDomain = if (wantsDomain) None else sdo,
        )
      }
      .to[List]
      .transact(xa)
  }

  def stats =
    for {
      tt  <- sql"SELECT COUNT(*)::INT FROM connection_events WHERE ts > NOW()-INTERVAL '24 hours'"
        .query[Int]
        .unique
        .transact(xa)
      bt  <-
        sql"SELECT COUNT(*)::INT FROM connection_events WHERE ts > NOW()-INTERVAL '24 hours' AND NOT allowed"
          .query[Int]
          .unique
          .transact(xa)
      th  <- sql"SELECT COUNT(*)::INT FROM connection_events WHERE ts > NOW()-INTERVAL '1 hour'"
        .query[Int]
        .unique
        .transact(xa)
      bh  <-
        sql"SELECT COUNT(*)::INT FROM connection_events WHERE ts > NOW()-INTERVAL '1 hour' AND NOT allowed"
          .query[Int]
          .unique
          .transact(xa)
      top <- sql"""SELECT CASE WHEN resolved_host_value IS NOT NULL THEN 'fqdn' ELSE host_type END,
                          COALESCE(resolved_host_value, host_value),
                          COUNT(*)::INT
                   FROM connection_events
                   WHERE NOT allowed AND ts > NOW()-INTERVAL '24 hours'
                   GROUP BY 1, 2 ORDER BY COUNT(*) DESC LIMIT 10"""
        .query[(HostId, Int)]
        .map(DomainCount.apply)
        .to[List]
        .transact(xa)
      dev <- sql"""SELECT ce.mac::TEXT,
                          COALESCE(d.name, ce.mac),
                          COUNT(*)::INT,
                          SUM(CASE WHEN NOT ce.allowed THEN 1 ELSE 0 END)::INT
                   FROM connection_events ce
                   LEFT JOIN devices d ON d.mac = ce.mac
                   WHERE ce.ts > NOW()-INTERVAL '24 hours'
                     AND ce.mac IS NOT NULL
                   GROUP BY ce.mac, d.name
                   ORDER BY COUNT(*) DESC LIMIT 20"""
        .query[(MacAddress, String, Int, Int)]
        .map(DeviceStats.apply)
        .to[List]
        .transact(xa)
    } yield DashboardStats(tt, bt, th, bh, top, dev)

  def topBlocked(hours: Int, lim: Int) =
    sql"""SELECT CASE WHEN resolved_host_value IS NOT NULL THEN 'fqdn' ELSE host_type END,
                 COALESCE(resolved_host_value, host_value),
                 COUNT(*)::INT
          FROM connection_events
          WHERE NOT allowed AND ts > NOW() - make_interval(hours => $hours)
          GROUP BY 1, 2 ORDER BY COUNT(*) DESC LIMIT $lim"""
      .query[(HostId, Int)]
      .map(DomainCount.apply)
      .to[List]
      .transact(xa)

  def lastSeenByMacSince(since: Instant): Task[Map[MacAddress, Instant]] =
    sql"""SELECT mac, MAX(ts)
          FROM connection_events
          WHERE mac IS NOT NULL AND ts > $since
          GROUP BY mac"""
      .query[(MacAddress, Instant)]
      .to[List]
      .transact(xa)
      .map(_.toMap)
}

object Repos {
  val userRepo              = ZLayer.fromFunction(UserRepoLive(_))
  val userProfileRepo       = ZLayer.fromFunction(UserProfileRepoLive(_))
  val profileRepo           = ZLayer.fromFunction(ProfileRepoLive(_))
  val scheduleRepo          = ZLayer.fromFunction(ScheduleRepoLive(_))
  val householdSettingsRepo = ZLayer.fromFunction(HouseholdSettingsRepoLive(_))
  val timeLimitRepo         = ZLayer.fromFunction(TimeLimitRepoLive(_))
  val siteTimeLimitRepo     = ZLayer.fromFunction(SiteTimeLimitRepoLive(_))
  val deviceRepo            = ZLayer.fromFunction(DeviceRepoLive(_))
  val blocklistRepo         = ZLayer.fromFunction(BlocklistRepoLive(_))
  val timeUsageRepo         = ZLayer.fromFunction(TimeUsageRepoLive(_))
  val timeExtRepo           = ZLayer.fromFunction(TimeExtensionRepoLive(_))
  val routerRepo            = ZLayer.fromFunction(RouterRepoLive(_))
  val trafficReportRepo     = ZLayer.fromFunction(TrafficReportRepoLive(_))
  val blockEventRepo        = ZLayer.fromFunction(BlockEventRepoLive(_))
  val connEventRepo         = ZLayer.fromFunction(ConnectionEventRepoLive(_))
  val all                   =
    userRepo ++ userProfileRepo ++ profileRepo ++ scheduleRepo ++ householdSettingsRepo ++ timeLimitRepo ++ siteTimeLimitRepo ++ deviceRepo ++ blocklistRepo ++ timeUsageRepo ++ timeExtRepo ++ routerRepo ++ trafficReportRepo ++ blockEventRepo ++ connEventRepo
}
