-- render.lua — generates dnsmasq and nftables config from a policy snapshot
--
-- Snapshot field naming: the API serializes PolicySnapshot/DevicePolicy/
-- ProfilePolicy/BlockRules via zio-json deriveCodec, which keeps the Scala
-- case-class field names verbatim (camelCase) — see shared/src/Models.scala.
--
-- Snapshot shape (post-#354 — see docs/architecture.md §0.2):
--   snapshot.devices    table   mac -> { profileId, name, rules? }
--   snapshot.profiles   table   profileIdStr -> { name, rules, failureMode }
--   snapshot.blocklists table   id -> { version, url }
--
-- The agent never evaluates schedules / time limits / pause. Server has
-- already collapsed them into per-profile BlockRules.blocked.
--
-- Public API:
--   render.dnsmasq(snapshot)  → string  (/tmp/dnsmasq.d/familydns.conf content)
--   render.nft(snapshot, opts) → string (/tmp/nftables.d/familydns.nft content)
--   render.update_shared(snapshot, nft_sets, blocked_macs, blocked_reason)
--     Rebuilds blocked_macs / blocked_reason in place from per-MAC
--     effective rules. nft_sets is cleared of stale per-host entries that
--     have no current source; population is otherwise driven by dnsmasq
--     --ipset= callbacks and dns-tail (#259).

local M = {}

-- Replace dots and colons with underscores (nftables set/counter name-safe).
local function sanitize(s)
  return (s:gsub("[%.%:]", "_"))
end
M.sanitize = sanitize

-- Resolve a device's effective BlockRules. Returns the rules table or nil
-- if the device has no profile and no override (and therefore no rules
-- apply — caller must treat as "permitted").
local function effective_rules(dev, profiles)
  if dev == nil then return nil end
  -- JSON decoders represent `null` differently (cjson uses a userdata
  -- sentinel; luci.jsonc uses nil). Only treat a real table as an override.
  if type(dev.rules) == "table" then return dev.rules end
  if dev.profileId == nil then return nil end
  -- cjson decodes JSON integers as Lua *floats*, so a profileId of 3
  -- arrives as 3.0 and `tostring(3.0)` yields "3.0" on Lua 5.3+, missing
  -- the profiles["3"] key. Use %d formatting to coerce to an integer
  -- decimal representation that matches the JSON-object key shape.
  local key = string.format("%d", dev.profileId)
  local prof = profiles and profiles[key]
  if type(prof) ~= "table" then return nil end
  if type(prof.rules) ~= "table" then return nil end
  return prof.rules
end
M.effective_rules = effective_rules

-- Iterate the device map in a deterministic (mac-sorted) order. Many of
-- our nft set element lists and dnsmasq dhcp-host lines should be stable
-- across rerenders so the etag-equivalent on-disk content doesn't churn.
local function sorted_devices(devices)
  local keys = {}
  for mac, _ in pairs(devices or {}) do keys[#keys + 1] = mac end
  table.sort(keys)
  local i = 0
  return function()
    i = i + 1
    local mac = keys[i]
    if mac == nil then return nil end
    return mac, devices[mac]
  end
end

local function sorted_keys(tbl)
  local keys = {}
  for k, _ in pairs(tbl or {}) do keys[#keys + 1] = k end
  table.sort(keys)
  return keys
end

local function sorted_profiles(profiles)
  local keys = {}
  for pid, _ in pairs(profiles or {}) do keys[#keys + 1] = pid end
  table.sort(keys)
  local i = 0
  return function()
    i = i + 1
    local pid = keys[i]
    if pid == nil then return nil end
    return pid, profiles[pid]
  end
end

-- Build the set of hosts that appear in any device's *effective* extraBlocked
-- list. Hosts only referenced by a profile that has no assigned device are
-- skipped — no point populating an ipset that nothing will drop on. Returns
-- a sorted unique list of hostnames.
local function effective_extra_blocked_hosts(snapshot)
  local seen = {}
  for _, dev in pairs(snapshot.devices or {}) do
    local r = effective_rules(dev, snapshot.profiles)
    if r and type(r.extraBlocked) == "table" then
      for _, host in ipairs(r.extraBlocked) do seen[host] = true end
    end
  end
  local hosts = {}
  for h in pairs(seen) do hosts[#hosts + 1] = h end
  table.sort(hosts)
  return hosts
end

-- nft set name for an extraBlocked host. `eb_` prefix scopes against
-- categorical blocklists (#352 uses `bl_`).
local function eb_set_name(host)
  return "eb_" .. sanitize(host)
end

-- nft set name for a blocklist id (#352). Replaces dots, colons, and
-- hyphens with underscores (nftables set names allow only [a-zA-Z0-9_]).
local function bl_sanitize(id)
  return (id:gsub("[%.%:%-%s]", "_"))
end
local function bl_set_name(id)
  return "bl_" .. bl_sanitize(id)
end

-- ---------------------------------------------------------------------------
-- render.dnsmasq(snapshot) → string
-- ---------------------------------------------------------------------------
function M.dnsmasq(snapshot)
  local out = {}
  local function emit(s) out[#out + 1] = s end

  emit("# familydns — generated by render.lua, do not edit")
  emit("")

  -- MAC → profile tag so dnsmasq can apply per-profile tagged callbacks.
  -- Devices auto-created from first_seen_mac events have profileId=nil
  -- until an admin assigns them; skip them (no policy to apply yet).
  emit("# device MAC → profile tag")
  for mac, dev in sorted_devices(snapshot.devices) do
    if dev.profileId then
      emit(string.format("dhcp-host=%s,set:profile%d", mac, dev.profileId))
    end
  end
  emit("")

  -- #351: extraBlocked is enforced at the connection layer (per-MAC nft
  -- drop), not via DNS sinkhole. dnsmasq's only role here is to populate
  -- an nftables ipset with the resolved IPs of each blocked host, so the
  -- forward-hook drop can match by `ip daddr ∈ @eb_<host>`. DNS still
  -- resolves the host normally — see docs/architecture.md §0.1 (Truth 1).
  -- OpenWRT 23.05+ ships dnsmasq-full without HAVE_IPSET; the legacy
  -- ipset framework was dropped in favour of native nftables sets, so we
  -- emit `nftset=` and populate the per-host nft set in the `inet
  -- familydns` table directly. Syntax: nftset=/<host>/4#<family>#<table>#<set>.
  emit("# extraBlocked → per-host nftset populated at resolve time (#351)")
  for _, host in ipairs(effective_extra_blocked_hosts(snapshot)) do
    emit(string.format("nftset=/%s/4#inet#familydns#%s", host, eb_set_name(host)))
  end
  emit("")

  -- #352: category blocklists — populate bl_<id> ipsets at DNS resolve time.
  -- snapshot._blocklist_hosts = { [id] = {host1, host2, ...} } is populated
  -- by the agent before calling render (so tests can inject without filesystem).
  local bl_hosts = snapshot._blocklist_hosts or {}
  local bl_ids   = sorted_keys(snapshot.blocklists or {})
  if #bl_ids > 0 then
    emit("# blocklist ipsets → resolved at DNS time (#352)")
    for _, id in ipairs(bl_ids) do
      local hosts = bl_hosts[id] or {}
      local set_name = bl_set_name(id)
      for _, host in ipairs(hosts) do
        emit(string.format("ipset=/%s/%s", host, set_name))
      end
    end
    emit("")
  end

  return table.concat(out, "\n")
end

-- ---------------------------------------------------------------------------
-- render.nft(snapshot, opts) → string
-- ---------------------------------------------------------------------------
-- opts (optional table):
--   poll_age_seconds  number — seconds since the last successful policy poll.
--                              When > 300, the per-profile failureMode
--                              decides what happens (#385):
--                                "block-all"       → emit an additional drop
--                                                    rule for the profile's
--                                                    devices (fail-safe).
--                                "allow-all"       → suppress this profile's
--                                                    devices from
--                                                    @blocked_macs and from
--                                                    every per-(MAC, host)
--                                                    and per-(MAC,
--                                                    blocklistId) drop, and
--                                                    from the DNAT chain.
--                                                    Cached enforcement is
--                                                    erased for these MACs.
--                                "last-known-good" → no change. The profile's
--                                                    cached snapshot rules
--                                                    keep enforcing exactly
--                                                    as-is (this is the
--                                                    behaviour the original
--                                                    binary "open" had).
--                              Below the 5-minute threshold all profiles
--                              behave as LastKnownGood — the cached
--                              snapshot stands and no failover transition
--                              has happened yet.
function M.nft(snapshot, opts)
  local out = {}
  local function emit(s)  out[#out + 1] = s  end
  local function ind(s)   out[#out + 1] = "  " .. s  end
  local function ind2(s)  out[#out + 1] = "    " .. s end

  emit("# familydns — generated by render.lua, do not edit")
  emit("# Load with a single `nft -f <this file>`. The prelude below performs an")
  emit("# atomic handover from the boot default-deny skeleton (table inet")
  emit("# familydns_boot, installed by /etc/init.d/familydns-boot — see #308) to")
  emit("# the runtime table in one transaction.")
  emit("add table inet familydns_boot")
  emit("delete table inet familydns_boot")
  emit("add table inet familydns")
  emit("delete table inet familydns")
  emit("table inet familydns {")
  emit("")

  -- Build profileId → [macs] index for per-profile nft sets used by future
  -- per-MAC enforcement rules (#351/#352/#353). Skip unassigned devices.
  local profile_macs = {}
  for mac, dev in sorted_devices(snapshot.devices) do
    local pid = dev.profileId
    if pid then
      if not profile_macs[pid] then profile_macs[pid] = {} end
      profile_macs[pid][#profile_macs[pid] + 1] = mac
    end
  end

  -- #385: during failover (>5 min API-unreachable), an AllowAll profile's
  -- devices must NOT receive any drop rule — not the @blocked_macs
  -- entry, not the per-(MAC, host) eb_ drops, not the per-(MAC,
  -- blocklistId) bl_ drops, and not the block-page DNAT. The cached
  -- snapshot is intentionally discarded for these MACs (cf. LastKnownGood,
  -- where the cached snapshot keeps enforcing). Compute the suppress set
  -- once so every subsequent rule-emission step can filter cheaply.
  local poll_age = opts and opts.poll_age_seconds
  local in_failover = poll_age and poll_age > 300
  local allowall_macs = {}
  if in_failover then
    local allowall_pids = {}
    for pidStr, prof in pairs(snapshot.profiles or {}) do
      if prof.failureMode == "allow-all" then
        local pid = tonumber(pidStr)
        if pid then allowall_pids[pid] = true end
      end
    end
    for mac, dev in pairs(snapshot.devices or {}) do
      if dev.profileId and allowall_pids[dev.profileId] then
        allowall_macs[mac] = true
      end
    end
  end

  -- Per-profile MAC sets. Emit in numeric-id order for stable output.
  for pidStr, _ in sorted_profiles(snapshot.profiles) do
    local pid = tonumber(pidStr)
    local macs = (pid and profile_macs[pid]) or {}
    ind(string.format("set profile%d_macs {", pid or 0))
    ind2("type ether_addr")
    if #macs > 0 then
      ind2("elements = { " .. table.concat(macs, ", ") .. " }")
    end
    ind("}")
    emit("")
  end

  -- Per-flow accounting set.
  ind("set mac_ip_tracking {")
  ind2("type ether_addr . ipv4_addr")
  ind2("flags dynamic,timeout")
  ind2("timeout 6h")
  ind2("counter")
  ind("}")
  emit("")

  -- Accounting chain: forward hook, low priority; updates tracking set per packet.
  ind("chain familydns_account {")
  ind2("type filter hook forward priority 1; policy accept;")
  ind2("update @mac_ip_tracking { ether saddr . ip daddr } counter")
  ind("}")
  emit("")

  -- blocked_macs: derived from per-device effective rules. The API server
  -- precomputes BlockRules.blocked from pause / time limit / schedule, so
  -- we just collect MACs whose effective rules.blocked == true.
  local blocked_macs_list = {}
  for mac, dev in sorted_devices(snapshot.devices) do
    local r = effective_rules(dev, snapshot.profiles)
    if r and r.blocked and not allowall_macs[mac] then
      blocked_macs_list[#blocked_macs_list + 1] = mac
    end
  end

  ind("set blocked_macs {")
  ind2("type ether_addr")
  if #blocked_macs_list > 0 then
    ind2("elements = { " .. table.concat(blocked_macs_list, ", ") .. " }")
  end
  ind("}")
  emit("")

  -- #351: per-host ipsets for extraBlocked. Each set is populated at DNS
  -- resolve time by dnsmasq `ipset=/host/eb_<host>` (rendered by dnsmasq()
  -- above). Dynamic + 1h timeout so resolved entries age out and we don't
  -- leak shared-CDN IPs to other hosts indefinitely.
  local eb_hosts = effective_extra_blocked_hosts(snapshot)
  for _, host in ipairs(eb_hosts) do
    ind(string.format("set %s {", eb_set_name(host)))
    ind2("type ipv4_addr")
    ind2("flags dynamic,timeout")
    ind2("timeout 1h")
    ind("}")
    emit("")
  end

  -- #351: per-(MAC, host) drop pairs. We build the cross-product from each
  -- device's *effective* extraBlocked list (device override > profile rules),
  -- so a profile's extraBlocked applies only to MACs in that profile and a
  -- device override applies only to that one MAC.
  local eb_pairs = {}
  for mac, dev in sorted_devices(snapshot.devices) do
    if not allowall_macs[mac] then
      local r = effective_rules(dev, snapshot.profiles)
      if r and type(r.extraBlocked) == "table" then
        for _, host in ipairs(r.extraBlocked) do
          eb_pairs[#eb_pairs + 1] = { mac = mac, host = host }
        end
      end
    end
  end

  -- #352: per-blocklist ipsets. Declared for every id in snapshot.blocklists
  -- regardless of whether any device references the id, so the dnsmasq
  -- ipset= callbacks have a set to populate. Dynamic + 1h timeout.
  local bl_ids = sorted_keys(snapshot.blocklists or {})
  for _, id in ipairs(bl_ids) do
    ind(string.format("set %s {", bl_set_name(id)))
    ind2("type ipv4_addr")
    ind2("flags dynamic,timeout")
    ind2("timeout 1h")
    ind("}")
    emit("")
  end

  -- #352: per-(MAC, blocklistId) drop pairs. For each device, for each
  -- blocklistId in its effective rules, if the id is in snapshot.blocklists,
  -- emit a drop rule. Ids absent from snapshot.blocklists are silently skipped.
  local bl_pairs = {}
  for mac, dev in sorted_devices(snapshot.devices) do
    if not allowall_macs[mac] then
      local r = effective_rules(dev, snapshot.profiles)
      if r and type(r.blocklistIds) == "table" then
        for _, id in ipairs(r.blocklistIds) do
          if (snapshot.blocklists or {})[id] then
            bl_pairs[#bl_pairs + 1] = { mac = mac, id = id }
          end
        end
      end
    end
  end

  ind("chain familydns_block {")
  ind2("type filter hook forward priority 0; policy accept;")
  if #blocked_macs_list > 0 then
    ind2("ether saddr @blocked_macs drop")
  end
  for _, p in ipairs(eb_pairs) do
    ind2(string.format("ether saddr %s ip daddr @%s drop",
                       p.mac, eb_set_name(p.host)))
  end
  for _, p in ipairs(bl_pairs) do
    ind2(string.format("ether saddr %s ip daddr @%s drop",
                       p.mac, bl_set_name(p.id)))
  end
  ind("}")
  emit("")

  -- Block-page DNAT chain (#303 + #351 + #352): redirect HTTP/80 to the local
  -- uhttpd block page so users see *why* a connection failed. Three
  -- triggers: MAC-wide block, per-(MAC, host) extraBlocked, per-(MAC, blocklistId).
  -- We emit the chain if any applies.
  if #blocked_macs_list > 0 or #eb_pairs > 0 or #bl_pairs > 0 then
    ind("chain familydns_block_nat {")
    ind2("type nat hook prerouting priority dstnat; policy accept;")
    if #blocked_macs_list > 0 then
      ind2("ether saddr @blocked_macs tcp dport 80 dnat ip to 127.0.0.1:8081")
    end
    for _, p in ipairs(eb_pairs) do
      ind2(string.format(
        "ether saddr %s ip daddr @%s tcp dport 80 dnat ip to 127.0.0.1:8081",
        p.mac, eb_set_name(p.host)))
    end
    for _, p in ipairs(bl_pairs) do
      ind2(string.format(
        "ether saddr %s ip daddr @%s tcp dport 80 dnat ip to 127.0.0.1:8081",
        p.mac, bl_set_name(p.id)))
    end
    ind("}")
    emit("")
  end

  -- #385: API-unreachable failover. failureMode is per-profile (carried on
  -- ProfilePolicy) with three variants — see the opts.poll_age_seconds
  -- doc at the top of M.nft for the per-mode behaviour. This block only
  -- handles BlockAll: collect MACs of devices whose profile's failureMode
  -- is "block-all" and emit a drop chain for them. AllowAll is enforced
  -- by SUPPRESSION earlier in this function (allowall_macs gates the
  -- @blocked_macs / eb_pairs / bl_pairs lists, so AllowAll devices reach
  -- this point with zero drop rules attributed to them — exactly what
  -- "pass forwarded traffic with no enforcement" means). LastKnownGood
  -- is the no-op default: the cached snapshot's rules keep enforcing
  -- exactly as-is.
  if in_failover then
    local blockall_pids = {}
    for pidStr, prof in pairs(snapshot.profiles or {}) do
      if prof.failureMode == "block-all" then
        local pid = tonumber(pidStr)
        if pid then blockall_pids[pid] = true end
      end
    end
    local failover_macs = {}
    for mac, dev in sorted_devices(snapshot.devices) do
      if dev.profileId and blockall_pids[dev.profileId] then
        failover_macs[#failover_macs + 1] = mac
      end
    end
    if #failover_macs > 0 then
      ind("set failover_drop {")
      ind2("type ether_addr")
      ind2("elements = { " .. table.concat(failover_macs, ", ") .. " }")
      ind("}")
      emit("")
      ind("chain familydns_failover {")
      ind2("type filter hook forward priority -1; policy accept;")
      ind2("ether saddr @failover_drop drop")
      ind("}")
      emit("")
    end
  end

  emit("}")
  emit("")

  return table.concat(out, "\n")
end

-- ---------------------------------------------------------------------------
-- render.update_shared(snapshot, nft_sets, blocked_macs, blocked_reason)
-- ---------------------------------------------------------------------------
-- Rebuilds blocked_macs / blocked_reason in place from each device's
-- effective BlockRules. nft_sets is left intact — population is driven by
-- dnsmasq --ipset= callbacks at resolution time (and by dns-tail per #259).
function M.update_shared(snapshot, nft_sets, blocked_macs, blocked_reason)
  if blocked_macs then
    for k in pairs(blocked_macs) do blocked_macs[k] = nil end
  end
  if blocked_reason then
    for k in pairs(blocked_reason) do blocked_reason[k] = nil end
  end

  for mac, dev in pairs(snapshot.devices or {}) do
    local r = effective_rules(dev, snapshot.profiles)
    if r and r.blocked then
      if blocked_macs   then blocked_macs[mac]   = true end
      if blocked_reason then blocked_reason[mac] = r.blockReason or "blocked" end
    end
  end
end

return M
