-- render.lua — generates dnsmasq and nftables config from a policy snapshot
--
-- Snapshot field naming: the API serializes PolicySnapshot/PolicyProfile/
-- PolicyDevice via zio-json deriveCodec, which keeps the Scala case-class
-- field names verbatim (camelCase) — see shared/src/Models.scala. This module
-- reads those keys (profileId, extraBlocked, siteLimits, dailyMinutes,
-- timeUsedToday.totalMinutes, extensionsTodayMinutes) directly. If the API's
-- JSON casing ever changes, change it here too (and update render_spec.lua).
--
-- Public API:
--   render.dnsmasq(snapshot)  → string  (/tmp/dnsmasq.d/familydns.conf content)
--   render.nft(snapshot)      → string  (/tmp/nftables.d/familydns.nft content)
--   render.update_shared(snapshot, nft_sets, blocked_macs, blocked_reason)
--     Seeds the shared tables that conntrack.lua uses for hostname attribution
--     and for labeling per-MAC blocked flows (pause / time-exhausted).
--
-- Counter naming convention (used by usage.lua):
--   ct_<mac_underscored>__<dst_ip_underscored>
--   e.g.  aa:bb:cc:11:22:33 + 1.2.3.4  →  ct_aa_bb_cc_11_22_33__1_2_3_4
--   The double-underscore (__) separates MAC from IP unambiguously.

local M = {}

-- Replace dots and colons with underscores (nftables set/counter name-safe).
local function sanitize(s)
  return (s:gsub("[%.%:]", "_"))
end
M.sanitize = sanitize

-- ---------------------------------------------------------------------------
-- render.dnsmasq(snapshot) → string
-- ---------------------------------------------------------------------------
function M.dnsmasq(snapshot)
  local out = {}
  local function emit(s) out[#out + 1] = s end

  emit("# familydns — generated by render.lua, do not edit")
  emit("")

  -- #259: query logging is enabled via UCI (`option logqueries '1'`,
  -- `option logfacility '/tmp/familydns-dnsmasq.log'`) so OpenWRT's dnsmasq
  -- init script knows to bind-mount the log file RW into dnsmasq's ujail.
  -- Emitting it here too would trip dnsmasq's "illegal repeated keyword"
  -- check (#287).

  -- MAC → profile tag so dnsmasq can apply per-profile rules.
  -- Devices auto-created from first_seen_mac events have profileId=nil
  -- until an admin assigns them; skip them (no policy to apply yet).
  emit("# device MAC → profile tag")
  for _, dev in ipairs(snapshot.devices or {}) do
    if dev.profileId then
      emit(string.format("dhcp-host=%s,set:profile%d", dev.mac, dev.profileId))
    end
  end
  emit("")

  -- extraBlocked → NXDOMAIN; deduplicate domains that appear in multiple profiles
  emit("# extraBlocked → NXDOMAIN")
  local seen_blocked = {}
  for _, prof in ipairs(snapshot.profiles or {}) do
    for _, domain in ipairs(prof.extraBlocked or {}) do
      if not seen_blocked[domain] then
        seen_blocked[domain] = true
        emit("address=/" .. domain .. "/#")
      end
    end
  end
  emit("")

  -- siteLimits → ipset= so dnsmasq populates nftables sets with resolved IPs
  emit("# siteLimits → nftables ipset population for usage accounting")
  for _, prof in ipairs(snapshot.profiles or {}) do
    for _, sl in ipairs(prof.siteLimits or {}) do
      local set_name = string.format("profile%d_%s", prof.id, sanitize(sl.domain))
      emit(string.format("ipset=/%s/%s", sl.domain, set_name))
    end
  end
  emit("")

  return table.concat(out, "\n")
end

-- ---------------------------------------------------------------------------
-- render.nft(snapshot) → string
-- ---------------------------------------------------------------------------
function M.nft(snapshot)
  local out = {}
  local function emit(s)  out[#out + 1] = s  end
  local function ind(s)   out[#out + 1] = "  " .. s  end
  local function ind2(s)  out[#out + 1] = "    " .. s end

  emit("# familydns — generated by render.lua, do not edit")
  emit("# Load with: nft delete table inet familydns 2>/dev/null; nft -f <this file>")
  emit("table inet familydns {")
  emit("")

  -- Build profileId → [macs] index. Skip unassigned devices (profileId=nil);
  -- they have no profile to be matched against in the nft sets.
  local profile_macs = {}
  for _, dev in ipairs(snapshot.devices or {}) do
    local pid = dev.profileId
    if pid then
      if not profile_macs[pid] then profile_macs[pid] = {} end
      profile_macs[pid][#profile_macs[pid] + 1] = dev.mac
    end
  end

  -- Per-profile MAC sets
  for _, prof in ipairs(snapshot.profiles or {}) do
    local macs = profile_macs[prof.id] or {}
    ind(string.format("set profile%d_macs {", prof.id))
    ind2("type ether_addr")
    if #macs > 0 then
      ind2("elements = { " .. table.concat(macs, ", ") .. " }")
    end
    ind("}")
    emit("")
  end

  -- Per-domain IP sets for siteLimits (dynamic: populated by dnsmasq --ipset= at query time)
  for _, prof in ipairs(snapshot.profiles or {}) do
    for _, sl in ipairs(prof.siteLimits or {}) do
      local set_name = string.format("profile%d_%s", prof.id, sanitize(sl.domain))
      ind(string.format("set %s {", set_name))
      ind2("type ipv4_addr")
      ind2("flags dynamic,timeout")
      ind2("timeout 1h")
      ind("}")
      emit("")
    end
  end

  -- Per-flow accounting set (conntrack.lua adds rules referencing named counters;
  -- this set is also used as a fallback for byte accounting via dynamic population)
  ind("set mac_ip_tracking {")
  ind2("type ether_addr . ipv4_addr")
  ind2("flags dynamic,timeout")
  ind2("timeout 6h")
  ind2("counter")
  ind("}")
  emit("")

  -- Accounting chain: forward hook, low priority; updates tracking set per packet
  ind("chain familydns_account {")
  ind2("type filter hook forward priority 1; policy accept;")
  ind2("update @mac_ip_tracking { ether saddr . ip daddr } counter")
  ind("}")
  emit("")

  -- Block chain: drop/redirect for exhausted time limits, paused profiles, schedules
  ind("chain familydns_block {")
  ind2("type filter hook forward priority 0; policy accept;")
  emit("")

  for _, prof in ipairs(snapshot.profiles or {}) do
    local block_reason = nil

    if prof.paused then
      block_reason = "paused"
    elseif (prof.dailyMinutes or 0) > 0 then
      local used       = (prof.timeUsedToday and prof.timeUsedToday.totalMinutes) or 0
      local extensions = prof.extensionsTodayMinutes or 0
      local remaining  = prof.dailyMinutes + extensions - used
      if remaining <= 0 then
        block_reason = "time_limit"
      end
    end

    if block_reason then
      ind2(string.format("# profile %d (%s): %s", prof.id, prof.name, block_reason))
      -- Drop all forwarded traffic from devices on this profile. DNAT to a
      -- block page would be nicer UX but needs a separate nat-type chain
      -- (DNAT is not supported in filter chains), and the bare `dnat to`
      -- form rejected `nft -f` entirely (#297) — so until we wire up a
      -- prerouting nat chain, we just drop.
      ind2(string.format("ether saddr @profile%d_macs drop", prof.id))
      emit("")
    end
  end

  ind("}")
  emit("")
  emit("}")
  emit("")

  return table.concat(out, "\n")
end

-- ---------------------------------------------------------------------------
-- render.update_shared(snapshot, nft_sets, blocked_macs, blocked_reason)
-- ---------------------------------------------------------------------------
-- Seeds nft_sets with empty tables for each siteLimits domain so that
-- conntrack.lua can attribute hostnames from the moment the agent starts.
-- Actual IPs are populated at runtime by dnsmasq --ipset= callbacks.
--
-- Also rebuilds blocked_macs / blocked_reason from the current snapshot so
-- conntrack.lua can label connection_attempt events as blocked when the
-- device's profile is paused or has exhausted its daily time (#297). nft
-- already drops these flows at the forward hook, but the conntrack -E -e NEW
-- watcher still sees the SYN_SENT entry and needs an independent signal to
-- classify it correctly — labeling purely by destination IP misses pause
-- (every IP is blocked) and time-limit (same).
--
-- Both tables are mutated in place (shared refs held by conntrack.lua); we
-- clear stale entries first so a profile that un-pauses stops marking flows
-- as blocked on the next poll.
function M.update_shared(snapshot, nft_sets, blocked_macs, blocked_reason)
  for _, prof in ipairs(snapshot.profiles or {}) do
    for _, sl in ipairs(prof.siteLimits or {}) do
      if not nft_sets[sl.domain] then
        nft_sets[sl.domain] = {}
      end
    end
  end

  if blocked_macs then
    for k in pairs(blocked_macs) do blocked_macs[k] = nil end
  end
  if blocked_reason then
    for k in pairs(blocked_reason) do blocked_reason[k] = nil end
  end

  local profile_block = {}
  for _, prof in ipairs(snapshot.profiles or {}) do
    local reason
    if prof.paused then
      reason = "paused"
    elseif (prof.dailyMinutes or 0) > 0 then
      local used = (prof.timeUsedToday and prof.timeUsedToday.totalMinutes) or 0
      local ext  = prof.extensionsTodayMinutes or 0
      if used >= prof.dailyMinutes + ext then
        reason = "time_limit"
      end
    end
    if reason then profile_block[prof.id] = reason end
  end

  for _, dev in ipairs(snapshot.devices or {}) do
    local pid    = dev.profileId
    local reason = pid and profile_block[pid] or nil
    if reason then
      if blocked_macs   then blocked_macs[dev.mac]   = true end
      if blocked_reason then blocked_reason[dev.mac] = reason end
    end
  end
end

return M
