package wifihaven.shared.contract

import wifihaven.shared.*
import zio.*
import zio.json.*
import zio.test.*
import zio.test.Assertion.*

import java.nio.file.{Files, Path, Paths}

/**
 * Bidirectional contract tests (#634). Two halves:
 *
 *   1. API → router: serialize representative response payloads via the production zio-json codecs,
 *      golden them under `shared/contract/api-to-router/`. The router-side lua spec
 *      (`openwrt/test/contract_spec.lua`) consumes these via `luci.jsonc` and asserts render.lua +
 *      the policy fetcher digest each field.
 *
 * 2. Router → API: load hand-curated samples of what the agent actually sends (under
 * `shared/contract/router-to-api/`), decode each through the production decoder, and assert the
 * decoded value re-serializes to a JSON shape equivalent to the input (no fields dropped, no silent
 * fallback to defaults).
 *
 * To regenerate the API-to-router fixtures after an intentional codec change, set
 * WIFIHAVEN_REGEN_CONTRACT=1 (or run `scripts/regen-contract-fixtures.sh`).
 */
object ContractGoldenSpec extends ZIOSpecDefault {

  private val contractDir: Path = locateContractDir()

  private def locateContractDir(): Path = {
    // Walk up from cwd until we find a directory containing `shared/contract`.
    // Mill normally runs tests with cwd = workspace root, but `out/...` dirs
    // can shift this depending on test isolation settings.
    val start = Paths.get(sys.props.getOrElse("user.dir", "."))
    var cur   = start.toAbsolutePath
    while (cur != null) {
      val cand = cur.resolve("shared/contract")
      if (Files.isDirectory(cand)) return cand
      cur = cur.getParent
    }
    sys.error(s"could not locate shared/contract from user.dir=$start")
  }

  private val regenerate: Boolean =
    sys.env.get("WIFIHAVEN_REGEN_CONTRACT").exists(v => v == "1" || v.equalsIgnoreCase("true"))

  // ── Helpers ──────────────────────────────────────────────────────────────

  private def readFixture(rel: String): String =
    new String(
      Files.readAllBytes(contractDir.resolve(rel)),
      java.nio.charset.StandardCharsets.UTF_8,
    )

  private def writeFixture(rel: String, body: String): Unit = {
    val p = contractDir.resolve(rel)
    Files.createDirectories(p.getParent)
    val _ = Files.writeString(p, body)
  }

  /** Normalize JSON for a structural compare that ignores whitespace + key order. */
  private def normalize(json: String): Either[String, String] =
    json.fromJson[ast.Json].map(_.toJson)

  private def assertGoldenMatches(rel: String, generated: String): TestResult = {
    if (regenerate) {
      writeFixture(rel, generated)
      assertCompletes
    } else {
      val expected = readFixture(rel)
      // Compare structurally so trivial formatting drift (line breaks, key
      // order) doesn't break the test, while real shape changes still do.
      val cmp      = for {
        e <- normalize(expected)
        g <- normalize(generated)
      } yield (e, g)
      cmp match {
        case Right((e, g)) if e == g => assertCompletes
        case Right((e, g))           =>
          assert(g)(equalTo(e)) ?? s"$rel mismatch (regenerate with WIFIHAVEN_REGEN_CONTRACT=1)"
        case Left(err)               =>
          assert(err)(isNull) ?? s"$rel JSON parse failure: $err"
      }
    }
  }

  /**
   * For router→API: decode the fixture via the production decoder, re-encode via the production
   * encoder, and assert the re-encoded JSON is structurally equal to the input. This catches:
   *   - codec drops a field (re-encode would be missing it)
   *   - codec falls back to a default (re-encode shows the default value where the input had
   *     something different — caught by structural diff)
   *   - codec renames the wire field (decode fails outright)
   */
  private def assertRoundTrip[A: JsonCodec](rel: String): TestResult = {
    val raw     = readFixture(rel)
    val decoded = raw.fromJson[A]
    decoded match {
      case Left(err)    =>
        assert(err)(isNull) ?? s"$rel decode failed: $err"
      case Right(value) =>
        val reEncoded = value.toJson
        val cmp       = for {
          inJ  <- normalize(raw)
          outJ <- normalize(reEncoded)
        } yield (inJ, outJ)
        cmp match {
          case Right((inJ, outJ)) if inJ == outJ => assertCompletes
          case Right((inJ, outJ))                =>
            assert(outJ)(equalTo(inJ)) ??
              s"$rel round-trip differs (codec dropped or defaulted a field?)"
          case Left(err)                         =>
            assert(err)(isNull) ?? s"$rel normalize failed: $err"
        }
    }
  }

  /**
   * Value-level round-trip, for fixtures whose genuine production bytes can't be byte-compared
   * against zio-json's re-encode (#1367).
   *
   * The router→API metrics fixture is byte-generated by the production encoder (luci.jsonc), so it
   * carries the REAL wire shape: a label-less series OMITS `labels` (luci.jsonc renders an empty
   * Lua table as `[]`, which the `Map[String,String]` decoder rejects, so the agent never emits
   * one), and whole-number `Double` fields render as `N` while fractional ones render at full
   * `%.17g` precision (`0.82` → `0.81999999999999995`). zio-json re-encodes the decoded value
   * differently — empty `Map` → `{}`, `Double` → shortest form (`0.82`, `880.0`) — so a structural
   * byte compare would flag those as false "defaulted field" diffs even though nothing was dropped.
   *
   * So we assert the invariant that actually matters: the genuine bytes DECODE (this is the guard
   * that catches the #1365 class — a `labels:[]` / wrong-typed value fails decode outright), and
   * decode→encode→decode is a fixed point at the VALUE level (no field silently lost across a
   * re-encode). Scoped to this one case; the other three fixtures keep the stricter byte
   * round-trip.
   */
  private def assertValueRoundTrip[A: JsonCodec](rel: String): TestResult = {
    val raw = readFixture(rel)
    raw.fromJson[A] match {
      case Left(err) =>
        assert(err)(isNull) ?? s"$rel decode failed: $err"
      case Right(v1) =>
        v1.toJson.fromJson[A] match {
          case Left(err) =>
            assert(err)(isNull) ?? s"$rel re-encoded JSON failed to decode: $err"
          case Right(v2) =>
            assert(v2)(equalTo(v1)) ??
              s"$rel value round-trip differs (codec dropped or defaulted a field?)"
        }
    }
  }

  // ── Spec ─────────────────────────────────────────────────────────────────

  def spec = suite("bidirectional contract (#634)")(
    suite("API → router (golden serialized via production codecs)")(
      test("policy_snapshot.json") {
        assertGoldenMatches(
          "api-to-router/policy_snapshot.json",
          ContractFixtures.pretty(ContractFixtures.policySnapshot),
        )
      },
    ),
    suite("router → API (decode hand-curated samples through production decoders)")(
      test("router_events_request.json decodes round-trip-clean") {
        assertRoundTrip[RouterEventsRequest]("router-to-api/router_events_request.json")
      },
      test("usage_report.json decodes round-trip-clean") {
        assertRoundTrip[UsageReport]("router-to-api/usage_report.json")
      },
      test("register_router_request.json decodes round-trip-clean") {
        assertRoundTrip[RegisterRouterRequest]("router-to-api/register_router_request.json")
      },
      test("router_metrics_batch.json decodes round-trip-clean") {
        // Value-level (not byte) compare: the fixture carries genuine luci.jsonc bytes
        // (omitted empty labels, whole Doubles as `N`, full-precision fractionals) which
        // zio-json re-encodes differently. See assertValueRoundTrip (#1367).
        assertValueRoundTrip[RouterMetricsBatch]("router-to-api/router_metrics_batch.json")
      },
      test("a series with labels:[] (the #1365 wire bug) is REJECTED by the decoder") {
        // This is the shape real luci.jsonc produces for `labels = {}` (empty Lua table → `[]`).
        // The decoder MUST reject it — that rejection is what makes the genuine-byte metrics
        // fixture a regression guard: if build_batch ever emits an empty `labels` again, the
        // faithful generator writes `"labels":[]` and this decode fails. (#1367)
        val malformed =
          """{"routerId":"r","agentVersion":"0.3.1","agentStartedAt":"t","sampledAt":"t",
            |"gauges":[{"name":"agent_uptime_seconds","labels":[],"value":1}]}""".stripMargin
        assert(malformed.fromJson[RouterMetricsBatch])(isLeft)
      },
    ),
  )
}
