package wifihaven.shared.contract

import wifihaven.shared.*
import wifihaven.shared.types.*
import zio.json.*

/**
 * Representative payloads for bidirectional contract tests (#634).
 *
 * These are constructed via the *production* zio-json codecs (see Models.scala `derives
 * JsonCodec`). Renaming a wire field in Models.scala flips the generated JSON and trips the
 * consumer-side parser tests.
 *
 * Keep these vivid: every optional field should appear set in at least one fixture so a "field
 * accidentally dropped from the codec" regression is caught regardless of which fixture the
 * consumer loads.
 */
object ContractFixtures {

  // ── API → router fixtures ────────────────────────────────────────────────

  /**
   * Policy snapshot — the central API→router surface (#297/#302/#354). Exercises:
   *   - devices: per-MAC override rules (rules != null) AND profile-resolved rules (rules == null)
   *   - profiles: every BlockRules field populated incl. blockReason and blockIpOnly
   *   - blocklists: at least one entry with version + url
   *   - failureMode: all three variants represented across the profile set
   */
  val policySnapshot: PolicySnapshot = {
    val macKid     = MacAddress.parse("aa:bb:cc:11:22:33").toOption.get
    val macAdult   = MacAddress.parse("de:ad:be:ef:00:01").toOption.get
    val macBlocked = MacAddress.parse("12:34:56:78:9a:bc").toOption.get
    val kidsPid    = ProfileId(3L)
    val adultsPid  = ProfileId(4L)
    val adsList    = BlocklistId.parse("ads").toOption.get
    val adultList  = BlocklistId.parse("adult").toOption.get
    val tiktok     = Hostname.parse("tiktok.com").toOption.get
    val khan       = Hostname.parse("khanacademy.org").toOption.get

    PolicySnapshot(
      etag = ETag.unsafe("\"sha256:abc123def4567890\""),
      generatedAt = "2026-05-17T14:00:00Z",
      devices = Map(
        macKid     -> DevicePolicy(
          profileId = Some(kidsPid),
          name = "kid-ipad",
          rules = None, // resolves to profiles["3"].rules
        ),
        macAdult   -> DevicePolicy(
          profileId = Some(adultsPid),
          name = "parent-phone",
          rules = None,
        ),
        macBlocked -> DevicePolicy(
          profileId = None,
          name = "unknown-device",
          rules = Some(
            BlockRules(
              blocked = true,
              blockReason = Some(MacBlockReason.Unmanaged),
              extraBlocked = Nil,
              extraAllowed = List(Hostname.parse("school.example.org").toOption.get),
              blocklistIds = Nil,
              blockIpOnly = false,
            ),
          ),
        ),
      ),
      profiles = Map(
        kidsPid   -> ProfilePolicy(
          name = "kids",
          rules = BlockRules(
            blocked = false,
            blockReason = None,
            extraBlocked = List(tiktok),
            extraAllowed = List(khan),
            blocklistIds = List(adsList, adultList),
            blockIpOnly = false,
          ),
          failureMode = FailureMode.BlockAll,
        ),
        adultsPid -> ProfilePolicy(
          name = "adults",
          rules = BlockRules(
            blocked = false,
            blockReason = None,
            extraBlocked = Nil,
            extraAllowed = Nil,
            blocklistIds = List(adsList),
            blockIpOnly = true,
          ),
          failureMode = FailureMode.LastKnownGood,
        ),
      ),
      blocklists = Map(
        adsList   -> Blocklist(
          version = BlocklistVersion.unsafe("2026.05.01"),
          url = BlocklistUrl.unsafe("/api/blocklists/ads"),
        ),
        adultList -> Blocklist(
          version = BlocklistVersion.unsafe("2026.05.01"),
          url = BlocklistUrl.unsafe("https://example.org/lists/adult.txt"),
        ),
      ),
      // #1307: global infra allowlist the whole-MAC block path never drops.
      infraAllow = List(
        Hostname.parse("connectivitycheck.gstatic.com").toOption.get,
        Hostname.parse("g.aaplimg.com").toOption.get,
      ),
    )
  }

  // ── Router → API fixtures ────────────────────────────────────────────────
  //
  // NOTE: The router → API fixtures (`shared/contract/router-to-api/*.json`)
  // are NOT generated from this file — they are generated by the OpenWRT
  // agent's own production POST-body builders in
  // `openwrt/test/contract_gen.lua`. This is deliberate: if the lua agent
  // silently changes what it sends, regenerating from Scala would mask the
  // drift. By generating from the producer, any router-side wire change
  // shows up as a diff in `shared/contract/router-to-api/*.json` and trips
  // ContractGoldenSpec's round-trip decoder.
  //
  // (`register_router_request.json` is a documented exception: the actual
  // producer is `openwrt/install.sh`'s shell `printf`, not lua. See
  // shared/contract/README.md.)

  // ── Pretty-printed JSON for golden files ────────────────────────────────

  def pretty[A: JsonEncoder](a: A): String = a.toJsonPretty + "\n"

  val apiToRouter: List[(String, String)] = List(
    "policy_snapshot.json" -> pretty(policySnapshot),
  )
}
