-- Tests for openwrt/files/usr/lib/lua/wifihaven/nflog.lua (#1122)
--
-- The nflog tail synthesizes connection_attempt events for forward-drop
-- flows that the conntrack -E NEW path cannot see (forward-chain drops
-- never reach the postrouting confirm hook, so they never emit IPCT_NEW).
-- Every per-MAC drop rule emitted by render.lua now carries
--   log group 1 counter drop comment "wh_drop:<mac>:<reason>"
-- and the agent tails the resulting nflog stream + posts allowed=false
-- events.

local nflog = require("nflog")

describe("nflog.parse_line", function()

  -- Sample line shape based on what kernel-level nflog netlink consumers
  -- (ulogd, nft monitor trace) emit when an `iptables-LOG`-style record
  -- is generated by `log group N`. The exact framing varies by consumer;
  -- the parser is robust to leading kernel-log fluff before the
  -- `wh_drop:` token and to KEY=value field order after it.
  it("extracts mac, reason, src_ip, dst_ip from a typical nflog line", function()
    local line = "[12345.678] wh_drop:aa:bb:cc:11:22:33:Paused IN=br-lan OUT=eth0 " ..
                 "MAC=11:22:33:44:55:66:aa:bb:cc:11:22:33:08:00 " ..
                 "SRC=192.168.1.42 DST=1.2.3.4 LEN=60 PROTO=TCP SPT=54321 DPT=443"
    local ev = nflog.parse_line(line)
    assert.is_not_nil(ev)
    assert.equal("aa:bb:cc:11:22:33", ev.mac)
    assert.equal("Paused",            ev.reason)
    assert.equal("192.168.1.42",      ev.src_ip)
    assert.equal("1.2.3.4",           ev.dst_ip)
  end)

  it("parses every MacBlockReason value", function()
    for _, reason in ipairs({ "Paused", "Schedule", "TimeLimit", "Manual", "Unmanaged" }) do
      local line = "wh_drop:de:ad:be:ef:00:01:" .. reason ..
                   " SRC=10.0.0.5 DST=8.8.8.8 PROTO=UDP DPT=53"
      local ev = nflog.parse_line(line)
      assert.is_not_nil(ev, "expected to parse reason=" .. reason)
      assert.equal(reason, ev.reason)
      assert.equal("de:ad:be:ef:00:01", ev.mac)
    end
  end)

  it("parses the per-host (eb_) drop reason `host`", function()
    local line = "wh_drop:aa:bb:cc:11:22:33:host " ..
                 "SRC=192.168.1.42 DST=1.2.3.4 PROTO=TCP DPT=443"
    local ev = nflog.parse_line(line)
    assert.is_not_nil(ev)
    assert.equal("host", ev.reason)
  end)

  it("parses the per-category (bl_) drop reason `category:<id>`", function()
    local line = "wh_drop:aa:bb:cc:11:22:33:category:ads " ..
                 "SRC=192.168.1.42 DST=1.2.3.4 PROTO=TCP DPT=443"
    local ev = nflog.parse_line(line)
    assert.is_not_nil(ev)
    assert.equal("category:ads", ev.reason)
  end)

  it("parses the blockIpOnly drop reason `ip_only`", function()
    local line = "wh_drop:aa:bb:cc:11:22:33:ip_only " ..
                 "SRC=192.168.1.42 DST=1.2.3.4 PROTO=TCP DPT=443"
    local ev = nflog.parse_line(line)
    assert.is_not_nil(ev)
    assert.equal("ip_only", ev.reason)
  end)

  it("returns nil for a line missing the wh_drop: token", function()
    local ev = nflog.parse_line("some unrelated syslog line about cron")
    assert.is_nil(ev)
  end)

  it("returns nil when SRC/DST are missing (incomplete kernel log)", function()
    local line = "wh_drop:aa:bb:cc:11:22:33:Paused PROTO=TCP DPT=443"
    local ev = nflog.parse_line(line)
    assert.is_nil(ev)
  end)
end)

describe("nflog.build_event", function()
  it("builds a connection_attempt with allowed=false and the parsed reason", function()
    local ev = nflog.build_event({
      mac      = "aa:bb:cc:11:22:33",
      dst_ip   = "1.2.3.4",
      hostname = "youtube.com",
      reason   = "Paused",
      ts       = "2026-05-27T12:00:00Z",
    })
    assert.equal("connection_attempt", ev["type"])
    assert.equal("aa:bb:cc:11:22:33",  ev.mac)
    assert.equal(false,                ev.allowed)
    assert.equal("Paused",             ev.reason)
    assert.equal("1.2.3.4",            ev.destIp)
    assert.equal("2026-05-27T12:00:00Z", ev.ts)
    assert.same({ type = "fqdn", value = "youtube.com" }, ev.host)
  end)

  it("falls back to ipv4 host tag when hostname is nil", function()
    local ev = nflog.build_event({
      mac    = "aa:bb:cc:11:22:33",
      dst_ip = "1.2.3.4",
      reason = "TimeLimit",
      ts     = "2026-05-27T12:00:00Z",
    })
    assert.same({ type = "ipv4", value = "1.2.3.4" }, ev.host)
  end)

  it("falls back to ipv6 host tag when dst_ip contains a colon", function()
    local ev = nflog.build_event({
      mac    = "aa:bb:cc:11:22:33",
      dst_ip = "2001:db8::1",
      reason = "Schedule",
      ts     = "2026-05-27T12:00:00Z",
    })
    assert.same({ type = "ipv6", value = "2001:db8::1" }, ev.host)
  end)
end)

describe("nflog.new_dedup", function()
  it("suppresses a duplicate (mac, dst_ip, hname) within the window", function()
    local now    = 1000
    local dedup  = nflog.new_dedup({ window_seconds = 10, now_fn = function() return now end })
    assert.is_true(dedup.allow("aa:bb:cc:11:22:33", "1.2.3.4", "youtube.com"))
    -- Same key inside the window → suppress.
    assert.is_false(dedup.allow("aa:bb:cc:11:22:33", "1.2.3.4", "youtube.com"))
    -- Different dst_ip → allowed.
    assert.is_true(dedup.allow("aa:bb:cc:11:22:33", "5.6.7.8", "youtube.com"))
    -- Same key but window has elapsed → allowed.
    now = now + 11
    assert.is_true(dedup.allow("aa:bb:cc:11:22:33", "1.2.3.4", "youtube.com"))
  end)

  it("treats nil hostname as its own bucket distinct from an attributed hostname", function()
    local now   = 1000
    local dedup = nflog.new_dedup({ window_seconds = 10, now_fn = function() return now end })
    assert.is_true(dedup.allow("aa:bb:cc:11:22:33", "1.2.3.4", nil))
    assert.is_false(dedup.allow("aa:bb:cc:11:22:33", "1.2.3.4", nil))
    -- Same flow once attribution arrives — counted again because the key changed.
    assert.is_true(dedup.allow("aa:bb:cc:11:22:33", "1.2.3.4", "youtube.com"))
  end)
end)

describe("nflog.run (end-to-end with injected reader + batcher)", function()
  it("feeds parsed events into the batcher, deduped per (mac, dst_ip, hname)", function()
    local lines = {
      "wh_drop:aa:bb:cc:11:22:33:Paused SRC=192.168.1.42 DST=1.2.3.4 PROTO=TCP DPT=443",
      -- duplicate within the window — should be suppressed
      "wh_drop:aa:bb:cc:11:22:33:Paused SRC=192.168.1.42 DST=1.2.3.4 PROTO=TCP DPT=443",
      "wh_drop:aa:bb:cc:11:22:33:Paused SRC=192.168.1.42 DST=5.6.7.8 PROTO=TCP DPT=443",
      "an unrelated syslog line",
      "wh_drop:de:ad:be:ef:00:01:Unmanaged SRC=192.168.1.99 DST=9.9.9.9 PROTO=UDP DPT=53",
    }
    local i = 0
    local read_fn = function()
      i = i + 1
      return lines[i]
    end
    local batched = {}
    local batcher = { add = function(_, ev) end }
    batcher.add = function(ev) batched[#batched + 1] = ev end

    nflog.run({
      read_fn        = read_fn,
      batcher        = batcher,
      now_fn         = function() return 1000 end,
      ts_fn          = function() return "2026-05-27T12:00:00Z" end,
      lookup_hostname = function(_) return nil end,
      window_seconds = 60,
    })

    assert.equal(3, #batched)
    assert.equal("aa:bb:cc:11:22:33", batched[1].mac)
    assert.equal(false,               batched[1].allowed)
    assert.equal("Paused",            batched[1].reason)
    assert.equal("1.2.3.4",           batched[1].destIp)
    assert.equal("5.6.7.8",           batched[2].destIp)
    assert.equal("de:ad:be:ef:00:01", batched[3].mac)
    assert.equal("Unmanaged",         batched[3].reason)
  end)

  it("attributes hostname via the injected lookup", function()
    local lines = {
      "wh_drop:aa:bb:cc:11:22:33:Paused SRC=192.168.1.42 DST=1.2.3.4 PROTO=TCP DPT=443",
    }
    local i = 0
    local read_fn = function() i = i + 1; return lines[i] end
    local batched = {}
    nflog.run({
      read_fn = read_fn,
      batcher = { add = function(ev) batched[#batched + 1] = ev end },
      now_fn  = function() return 1000 end,
      ts_fn   = function() return "2026-05-27T12:00:00Z" end,
      lookup_hostname = function(ip)
        if ip == "1.2.3.4" then return "youtube.com" end
        return nil
      end,
      window_seconds = 60,
    })
    assert.equal(1, #batched)
    assert.same({ type = "fqdn", value = "youtube.com" }, batched[1].host)
  end)
end)
