-- Tests for openwrt/files/usr/lib/lua/wifihaven/nflog.lua (#1122)
--
-- The nflog tail synthesizes connection_attempt events for forward-drop
-- flows that the conntrack -E NEW path cannot see (forward-chain drops
-- never reach the postrouting confirm hook, so they never emit IPCT_NEW).
-- Every per-MAC drop rule emitted by render.lua now carries
--   log prefix "wh_drop:<mac>:<reason> " counter drop comment "wh_drop:…"
-- (kernel ring buffer, readable off logread — #1126) and the agent tails the
-- resulting stream (via the wifihaven-nflog-tail spool) + posts allowed=false
-- events.

local nflog = require("nflog")

describe("nflog.parse_line", function()

  -- Sample line shape based on what kernel-level nflog netlink consumers
  -- (logread / dmesg) emit when an `iptables-LOG`-style record is generated by
  -- the nft `log prefix` action. The exact framing varies by consumer;
  -- the parser is robust to leading kernel-log fluff before the
  -- `wh_drop:` token and to KEY=value field order after it.
  it("extracts mac, reason, src_ip, dst_ip from a typical nflog line", function()
    local line = "[12345.678] wh_drop:aa:bb:cc:11:22:33:Paused IN=br-lan OUT=eth0 " ..
                 "MAC=11:22:33:44:55:66:aa:bb:cc:11:22:33:08:00 " ..
                 "SRC=192.168.1.42 DST=1.2.3.4 LEN=60 PROTO=TCP SPT=54321 DPT=443"
    local ev = nflog.parse_line(line)
    assert.is_not_nil(ev)
    assert.equal("aa:bb:cc:11:22:33", ev.mac)
    assert.equal("Paused",            ev.reason)
    assert.equal("192.168.1.42",      ev.src_ip)
    assert.equal("1.2.3.4",           ev.dst_ip)
  end)

  it("parses every MacBlockReason value", function()
    for _, reason in ipairs({ "Paused", "Schedule", "TimeLimit", "Manual", "Unmanaged" }) do
      local line = "wh_drop:de:ad:be:ef:00:01:" .. reason ..
                   " SRC=10.0.0.5 DST=8.8.8.8 PROTO=UDP DPT=53"
      local ev = nflog.parse_line(line)
      assert.is_not_nil(ev, "expected to parse reason=" .. reason)
      assert.equal(reason, ev.reason)
      assert.equal("de:ad:be:ef:00:01", ev.mac)
    end
  end)

  it("parses the per-host (eb_) drop reason `host`", function()
    local line = "wh_drop:aa:bb:cc:11:22:33:host " ..
                 "SRC=192.168.1.42 DST=1.2.3.4 PROTO=TCP DPT=443"
    local ev = nflog.parse_line(line)
    assert.is_not_nil(ev)
    assert.equal("host", ev.reason)
  end)

  -- #1645: post-rollout render.lua emits `wh_drop:<mac>:host:<host>` so the
  -- nflog parser pulls the matched eb_<host> rule's host straight through
  -- as reason=`host:<host>`. Same `(%S+)` capture as `category:<id>`; no
  -- prefix translation step.
  it("parses the per-host eb_ drop reason `host:<host>` (#1645)", function()
    local line = "wh_drop:aa:bb:cc:11:22:33:host:youtubei.googleapis.com " ..
                 "SRC=192.168.1.42 DST=1.2.3.4 PROTO=TCP DPT=443"
    local ev = nflog.parse_line(line)
    assert.is_not_nil(ev)
    assert.equal("host:youtubei.googleapis.com", ev.reason)
  end)

  it("parses the per-category (bl_) drop reason `category:<id>`", function()
    local line = "wh_drop:aa:bb:cc:11:22:33:category:ads " ..
                 "SRC=192.168.1.42 DST=1.2.3.4 PROTO=TCP DPT=443"
    local ev = nflog.parse_line(line)
    assert.is_not_nil(ev)
    assert.equal("category:ads", ev.reason)
  end)

  it("parses the blockIpOnly drop reason `ip_only`", function()
    local line = "wh_drop:aa:bb:cc:11:22:33:ip_only " ..
                 "SRC=192.168.1.42 DST=1.2.3.4 PROTO=TCP DPT=443"
    local ev = nflog.parse_line(line)
    assert.is_not_nil(ev)
    assert.equal("ip_only", ev.reason)
  end)

  it("returns nil for a line missing the wh_drop: token", function()
    local ev = nflog.parse_line("some unrelated syslog line about cron")
    assert.is_nil(ev)
  end)

  it("returns nil when SRC/DST are missing (incomplete kernel log)", function()
    local line = "wh_drop:aa:bb:cc:11:22:33:Paused PROTO=TCP DPT=443"
    local ev = nflog.parse_line(line)
    assert.is_nil(ev)
  end)
end)

-- ── #2647: block-page DNAT records ────────────────────────────────────────
--
-- The NAT path (chain wifihaven_block_nat, prerouting) redirects TCP 80/443
-- to the local block-page listener. Prerouting runs BEFORE the forward hook
-- and the rewritten packet is delivered to INPUT, so it never reaches the
-- filter chain's log/drop rules — pre-#2647 the blocks users actually SAW
-- produced no event at all. render.lua now emits a rate-limited
-- `log prefix "wh_dnat:<mac>:<reason> "` ahead of each dnat/redirect rule,
-- carrying the SAME <reason> vocabulary as the drop path. The tail must
-- ingest it identically, so one kernel-log channel feeds both paths.

describe("nflog.parse_line #2647 block-page DNAT records", function()

  it("extracts mac, reason, src_ip, dst_ip from a wh_dnat line", function()
    local line = "[12345.678] wh_dnat:aa:bb:cc:11:22:33:host:neverssl.com IN=br-lan OUT= " ..
                 "MAC=11:22:33:44:55:66:aa:bb:cc:11:22:33:08:00 " ..
                 "SRC=192.168.1.42 DST=1.2.3.4 LEN=60 PROTO=TCP SPT=54321 DPT=80"
    local ev = nflog.parse_line(line)
    assert.is_not_nil(ev)
    assert.equal("aa:bb:cc:11:22:33",     ev.mac)
    assert.equal("host:neverssl.com",     ev.reason)
    assert.equal("192.168.1.42",          ev.src_ip)
    assert.equal("1.2.3.4",               ev.dst_ip)
  end)

  -- Identical vocabulary, not a parallel one: whatever the drop path can say,
  -- the DNAT path says the same way (docs/process/single-source-of-truth.md).
  it("parses the whole reason vocabulary on the wh_dnat prefix", function()
    for _, reason in ipairs({ "Paused", "Schedule", "TimeLimit", "Manual", "Unmanaged",
                              "DefaultDeny", "blocked", "ip_only", "global_block",
                              "host:tiktok.com", "category:ads" }) do
      local line = "wh_dnat:de:ad:be:ef:00:01:" .. reason ..
                   " SRC=10.0.0.5 DST=8.8.8.8 PROTO=TCP DPT=80"
      local ev = nflog.parse_line(line)
      assert.is_not_nil(ev, "expected to parse reason=" .. reason)
      assert.equal(reason, ev.reason)
      assert.equal("de:ad:be:ef:00:01", ev.mac)
    end
  end)

  it("parses a v6 wh_dnat redirect record", function()
    local line = "wh_dnat:aa:bb:cc:11:22:33:Schedule " ..
                 "SRC=2001:db8::42 DST=2606:4700::1111 PROTO=TCP DPT=443"
    local ev = nflog.parse_line(line)
    assert.is_not_nil(ev)
    assert.equal("2606:4700::1111", ev.dst_ip)
    assert.equal("Schedule",        ev.reason)
  end)

  it("still returns nil for an unrelated line", function()
    assert.is_nil(nflog.parse_line("wh_other:aa:bb:cc:11:22:33:Paused SRC=1.1.1.1 DST=2.2.2.2"))
  end)
end)

describe("nflog.run #2647 does not double-count a redirected flow", function()

  -- A flow must not produce both a DNAT event and a drop event. The two
  -- enforcement paths are mutually exclusive per packet (a DNAT'd packet
  -- never reaches the forward hook), but a device hitting the same host over
  -- both TCP/443 (redirected) and QUIC/UDP 443 (dropped) can produce one line
  -- of each — the existing per-(mac, dst_ip, hostname) dedup must collapse
  -- them into a single connection_attempt, exactly as it already does for two
  -- drop lines.
  it("collapses a wh_dnat and a wh_drop line for the same (mac, dst) into one event", function()
    local lines = {
      "wh_dnat:aa:bb:cc:11:22:33:host:neverssl.com SRC=192.168.1.42 DST=1.2.3.4 PROTO=TCP DPT=80",
      "wh_drop:aa:bb:cc:11:22:33:host:neverssl.com SRC=192.168.1.42 DST=1.2.3.4 PROTO=UDP DPT=443",
    }
    local i, events = 0, {}
    nflog.run({
      read_fn         = function() i = i + 1; return lines[i] end,
      batcher         = { add = function(ev) events[#events + 1] = ev end },
      lookup_hostname = function(_) return "neverssl.com" end,
      ts_fn           = function() return "2026-08-08T00:00:00Z" end,
      now_fn          = function() return 1000 end,
      window_seconds  = 60,
    })
    assert.equal(1, #events)
    assert.equal(false, events[1].allowed)
    assert.equal("host:neverssl.com", events[1].reason)
  end)

  it("synthesizes a connection_attempt from a wh_dnat line alone", function()
    local lines = {
      "wh_dnat:aa:bb:cc:11:22:33:host:neverssl.com SRC=192.168.1.42 DST=1.2.3.4 PROTO=TCP DPT=80",
    }
    local i, events = 0, {}
    nflog.run({
      read_fn         = function() i = i + 1; return lines[i] end,
      batcher         = { add = function(ev) events[#events + 1] = ev end },
      lookup_hostname = function(_) return "neverssl.com" end,
      ts_fn           = function() return "2026-08-08T00:00:00Z" end,
      now_fn          = function() return 1000 end,
    })
    assert.equal(1, #events)
    assert.equal("connection_attempt", events[1]["type"])
    assert.same({ type = "fqdn", value = "neverssl.com" }, events[1].host)
  end)
end)

describe("nflog.build_event", function()
  it("builds a connection_attempt with allowed=false and the parsed reason", function()
    local ev = nflog.build_event({
      mac      = "aa:bb:cc:11:22:33",
      dst_ip   = "1.2.3.4",
      hostname = "youtube.com",
      reason   = "Paused",
      ts       = "2026-05-27T12:00:00Z",
    })
    assert.equal("connection_attempt", ev["type"])
    assert.equal("aa:bb:cc:11:22:33",  ev.mac)
    assert.equal(false,                ev.allowed)
    assert.equal("Paused",             ev.reason)
    assert.equal("1.2.3.4",            ev.destIp)
    assert.equal("2026-05-27T12:00:00Z", ev.ts)
    assert.same({ type = "fqdn", value = "youtube.com" }, ev.host)
  end)

  it("falls back to ipv4 host tag when hostname is nil", function()
    local ev = nflog.build_event({
      mac    = "aa:bb:cc:11:22:33",
      dst_ip = "1.2.3.4",
      reason = "TimeLimit",
      ts     = "2026-05-27T12:00:00Z",
    })
    assert.same({ type = "ipv4", value = "1.2.3.4" }, ev.host)
  end)

  it("falls back to ipv6 host tag when dst_ip contains a colon", function()
    local ev = nflog.build_event({
      mac    = "aa:bb:cc:11:22:33",
      dst_ip = "2001:db8::1",
      reason = "Schedule",
      ts     = "2026-05-27T12:00:00Z",
    })
    assert.same({ type = "ipv6", value = "2001:db8::1" }, ev.host)
  end)
end)

describe("nflog.new_dedup", function()
  it("suppresses a duplicate (mac, dst_ip, hname) within the window", function()
    local now    = 1000
    local dedup  = nflog.new_dedup({ window_seconds = 10, now_fn = function() return now end })
    assert.is_true(dedup.allow("aa:bb:cc:11:22:33", "1.2.3.4", "youtube.com"))
    -- Same key inside the window → suppress.
    assert.is_false(dedup.allow("aa:bb:cc:11:22:33", "1.2.3.4", "youtube.com"))
    -- Different dst_ip → allowed.
    assert.is_true(dedup.allow("aa:bb:cc:11:22:33", "5.6.7.8", "youtube.com"))
    -- Same key but window has elapsed → allowed.
    now = now + 11
    assert.is_true(dedup.allow("aa:bb:cc:11:22:33", "1.2.3.4", "youtube.com"))
  end)

  it("treats nil hostname as its own bucket distinct from an attributed hostname", function()
    local now   = 1000
    local dedup = nflog.new_dedup({ window_seconds = 10, now_fn = function() return now end })
    assert.is_true(dedup.allow("aa:bb:cc:11:22:33", "1.2.3.4", nil))
    assert.is_false(dedup.allow("aa:bb:cc:11:22:33", "1.2.3.4", nil))
    -- Same flow once attribution arrives — counted again because the key changed.
    assert.is_true(dedup.allow("aa:bb:cc:11:22:33", "1.2.3.4", "youtube.com"))
  end)
end)

describe("nflog.run (end-to-end with injected reader + batcher)", function()
  it("feeds parsed events into the batcher, deduped per (mac, dst_ip, hname)", function()
    local lines = {
      "wh_drop:aa:bb:cc:11:22:33:Paused SRC=192.168.1.42 DST=1.2.3.4 PROTO=TCP DPT=443",
      -- duplicate within the window — should be suppressed
      "wh_drop:aa:bb:cc:11:22:33:Paused SRC=192.168.1.42 DST=1.2.3.4 PROTO=TCP DPT=443",
      "wh_drop:aa:bb:cc:11:22:33:Paused SRC=192.168.1.42 DST=5.6.7.8 PROTO=TCP DPT=443",
      "an unrelated syslog line",
      "wh_drop:de:ad:be:ef:00:01:Unmanaged SRC=192.168.1.99 DST=9.9.9.9 PROTO=UDP DPT=53",
    }
    local i = 0
    local read_fn = function()
      i = i + 1
      return lines[i]
    end
    local batched = {}
    local batcher = { add = function(_, ev) end }
    batcher.add = function(ev) batched[#batched + 1] = ev end

    nflog.run({
      read_fn        = read_fn,
      batcher        = batcher,
      now_fn         = function() return 1000 end,
      ts_fn          = function() return "2026-05-27T12:00:00Z" end,
      lookup_hostname = function(_) return nil end,
      window_seconds = 60,
    })

    assert.equal(3, #batched)
    assert.equal("aa:bb:cc:11:22:33", batched[1].mac)
    assert.equal(false,               batched[1].allowed)
    assert.equal("Paused",            batched[1].reason)
    assert.equal("1.2.3.4",           batched[1].destIp)
    assert.equal("5.6.7.8",           batched[2].destIp)
    assert.equal("de:ad:be:ef:00:01", batched[3].mac)
    assert.equal("Unmanaged",         batched[3].reason)
  end)

  it("attributes hostname via the injected lookup", function()
    local lines = {
      "wh_drop:aa:bb:cc:11:22:33:Paused SRC=192.168.1.42 DST=1.2.3.4 PROTO=TCP DPT=443",
    }
    local i = 0
    local read_fn = function() i = i + 1; return lines[i] end
    local batched = {}
    nflog.run({
      read_fn = read_fn,
      batcher = { add = function(ev) batched[#batched + 1] = ev end },
      now_fn  = function() return 1000 end,
      ts_fn   = function() return "2026-05-27T12:00:00Z" end,
      lookup_hostname = function(ip)
        if ip == "1.2.3.4" then return "youtube.com" end
        return nil
      end,
      window_seconds = 60,
    })
    assert.equal(1, #batched)
    assert.same({ type = "fqdn", value = "youtube.com" }, batched[1].host)
  end)

  -- #1793: the kernel netfilter LOG action behind every wh_drop line emits the
  -- v6 DST in FULLY-EXPANDED zero-padded form, but the dns cache is keyed by the
  -- COMPRESSED form dnsmasq logs. Before the fix, the agent's lookup_hostname
  -- (a tbl[canon_ip(dst_ip)] index over the cache snapshot) missed for blocked
  -- v6 flows and the event recorded a bare ipv6 literal. This pins the
  -- end-to-end path: an expanded DST resolves to the FQDN stored under the
  -- compressed key.
  it("attributes a v6 drop whose DST= is expanded but the cache key is compressed (#1793)", function()
    local dns_log   = require("dns_log")
    local host_norm = require("host_norm")
    -- The cache snapshot as dns-tail writes it: COMPRESSED v6 key.
    local snapshot = "2607:f8b0:400f:801::2002\tpagead2.googlesyndication.com\t1000\n"
    local tbl = dns_log.load_table(snapshot, 3600, 1000)
    -- Production lookup_hostname canonicalizes the query key (wifihaven-agent).
    local lookup_hostname = function(ip) return tbl[host_norm.canon_ip(ip)] end

    -- The wh_drop line as it actually appears in logread: EXPANDED DST=.
    local lines = {
      "wh_drop:04:72:ef:d6:e4:5a:category:ads SRC=2601:280:4700:f32::49df "
        .. "DST=2607:f8b0:400f:0801:0000:0000:0000:2002 PROTO=UDP DPT=443",
    }
    local i = 0
    local read_fn = function() i = i + 1; return lines[i] end
    local batched = {}
    nflog.run({
      read_fn = read_fn,
      batcher = { add = function(ev) batched[#batched + 1] = ev end },
      now_fn  = function() return 1000 end,
      ts_fn   = function() return "2026-06-19T12:00:00Z" end,
      lookup_hostname = lookup_hostname,
      window_seconds = 60,
    })

    assert.equal(1, #batched)
    assert.same({ type = "fqdn", value = "pagead2.googlesyndication.com" },
                batched[1].host)
    assert.equal("category:ads", batched[1].reason)
    assert.equal(false,          batched[1].allowed)
  end)
end)

describe("nflog.drain_file (#1126 production reader — file-offset tail)", function()
  -- The production reader cannot block on logread; the wifihaven-nflog-tail
  -- sidecar owns the blocking `logread -f` and appends wh_drop: lines to a
  -- tmpfs spool. The agent drains new COMPLETE lines from that spool on each
  -- cooperative tick, tracking a byte offset so a line is never re-read.

  local tmp_path

  local function write_file(path, content)
    local f = assert(io.open(path, "w"))
    f:write(content)
    f:close()
  end

  local function append_file(path, content)
    local f = assert(io.open(path, "a"))
    f:write(content)
    f:close()
  end

  before_each(function()
    tmp_path = os.tmpname()
  end)

  after_each(function()
    if tmp_path then os.remove(tmp_path) end
  end)

  it("returns {} and offset 0 when the spool file does not exist", function()
    local state = { offset = 0 }
    local lines = nflog.drain_file("/no/such/file/wifihaven-nflog", state)
    assert.same({}, lines)
    assert.equal(0, state.offset)
  end)

  it("drains complete lines and advances the offset past them", function()
    write_file(tmp_path,
      "wh_drop:aa:bb:cc:11:22:33:Paused SRC=192.168.1.42 DST=1.2.3.4 DPT=443\n" ..
      "wh_drop:de:ad:be:ef:00:01:Schedule SRC=192.168.1.99 DST=9.9.9.9 DPT=53\n")
    local state = { offset = 0 }
    local lines = nflog.drain_file(tmp_path, state)
    assert.equal(2, #lines)
    assert.truthy(lines[1]:find("wh_drop:aa:bb:cc:11:22:33:Paused", 1, true))
    assert.truthy(lines[2]:find("wh_drop:de:ad:be:ef:00:01:Schedule", 1, true))
    -- A second drain with the same state reads nothing new.
    assert.same({}, nflog.drain_file(tmp_path, state))
  end)

  it("only consumes up to the last newline, leaving a partial trailing line", function()
    write_file(tmp_path, "wh_drop:aa:bb:cc:11:22:33:Paused SRC=1.1.1.1 DST=2.2.2.2 DPT=443\n" ..
                         "wh_drop:aa:bb:cc:11:22:33:host SRC=1.1.1.1 DST=3.3.3.3")  -- no trailing \n
    local state = { offset = 0 }
    local lines = nflog.drain_file(tmp_path, state)
    assert.equal(1, #lines)
    -- Once the writer finishes the partial line, the next drain picks it up whole.
    append_file(tmp_path, " DPT=80\n")
    local more = nflog.drain_file(tmp_path, state)
    assert.equal(1, #more)
    assert.truthy(more[1]:find("DST=3.3.3.3 DPT=80", 1, true))
  end)

  it("resets the cursor to 0 when the spool is truncated/rotated (size < offset)", function()
    write_file(tmp_path, "wh_drop:aa:bb:cc:11:22:33:Paused SRC=1.1.1.1 DST=2.2.2.2 DPT=443\n")
    local state = { offset = 0 }
    assert.equal(1, #nflog.drain_file(tmp_path, state))
    assert.is_true(state.offset > 0)
    -- Sidecar rotated the spool (truncate-in-place): file is now smaller than
    -- the saved offset, so the reader must rewind to 0 and read the new content.
    write_file(tmp_path, "wh_drop:99:88:77:66:55:44:Manual DST=4.4.4.4\n")
    local lines = nflog.drain_file(tmp_path, state)
    assert.equal(1, #lines)
    assert.truthy(lines[1]:find("wh_drop:99:88:77:66:55:44:Manual", 1, true))
  end)

  it("feeds drained lines through run() with a persistent cross-tick dedup", function()
    -- Tick 1: two distinct flows.
    write_file(tmp_path,
      "wh_drop:aa:bb:cc:11:22:33:Paused SRC=192.168.1.42 DST=1.2.3.4 DPT=443\n" ..
      "wh_drop:aa:bb:cc:11:22:33:Paused SRC=192.168.1.42 DST=1.2.3.4 DPT=443\n")
    local state = { offset = 0 }
    local dedup = nflog.new_dedup({ window_seconds = 60, now_fn = function() return 1000 end })
    local batched = {}
    local batcher = { add = function(ev) batched[#batched + 1] = ev end }

    local function tick()
      local lines = nflog.drain_file(tmp_path, state)
      if #lines == 0 then return end
      local i = 0
      nflog.run({
        read_fn = function() i = i + 1; return lines[i] end,
        batcher = batcher,
        dedup   = dedup,
        ts_fn   = function() return "2026-05-27T12:00:00Z" end,
        lookup_hostname = function(_) return nil end,
      })
    end

    tick()
    assert.equal(1, #batched)  -- duplicate within the window collapsed
    -- Tick 2: the SAME flow line appears again, still inside the dedup window.
    append_file(tmp_path,
      "wh_drop:aa:bb:cc:11:22:33:Paused SRC=192.168.1.42 DST=1.2.3.4 DPT=443\n")
    tick()
    assert.equal(1, #batched)  -- cross-tick dedup suppressed it (persistent dedup)
  end)
end)

-- #2620: the drop-event pipeline cadence (drain the nflog spool, then flush the
-- shared events batcher).
--
-- nflog_poll_interval (5s) + event_flush_interval (10s) exist to bound HTTP
-- REQUEST volume: each flush is one POST /api/router/events. When the ws link
-- is healthy the events instead ride an already-open persistent socket via the
-- outbound tee, so the request-volume argument buys nothing and the batching is
-- pure added latency (up to 15s of the measured 26s drop-to-SPA delay). On the
-- HTTP fallback path the interval still holds, unchanged.
describe("nflog.pipeline_interval (#2620)", function()
  it("keeps the HTTP-path interval when the ws link is not healthy", function()
    assert.are.equal(5, nflog.pipeline_interval(5, 1, false))
  end)

  it("drops to the agent tick interval on the ws path", function()
    assert.are.equal(1, nflog.pipeline_interval(5, 1, true))
  end)

  -- The ws path must never be SLOWER than the HTTP path it exists to beat, no
  -- matter what conntrack_tick_interval has been tuned to (the shipped config
  -- invites tuning it, bounded only by the activity sampler).
  it("never lets the ws path come out slower than the HTTP cadence", function()
    assert.are.equal(5, nflog.pipeline_interval(5, 30, true))
    assert.are.equal(5, nflog.pipeline_interval(5, 5, true))
  end)
end)

describe("nflog.due (#2620)", function()
  it("is false before the interval has elapsed and true at/after it", function()
    assert.is_false(nflog.due(103, 100, 5))
    assert.is_true(nflog.due(105, 100, 5))
    assert.is_true(nflog.due(140, 100, 5))
  end)

  it("fires on the first tick against the zero anchor the agent boots with", function()
    -- ts.last_nflog_run / ts.last_nflog_gc start at 0 and `mono` is
    -- clock.monotonic_seconds() (uptime), so the very first on_tick is already
    -- far past any interval — no cold-start stall.
    assert.is_true(nflog.due(3600, 0, 5))
    -- Degenerate: an anchor equal to now is genuinely not due yet.
    assert.is_false(nflog.due(0, 0, 5))
  end)

  -- Pinned together: on the ws path the step runs about once a second, NOT on
  -- every call. Ten on_tick calls inside one second must yield one run.
  it("runs once per ws interval across a burst of on_tick calls", function()
    local anchor, runs = 0, 0
    local interval = nflog.pipeline_interval(5, 1, true)
    for i = 1, 10 do
      local mono = i * 0.1          -- ten calls spread over one second
      if nflog.due(mono, anchor, interval) then
        anchor = mono
        runs = runs + 1
      end
    end
    assert.are.equal(1, runs)
  end)
end)
